### ISSUE TITLE
cubical falling over because of memory issues on idia

### ISSUE THREAD

**Issue by healytwin1** [caracal-pipeline/caracal#1017]
I have been trying to run the self-cal worker, but it is failing at the cubical step on the first selfcal loop. I have tried this on both my desktop (running podman) and on ilifu (with singularity), the errors are not the same, but the fail at the same point. I have used the same config file and the same dataset.

The podman error:
```
# INFO       - 06:48:50 - main               [0.1/0.9 2.1/2.2 0.9Gb] Exiting with exception: BrokenProcessPool(A process in the process pool was terminated abruptly while the future was running or pending.)
#  Traceback (most recent call last):
#   File "/usr/local/lib/python3.6/dist-packages/cubical/main.py", line 540, in main
#     stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts, out_opts)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/workers.py", line 214, in run_process_loop
#     return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts, out_opts)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/workers.py", line 274, in _run_multi_process_loop
#     if not io_futures[itile].result():
#   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
#     return self.__get_result()
#   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
#     raise self._exception
# concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
# 
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 57, in <module>
#     subprocess.check_call(shlex.split(_runc))
#   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['gocubical', '--sol-jones', 'G', '--data-ms', '/stimela_mount/msdir/A2626_1563407160_XXYY-Abell2626_corr.ms', '--data-column', 'DATA', '--data-time-chunk', '360', '--data-freq-chunk', '0', '--model-list', 'MODEL_DATA', '--model-ddes', 'never', '--montblanc-dtype', 'float', '--weight-column', 'WEIGHT', '--flags-apply', '-cubical', '--madmax-enable', '1', '--madmax-estimate', 'corr', '--madmax-plot', '1', '--madmax-threshold', '0,10', '--sel-diag', '1', '--sol-term-iters', '5,0', '--bbc-save-to', '/stimela_mount/output/continuum/selfcal_products/bbc-gains-1-A2626_1563407160_XXYY-Abell2626_corr.parmdb', '--dist-ncpu', '7', '--dist-max-chunks', '2', '--out-name', '/stimela_mount/output/continuum/selfcal_products/A2626_E1_v1_A2626_1563407160_XXYY-Abell2626_corr_1_cubical', '--out-overwrite', '1', '--out-mode', 'sc', '--out-casa-gaintables', '1', '--out-plots', '1', '--dist-nworker', '0', '--log-memory', '1', '--log-boring', '1', '--g-time-int', '120', '--g-freq-int', '0', '--g-clip-low', '0.5', '--g-clip-high', '2.0', '--g-solvable', '1', '--g-type', 'phase-diag', '--g-save-to', '/stimela_mount/output/continuum/selfcal_products/g-phase-gains-1-A2626_1563407160_XXYY-Abell2626_corr.parmdb', '--g-update-type', 'phase-diag', '--g-max-prior-error', '0.1', '--g-max-post-error', '0.1', '--degridding-OverS', '11', '--degridding-Support', '7', '--degridding-Nw', '100', '--degridding-wmax', '0', '--degridding-Padding', '1.7', '--degridding-NDegridBand', '16', '--degridding-MaxFacetSize', '0.25', '--degridding-MinNFacetPerAxis', '1']' returned non-zero exit status 1.
2020-04-28 08:48:56 CARACal.Stimela.calibrate_cubical_1_0 ERROR: podman returns error code 1
2020-04-28 08:48:56 CARACal.Stimela.calibrate_cubical_1_0 ERROR: job failed at 2020-04-28 08:48:56.890757 after 0:02:26.837220
2020-04-28 08:48:57 CARACal ERROR: Job 'calibrate_cubical_1_0:: Calibrate step 1 ms=A2626_1563407160_XXYY-Abell2626_corr.ms' failed: podman returns error code 1 [PipelineException]
2020-04-28 08:48:57 CARACal INFO:   More information can be found in the logfile at output/log-caracal-20200428-065326.txt

```

and the singularity error:
```
# WARNING    - 10:11:43 - solver             [x04] [59.8/70.7 62.7/73.6 25.6Gb] 'G' D0T3F0 Stations 13 (1/62) fully flagged due to low SNR. These stations may be faulty or your SNR requirements (max-pri
or-error) are not met. New flags will be raised for this chunk of data
# WARNING    - 10:11:47 - solver             [x03] [60.2/71.2 63.1/74.1 25.6Gb] 'G' D0T2F0 Stations 13 (1/62) fully flagged due to low SNR. These stations may be faulty or your SNR requirements (max-pri
or-error) are not met. New flags will be raised for this chunk of data
# INFO       - 10:12:11 - ms_tile            [io] [35.2/47.5 43.4/50.3 25.6Gb]   22290694 (3.06%) model visibilities flagged as 0/inf/nan
# ERROR      - 10:14:13 - solver             [x03] [71.2/77.2 75.5/80.2 25.6Gb] Solver for tile 1 chunk D0T2F0 failed with exception: Unable to allocate 10.7 GiB for an array with shape (150, 621, 62, 6
2, 2, 2) and data type complex64
# INFO       - 10:14:13 - solver             [x03] [71.2/77.2 75.5/80.2 25.6Gb] Traceback (most recent call last):
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 857, in run_solver
#     corr_vis = solver_machine.run()
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 680, in run
#     SolveOnly.run(self)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 664, in run
#     self.sol_opts, label=self.label)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 353, in _solve_gains
#     stats.estimate_noise(resid_arr, flags_arr, residuals=True)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/statistics.py", line 160, in estimate_noise
#     deltavis2[:, 1:, ...]  = np.square(abs(data[0, :, 1:, ...] - data[0, :, :-1, ...])).sum(axis=(-2,-1))
# MemoryError: Unable to allocate 10.7 GiB for an array with shape (150, 621, 62, 62, 2, 2) and data type complex64
# Process Process-4:
# Traceback (most recent call last):
#   File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
#     r = call_item.fn(*call_item.args, **call_item.kwargs)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 857, in run_solver
#     corr_vis = solver_machine.run()
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 680, in run
#     SolveOnly.run(self)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 664, in run
#     self.sol_opts, label=self.label)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 353, in _solve_gains
#     stats.estimate_noise(resid_arr, flags_arr, residuals=True)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/statistics.py", line 160, in estimate_noise
#     deltavis2[:, 1:, ...]  = np.square(abs(data[0, :, 1:, ...] - data[0, :, :-1, ...])).sum(axis=(-2,-1))
# MemoryError: Unable to allocate 10.7 GiB for an array with shape (150, 621, 62, 62, 2, 2) and data type complex64
# 
# During handling of the above exception, another exception occurred:
# 
# Traceback (most recent call last):
#   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
#     self.run()
#   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
#     self._target(*self._args, **self._kwargs)
#   File "/usr/lib/python3.6/concurrent/futures/process.py", line 178, in _process_worker
#     result_queue.put(_ResultItem(call_item.work_id, exception=exc))
#   File "/usr/lib/python3.6/multiprocessing/queues.py", line 341, in put
#     obj = _ForkingPickler.dumps(obj)
#   File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
#     cls(buf, protocol).dump(obj)
# _pickle.PicklingError: Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError
# INFO       - 10:15:01 - ms_tile            [io] [41.2/48.0 43.9/50.7 31.1Gb]   22290694 (3.06%) visibilities flagged due to 0/inf/nan model
# INFO       - 10:15:01 - main               [io] [7.6/48.0 10.2/50.7 31.1Gb] I/O job(s) complete
# INFO       - 10:15:02 - main               [0.8/0.8 3.8/3.8 30.9Gb] Exiting with exception: BrokenProcessPool(A process in the process pool was terminated abruptly while the future was running or pending.)
#  Traceback (most recent call last):
#   File "/usr/local/lib/python3.6/dist-packages/cubical/main.py", line 540, in main
#     stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts, out_opts)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/workers.py", line 214, in run_process_loop
#     return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts, out_opts)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/workers.py", line 300, in _run_multi_process_loop
#     stats = future.result()
#   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
#     return self.__get_result()
#   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
#     raise self._exception
# concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
# 
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 57, in <module>
#     subprocess.check_call(shlex.split(_runc))
#   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['gocubical', '--sol-jones', 'G', '--data-ms', '/stimela_mount/msdir/A2626_1563407160_XXYY-Abell2626_corr.ms', '--data-column', 'DATA', '--data-time-chunk', '360', '--data-freq-chunk', '0', '--model-list', 'MODEL_DATA', '--model-ddes', 'never', '--montblanc-dtype', 'float', '--weight-column', 'WEIGHT', '--flags-apply', '-cubical', '--madmax-enable', '1', '--madmax-estimate', 'corr', '--madmax-plot', '1', '--madmax-threshold', '0,10', '--sel-diag', '1', '--sol-term-iters', '5,0', '--bbc-save-to', '/stimela_mount/output/continuum/selfcal_products/bbc-gains-1-A2626_1563407160_XXYY-Abell2626_corr.parmdb', '--dist-ncpu', '7', '--dist-max-chunks', '2', '--out-name', '/stimela_mount/output/continuum/selfcal_products/A2626_E1_v1_A2626_1563407160_XXYY-Abell2626_corr_1_cubical', '--out-overwrite', '1', '--out-mode', 'sc', '--out-casa-gaintables', '1', '--out-plots', '1', '--dist-nworker', '0', '--log-memory', '1', '--log-boring', '1', '--g-time-int', '120', '--g-freq-int', '0', '--g-clip-low', '0.5', '--g-clip-high', '2.0', '--g-solvable', '1', '--g-type', 'phase-diag', '--g-save-to', '/stimela_mount/output/continuum/selfcal_products/A2626_E1_v1-g-phase-gains-1-A2626_1563407160_XXYY-Abell2626_corr.parmdb', '--g-update-type', 'phase-diag', '--g-max-prior-error', '0.1', '--g-max-post-error', '0.1', '--degridding-OverS', '11', '--degridding-Support', '7', '--degridding-Nw', '100', '--degridding-wmax', '0', '--degridding-Padding', '1.7', '--degridding-NDegridBand', '16', '--degridding-MaxFacetSize', '0.25', '--degridding-MinNFacetPerAxis', '1']' returned non-zero exit status 1.
2020-04-28 10:15:03 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR: singularity returns error code 1
```

**Comment by healytwin1** [comment]
So we step past the initial memory allocation error on the HighMem node, but it fails a little later on because it cannot allocate 1.85gb for an array... (see the attached log: 
[caracal_E1-1274714-stdout.log](https://github.com/caracal-pipeline/caracal/files/4610896/caracal_E1-1274714-stdout.log) )

I am currently running a test on one of the normal nodes that has had `ulimit -l` set to be unlimited. Will report back on that when it has finished running.

**Comment by o-smirnov** [comment]
Does the HighMem node have a ``ulimit -l`` in place?

**Comment by Jordatious** [comment]
No, the nodes from the HighMem partition have the same locked memory configuration as the nodes from the Main partition. Btw, that is the default locked memory configuration, so it was not changed either way. We've made a node available to @healytwin1 within a reservation where there is no limit on locked memory, to see if that changes anything. If the test is successful, we should be able to change it across the board, particularly since we don't use swap space. Also @healytwin1, if CubiCal is using it, it's useful to check that nothing exists in `/dev/shm`.

**Comment by healytwin1** [comment]
So I have been running caracal on the unlimited memory lock node. (@Jordatious there is nothing in `/dev/shm`).

I ran a first test with ncpu = 5, but it failed because the max memory was going to exceed system memory (see attached log: 
[caracal-test1.txt](https://github.com/caracal-pipeline/caracal/files/4616650/caracal-test1.txt)
 )

The second test with ncpu = 4 was within the max memory limits, but hit an error slightly later on as it could not assign 5gb. It managed to step past that error without failing though, but has been stuck at the same point for ~5hours (see log which I  downloaded at 17h41 for time reference: 
[caracal-test2.txt](https://github.com/caracal-pipeline/caracal/files/4616655/caracal-test2.txt)
)

**Comment by SpheMakh** [comment]
Looking at this

```
Per-solver (worker) memory use estimated at 41.59GiB: 17.61% of total system memory.
```

This must be an error in cubical, or it's memory are way off.

**Comment by o-smirnov** [comment]
Right, so no ``ulimit -l`` on that node, and we get the same problem, sigh...

@healytwin1, could you please try something else for us, run with an experimental branch. This is not likely to solve the problem, but it will give more informative logs:

* In your virtualenv, ``pip install git+https://github.com/ratt-ru/Stimela@cubical_ddf``.

* Run caracal with ``-debug``. You can use ``-sw selfcal`` to start at the selfcal worker right away.

* Wait for it to fall over and post the logs. :)

@JSKenyon, this is really pernicious, look below. The ``[35.8/76.9 41.2/79.7 30.8Gb]`` shows current and peak memory use. This is a 256GB node, we're barely using any RAM, and yet it tells us "Unable to allocate 5.43 GiB"? 
```
# INFO      13:01:51 - main               [io] [35.8/76.9 41.2/79.7 30.8Gb] I/O handler for load 1 save None failed with exception: Unable to allocate 5.43 GiB for an array with shape 
(1171800, 622, 2) and data type int32
# INFO      13:01:51 - main               [io] [35.8/76.9 41.2/79.7 30.8Gb] Traceback (most recent call last):
#   File "/usr/local/lib/python3.6/dist-packages/cubical/workers.py", line 457, in _io_handler
#     tile.load(load_model=load_model)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/data_handler/ms_tile.py", line 827, in load
#     flag_arr0[(self.bflagcol & self.dh._apply_bitflags) != 0] = FL.PRIOR
# MemoryError: Unable to allocate 5.43 GiB for an array with shape (1171800, 622, 2) and data type int32
# Process Process-1:
# Traceback (most recent call last):
#   File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
#     r = call_item.fn(*call_item.args, **call_item.kwargs)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/workers.py", line 457, in _io_handler
#     tile.load(load_model=load_model)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/data_handler/ms_tile.py", line 827, in load
#     flag_arr0[(self.bflagcol & self.dh._apply_bitflags) != 0] = FL.PRIOR
# MemoryError: Unable to allocate 5.43 GiB for an array with shape (1171800, 622, 2) and data type int32
```

**Comment by o-smirnov** [comment]
> This must be an error in cubical, or it's memory are way off.

Why? Do you find it too low? There's only 600-odd channels in this MS, so it doesn't look unreasonable to me. This is for a single worker, remember.

**Comment by SpheMakh** [comment]
It's not too low, but failing to allocate 17% of memory when you can use all of it sounds like a bug.

**Comment by o-smirnov** [comment]
The estimation is just that, an estimation, to give a warning up front. If you look at the actual memory use (inside the square brackets), the estimation is doing a reasonable job. It's being run with fairly conservative parameters, so the memory usage is low.

And it's not even failing to allocate 17%. It's failing to allocate a measly 5.43 GB!!!

But let's not be too hasty in calling it "a cubical bug". Smells more like some kind of unholy interaction between Python memory allocation (you can see by the trace it's deep within numpy that it fails), singularity, and something on the node.

**Comment by SpheMakh** [comment]
> And it's not even failing to allocate 17%. It's failing to allocate a measly 5.43 GB!!! 

I was referring to the first crash

**Comment by o-smirnov** [comment]
> In your virtualenv, ``pip install git+https://github.com/ratt-ru/Stimela@cubical_ddf``

One more time please (I pushed a small change). Unless you haven't done it yet.

**Comment by o-smirnov** [comment]
> I was referring to the first crash

Ah but if you read two lines down, it says "Total peak memory usage estimated at 241.15GiB: 102.11% of total system memory."

You're looking at per-worker usage which is always smaller.

**Comment by o-smirnov** [comment]
It's debatable what a reasonable "bomb out" threshold for peak memory use should be. I would go for 120% if there is swap space, 100% if there isn't, but that's a matter of discussion. And there's always ``--dist-safe 0`` to disable this entirely.

Be that as it may, at the moment it's doing exactly what it says on the box. There's just some real weirdness with the overall memory subsystem which we need to get to the bottom of.

**Comment by healytwin1** [comment]
> pip install git+https://github.com/ratt-ru/Stimela@cubical_ddf

I'm running this now.

**Comment by JSKenyon** [comment]
From my side, if @healytwin1's latest test fails, I would appreciate it if we can make some attempt to isolate this. This would require running CubiCal in isolation on whatever the pipeline has produced at the previous step. Currently, it is dying in CubiCal but the problem may not be in CubiCal itself - I believe that this is what both Oleg and I suspect as I do not believe this problem has been observed outside a pipeline/container.

**Comment by o-smirnov** [comment]
Yeah actually @Jordatious is there a way for me to log into the same node, so I can poke around the smoking ruins of @healytwin1's pipeline runs?

**Comment by healytwin1** [comment]
So that test failed: 
[caracal-test3.txt](https://github.com/caracal-pipeline/caracal/files/4620525/caracal-test3.txt)

**Comment by Jordatious** [comment]
Hey @o-smirnov, the smoking ruins will be on the filesystem across all ilifu nodes, including the login node, so @healytwin1 should be able to give you read access to those without the need to access this specific node or reservation.

**Comment by SpheMakh** [comment]
You welcome @o-smirnov 

```\              total        used        free      shared  buff/cache   available
# Mem:           236G         23G        211G        1.0M        1.9G        211G
# Swap:            0B          0B          0B
# time(seconds)        unlimited
# file(blocks)         unlimited
# data(kbytes)         unlimited
# stack(kbytes)        8192
# coredump(blocks)     unlimited
# memory(kbytes)       241172480
# locked memory(kbytes) unlimited
# process              967206
# nofiles              16384
# vmemory(kbytes)      unlimited
# locks                unlimited
# rtprio               0
# CONFIG='/stimela_mount/configfile'
# DISPLAY=':102'
# HOME='/users/juliahealy'
# IFS='
# '
# INPUT='/stimela_mount/input'
# LANG='C'
# LD_LIBRARY_PATH='/.singularity.d/libs'
# MSDIR='/stimela_mount/msdir'
# OPTIND='1'
# OUTPUT='/stimela_mount/output'
# PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
# PPID='48'
# PROMPT_COMMAND='PS1="Singularity> "; unset PROMPT_COMMAND'
# PS1='$ '
# PS2='> '
# PS4='+ '
# PWD='/users/juliahealy'
# SHLVL='1'
# SINGULARITY_APPNAME=''
# SINGULARITY_CONTAINER='/idia/projects/healy-a2626/stimela/stimela_cubical_1.5.00.sif'
# SINGULARITY_NAME='stimela_cubical_1.5.00.sif'
# STIMELA_MOUNT='/stimela_mount'
# TERM='xterm-256color'
# TMPDIR='/stimela_mount/output/tmp'
# XAUTHORITY='/stimela_mount/output/tmp/xvfb-run.zZsx4T/Xauthority'
```

**Comment by o-smirnov** [comment]
Yeah I've already looked at this, I see no smoking gun. Memory is free at the start.

(Bit of a mystery why the Python print() statements which are interspersed with those os.system() calls are not printing!... do you understand? I sure don't.)

As I said, I smell a similar rat in the shadems "no space left on device" problem, so let's focus on understanding that.

**Comment by o-smirnov** [comment]
> Hey @o-smirnov, the smoking ruins will be on the filesystem across all ilifu nodes, including the login node, so @healytwin1 should be able to give you read access to those without the need to access this specific node or reservation.

An excellent point @Jordatious, thanks! @healytwin1, could you please give me read permissions on where you're running this? ``/scratch/users/juliahealy/allthree2`` or something like that? I'm going to attempt to copy and reproduce...

(And thanks **a lot** for all the testing and the patience BTW...)

**Comment by healytwin1** [comment]
sure, but how do I give permissions to a single user?

**Comment by o-smirnov** [comment]
@Jordatious, I don't think you support ACLs on the filesystem, do you? I get an "Operation not supported".

@healytwin1, I don't think you can do a single user. Do you mind making the MS and config file world-readable for a bit so I can nab a copy?

**Comment by healytwin1** [comment]
@o-smirnov I think it should be readable: 
`drwxr-xr-x   8 juliahealy idia-group     33 May 12 23:13 allthree2`
The path is `/scratch/users/juliahealy/allthree2/`. There is only one config in the directory, and the msdir directory has the MS

**Comment by o-smirnov** [comment]
I think you need to do a chmod a+x on the parent dir as well:
```
$ ls -ld /scratch/users/juliahealy
drwxr-xr-- 21 juliahealy idia-healy-a2626 39 May 12 19:49 /scratch/users/juliahealy
```

**Comment by healytwin1** [comment]
done

**Comment by o-smirnov** [comment]
OK I got my copy, let's see if I can run it...

**Comment by o-smirnov** [comment]
@healytwin1 could you give me access again please, I need something from your ``input`` and ``output`` folders.

But I think I see the problem though. Or a combination of problems:

* Your selfcal time chunk and time solution intervals are way too high. I recommend a time chunk of -1 (i.e. let it choose automatically) and a time interval of... well... 240 timeslots is way too long to be useful anyway, so how about we try 16 and see?

* The setting of 240 (with ncpu 4) resulted in excessive memory use. So the MemoryError should have been taken at face value, it was quite banally running out of memory. But I was fooled by my own logging code. What I now realize is that the indicated memory footprints (in square brackets at every line) are **per worker**, not overall. Multiply them by 4 workers, of course the poor beast was out of memory!

* Reinforcing my error, the memory use estimation printed at the start is an underestimate...

Anyway I'd still like to test it on my node, but I'll need a copy of your output directory for that. But in the meantime you can also run with the suggested settings, and see what happens...

**Comment by Jordatious** [comment]
Looks like you've got permissions sorted. I've seen ACLs used on lifu before, but perhaps that was for CephFS, not BeeGFS.

**Comment by healytwin1** [comment]
> * Your selfcal time chunk and time solution intervals are way too high. I recommend a time chunk of -1 (i.e. let it choose automatically) and a time interval of... well... 240 timeslots is way too long to be useful anyway, so how about we try 16 and see?
> * The setting of 240 (with ncpu 4) resulted in excessive memory use. So the MemoryError should have been taken at face value, it was quite banally running out of memory. But I was fooled by my own logging code. What I now realize is that the indicated memory footprints (in square brackets at every line) are **per worker**, not overall. Multiply them by 4 workers, of course the poor beast was out of memory!


Eish, okay. I have adjusted the parameters and am re-running now.


> Anyway I'd still like to test it on my node, but I'll need a copy of your output directory for that. But in the meantime you can also run with the suggested settings, and see what happens...

I have opened the permissions again

**Comment by o-smirnov** [comment]
Cool, I grabbed what I needed. Happy testing!

**Comment by o-smirnov** [comment]
OK, with lower chunk and interval settings, it ran fine for me on a 256GB node. So I assume this problem is solved. I will improve the memory use reporting (https://github.com/ratt-ru/CubiCal/issues/376), and add a more informative MemoryError handler.

**Comment by healytwin1** [comment]
Yeah, mine now runs fine with the lower chunk settings.

**Comment by o-smirnov** [comment]
@JSKenyon, in the interest of posterity, I changed the memory counting code to do sums. With a chunk size of 120 (i.e. half of what it was), @healytwin1's job now prints:
```
INFO      18:37:02 - wisdom             [0.7 0.7 0.7 0.0Gb] Per-solver (worker) memory use estimated at 33.58GiB: 14.22% of total system memory.
INFO      18:37:02 - wisdom             [0.7 0.7 0.7 0.0Gb] Peak I/O memory use estimated at 48.33GiB: 20.47% of total system memory.
INFO      18:37:02 - wisdom             [0.7 0.7 0.7 0.0Gb] Total peak memory usage estimated at 149.07GiB: 63.12% of total system memory.
...
INFO      18:37:06 - data_handler       [0.7 0.7 0.7 0.0Gb] reading DATA
INFO      18:37:27 - data_handler       [11.5/12.2 11.2/11.6 10.9/11.0 0.0Gb] reading BITFLAG
INFO      18:38:11 - ms_tile            [17.5/18.2 17.2/17.6 16.9/17.0 0.0Gb]   13.58% input visibilities flagged and/or deselected
INFO      18:38:32 - data_handler       [19.9/20.7 19.6/20.0 19.3/19.4 10.0Gb] reading MODEL_DATA
INFO      18:38:57 - ms_tile            [26.0/26.7 25.7/26.1 25.4/25.5 10.0Gb]   22508830 (3.11%) model visibilities flagged as 0/inf/nan
INFO      18:42:50 - ms_tile            [32.0/32.7 31.7/32.1 31.4/31.5 15.4Gb]   22508830 (3.11%) visibilities flagged due to 0/inf/nan model
INFO      18:42:52 - main               [3.9/4.7 3.7/4.1 3.4/3.5 15.4Gb] I/O job(s) complete
INFO      18:42:52 - main               [3.9/4.7 3.7/4.1 3.4/3.5 15.4Gb] loading tile 1/7
INFO      18:42:52 - ms_tile            [3.9/4.7 3.7/4.1 3.4/3.5 15.4Gb] tile 1/7: reading MS rows 581994~1165940
INFO      18:42:52 - main               [0.7/4.7 0.4/4.1 0.1/3.5 15.4Gb] submitting solver jobs for tile 0/7
INFO      18:42:52 - main               [0.7/4.7 0.4/4.1 0.1/3.5 15.4Gb] WARNING: unrecognized worker process name 'ForkProcess-2'. Please inform the developers.
INFO      18:42:52 - main               [0.7/4.7 0.4/4.1 0.1/3.5 15.4Gb] WARNING: unrecognized worker process name 'ForkProcess-3'. Please inform the developers.
INFO      18:42:52 - main               [0.7/4.7 0.4/4.1 0.1/3.5 15.4Gb] WARNING: unrecognized worker process name 'ForkProcess-4'. Please inform the developers.
INFO      18:42:52 - data_handler       [3.9/4.7 3.7/4.1 3.4/3.5 15.4Gb] reading DATA
INFO      18:43:21 - data_handler       [14.8/67.8 14.3/65.3 14.2/64.6 15.4Gb] reading BITFLAG
INFO      18:44:18 - ms_tile            [20.8/120.4 20.3/118.0 20.2/117.3 15.4Gb]   9.22% input visibilities flagged and/or deselected
INFO      18:44:38 - data_handler       [23.2/138.6 22.8/136.2 22.7/135.5 25.4Gb] reading MODEL_DATA
INFO      18:45:08 - ms_tile            [29.3/159.3 28.9/157.0 28.8/156.3 25.4Gb]   22592448 (3.11%) model visibilities flagged as 0/inf/nan
WARNING   18:45:15 - solver             [14.3/124.6 13.9/122.3 13.8/121.7 25.4Gb] D0T1F0 (end solve) G: 10 iters, conv 0.00%, d/fl 1.61%, PGE 0.00829, stall 99.97%, chi^2 17.5 -> 17.68 (17.68), noise 0.159 -> 0.159 Shows signs of divergence. If you see this message often you may have significant RFI present in your data or your solution intervals are too short.
INFO      18:45:27 - solver             [14.4/144.1 13.9/141.9 13.8/141.3 25.6Gb] D0T1F0 has 12 (0.00%) new data flags: MadMax took out 12 visibilities (0 in final round)
WARNING   18:47:52 - solver             [16.4/164.2 16.0/162.3 15.8/161.7 26.1Gb] D0T3F0 (end solve) G: 10 iters, conv 0.00%, d/fl 1.61%, PGE 0.00841, stall 99.92%, chi^2 11.56 -> 11.67 (11.67), noise 0.157 -> 0.157 Shows signs of divergence. If you see this message often you may have significant RFI present in your data or your solution intervals are too short.
INFO      18:48:03 - solver             [16.5/166.9 16.0/164.9 15.9/164.4 26.2Gb] D0T3F0 has 192 (0.00%) new data flags: MadMax took out 192 visibilities (0 in final round)
```
The numbers now have the meaning "this worker/all workers" (RSS USS PSS SHM). Multiply this by 2, you can see how the old run was hitting the buffers.

This also shows that the wisdom module slightly under-estimates the peak usage.

**Comment by o-smirnov** [comment]
Here's what bothers me though (note to self and @JSKenyon, everyone else please ignore), the X in each X/Y is the worker's own usage, the Y is the total of all processes. We have four workers. It doesn't add up -- who's grabbing all that memory?

I'll add extra log statements to find out.
