### ISSUE TITLE
Null-ish visibilities in full test data

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1040]
Not sure if this is a bug or a feature, but I want to make sure I'm not the only one seeing this... I'm running the official full caratekit test and studying the plots carefully, and I see stuff like this in the initial data (AFTER flagging but BEFORE 1GC):

This is for gcal:

![image](https://user-images.githubusercontent.com/6470079/80866156-91a4de80-8c8d-11ea-90da-9cc7ace17104.png)

And this is for bpcal, which perhaps makes it obvious that only a few antennas are affected:

![image](https://user-images.githubusercontent.com/6470079/80866159-949fcf00-8c8d-11ea-8324-fd8f1da22150.png)

According to me those near-null visibilities don't belong there. And no, they're not XY/YXs, this is an XX YY plot. And it's not a bug in shadeMS since ragavi shows them too.

This shows up in 2 of the 3 test MSs. One is "clean". Anybody else seeing this?

**Comment by gigjozsa** [comment]
@o-smirnov can this be closed?

**Comment by o-smirnov** [comment]
What did we decide, the data is legit bad and everything is fine? Close it then.
