### ISSUE TITLE
tricolour hanging -- try dask-ms#113

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1046]
Tricolour  is giving me some grief. Sometimes it completes in a short time, sometimes it hangs for hours with no sign of progress (same .MS, same settings).

The more recent example is with current Caracal master, Stimela 1.4.3. I'm running it on a 15GB .MS on my 8-cores, 64GB RAM desktop with the tricolour strategy https://github.com/ska-sa/caracal/blob/master/caracal/data/meerkat_files/calibrator_soft_flagging.yaml .

On one occasion it stopped as:

```
# tricolour - 2020-05-05 17:54:10,740 INFO - Flagging based on quadrature polarized power
# tricolour - 2020-05-05 17:54:11,515 INFO - Only considering scans '1, 2, 135, 12, 145, 22, 155, 32, 167, 41, 43, 177, 53, 63, 73, 81, 84, 94, 104, 114, 125' as per user selection criterion
# tricolour - 2020-05-05 17:54:11,515 INFO - Only considering fields 'J0825-5010, J0408-6545' for flagging per user selection criterion.
# tricolour - 2020-05-05 17:54:11,515 INFO - Adding field 'J0408-6545' scan 1 to compute graph for processing
# tricolour - 2020-05-05 17:54:11,780 INFO - Adding field 'J0825-5010' scan 2 to compute graph for processing
# tricolour - 2020-05-05 17:54:11,814 INFO - Adding field 'J0825-5010' scan 12 to compute graph for processing
# tricolour - 2020-05-05 17:54:11,844 INFO - Adding field 'J0825-5010' scan 22 to compute graph for processing
# tricolour - 2020-05-05 17:54:11,874 INFO - Adding field 'J0825-5010' scan 32 to compute graph for processing
# tricolour - 2020-05-05 17:54:11,903 INFO - Adding field 'J0408-6545' scan 41 to compute graph for processing
# tricolour - 2020-05-05 17:54:11,957 INFO - Adding field 'J0825-5010' scan 43 to compute graph for processing
# tricolour - 2020-05-05 17:54:11,986 INFO - Adding field 'J0825-5010' scan 53 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,016 INFO - Adding field 'J0825-5010' scan 63 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,044 INFO - Adding field 'J0825-5010' scan 73 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,075 INFO - Adding field 'J0408-6545' scan 81 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,128 INFO - Adding field 'J0825-5010' scan 84 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,158 INFO - Adding field 'J0825-5010' scan 94 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,188 INFO - Adding field 'J0825-5010' scan 104 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,217 INFO - Adding field 'J0825-5010' scan 114 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,247 INFO - Adding field 'J0825-5010' scan 125 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,277 INFO - Adding field 'J0825-5010' scan 135 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,306 INFO - Adding field 'J0825-5010' scan 145 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,336 INFO - Adding field 'J0825-5010' scan 155 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,365 INFO - Adding field 'J0825-5010' scan 167 to compute graph for processing
# tricolour - 2020-05-05 17:54:12,395 INFO - Adding field 'J0825-5010' scan 177 to compute graph for processing
```

One hour after printing the last line it was still there and I just had to kill it.

I then started Caracal again changing nothing in the settings and got past the lines as above all the way to a happy ending:

```
# tricolour - 2020-05-05 19:03:00,209 INFO - Adding field 'J0825-5010' scan 177 to compute graph for processing
# 
# [##############################          ] | 76% Completed |  5min  0.1s
# [########################################] | 100% Completed | 10min  0.1s
# /usr/local/lib/python3.6/dist-packages/tricolour/flagging.py:1027: RuntimeWarning: Mean of empty slice
#   avgvis = np.nanmean(vis_scratch[cp, :, :], axis=0)
# tricolour - 2020-05-05 19:13:01,046 INFO - ********************************
# tricolour - 2020-05-05 19:13:01,047 INFO -    BEGINNING OF FLAG SUMMARY
# tricolour - 2020-05-05 19:13:01,047 INFO - ********************************
...
```

So it took 10 min to complete whatever it didn't manage to complete in 1 h at the first attempt.

Pinging @sjperkins @o-smirnov @bennahugo .

**Comment by o-smirnov** [comment]
Hate to tell you this, but I just got it to hang again.

**Comment by o-smirnov** [comment]
I see the image is using dask-ms 0.2.4. Let me roll a new one with 0.2.5 and test again.

**Comment by o-smirnov** [comment]
Maybe this was a false alarm. Looking closely, I notice there's a point in the run where it slows down to virtually no CPU use (<0.1%). But it's still pottering along and finishes eventually. Maybe that's what spooked me into crying for a hanging.

Not sure what the slow stage is, maybe @sjperkins and @bennahugo can make a mental note to chase it up one day.

My hypothesis is that the slow stage, whatever it is, does not scale up with data size. So on a full MeerKAT run, it is not noticeable. With a small test MS, the parallel work finishes super quickly, and the slow stage stands out.

I'll update the cab for dask-ms 0.2.5 in my Stimela branch anyway.

**Comment by sjperkins** [comment]
> Maybe this was a false alarm.

Suspect not, I could reliably reproduce a deadlock with ragavi: https://github.com/ska-sa/dask-ms/pull/113#issuecomment-626642292. 

PR https://github.com/ska-sa/dask-ms/pull/113 is included in dask-ms 0.2.5, so best to upgrade as you mentioned.

> Looking closely, I notice there's a point in the run where it slows down to virtually no CPU use (<0.1%). But it's still pottering along and finishes eventually. Maybe that's what spooked me into crying for a hanging.
> Not sure what the slow stage is, maybe @sjperkins and @bennahugo can make a mental note to chase it up one day.
> 
> My hypothesis is that the slow stage, whatever it is, does not scale up with data size. So on a full MeerKAT run, it is not noticeable. With a small test MS, the parallel work finishes super quickly, and the slow stage stands out.

Is the MS small and public enough to include on a tricolour issue? I'd guess its on 0% CPU because it's loading a scans worth of data into memory before flagging but dask diagnostic profiling would reveal it.

**Comment by KshitijT** [comment]
@o-smirnov , is this no longer an issue with the caracal release? Asking because I am fed up of aoflagger being very trigger happy and taking astronomical timescales to finish and want to switch to tricolour.

**Comment by o-smirnov** [comment]
Try it!

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by o-smirnov** [comment]
You have nothing to lose but your cpu cycles, after all.

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by KshitijT** [comment]
Some very expensive cpu cycles. :/
I speak after wasting 4 days on fruitless flagging with aoflagger.

**Comment by o-smirnov** [comment]
Fruitless flagging sounds horrible.

Try tricolour. I never went back.

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by KshitijT** [comment]
On it, will keep notes here.

**Comment by KshitijT** [comment]
Flags 505 GB in couple of hours - no hanging(s). :)
