### ISSUE TITLE
Model and subtracting the sun

### ISSUE THREAD

**Issue by bennahugo** [caracal-pipeline/caracal#105]
Meeting with @o-smirnov @SpheMakh @KshitijT @ianjarog
Need to treat Solar RFI more carefully than simply flagging it out, since the current flagging approach may be flagging out other large scale structure as well:

- Time variable phase rotation and image the sun to try and model first order morphology for subtraction OR snapshots. Extract model
- apply dE gains on top of model to capture any time variability

OR 

matched filtering approach

OR

BIRO

**Comment by Athanaseus** [comment]
Look into Victoria's solar imaging pipeline.
