### ISSUE TITLE
Excited oranges

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1079]
They are too excited about the release. How can I calm them down?

![joshs_oranges](https://user-images.githubusercontent.com/8706644/81566089-a888b680-939a-11ea-8c83-8b73511147bb.jpg)

**Comment by KshitijT** [comment]
Use DDcal to peel them - that should sort them out.

**Comment by KshitijT** [comment]
For some reason this issue has not received much attention - can't figure out why. @gigjozsa , did my suggestion above work for you?

The alternative is to mention every new post-release issue in this one; that should calm down the oranges pretty well, I think.

**Comment by gigjozsa** [comment]
The oranges were a bit sad about not more people commenting here. But I told them who you actually are, @KshitijT , and now they are pretty proud and happy again.

I also tested your suggestion and indeed it works.
