### ISSUE TITLE
Reinstate Jenkins test

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1082]
For some reasons we lost it...

**Comment by gigjozsa** [comment]
See #1081, no Jenkins test is invoked. Tried to figure out myself how to reinstate, but this requires either knowledge or time. Requesting from @o-smirnov @bennahugo , or  @SpheMakh to reinstate the Jenkins test in branch testest.

**Comment by bennahugo** [comment]
Not sure what you mean by lost it. The machine simply asked for permission to start testing. It is running at present.

**Comment by gigjozsa** [comment]
> Not sure what you mean by lost it. The machine simply asked for permission to start testing. It is running at present.
@bennahugo could you elaborate? I just submitted a PR (basically the current release) to see what happens in github and no Jenkins test started, which is why I raised the issue. 

What do I need to do if this happens?

**Comment by gigjozsa** [comment]
> The machine simply asked for permission to start testing

Where would this show if it happens again? Is it the "could one of the operators verify this patch" ? To which I reply "ok to test" ?

**Comment by bennahugo** [comment]
Either Oleg or myself has to say ok to test. We are admin on the box

**Comment by gigjozsa** [comment]
@bennahugo can this be opened at least to admins on caracal?

**Comment by o-smirnov** [comment]
ok to test
 :)

**Comment by o-smirnov** [comment]
Actually I never understood this Jenkins magic. Where exactly do the permissions for who are "admins" reside? In any case people like @gigjozsa, @SpheMakh and @paoloserra should be on it too.

**Comment by gigjozsa** [comment]
Yes, and before the shift to the new repo, I did have the ability to (re-)start it...

**Comment by gigjozsa** [comment]
Also on caracal we have the develper team with admin rights.

**Comment by gigjozsa** [comment]
Sorry, correction, this is not true, it's only a few people.

**Comment by gigjozsa** [comment]
Anyway, this should be open to people with write access actually.

**Comment by o-smirnov** [comment]
Yeah ok so I reorganized teams a little. We have an admin team and a developers team now. Someone less lazy than me can invite everyone else to the developers team.

Can Jenkins be made to honour these team privileges, or must something there be configured separately @bennahugo?

**Comment by gigjozsa** [comment]
@bennahugo could this perhaps be done?

**Comment by bennahugo** [comment]
Will configure it tomorrow. I need to manually whitelist them only for this
job
