### ISSUE TITLE
Support processing of shared, read-only input .MS files

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1086]
Caracal supports a workflow where the input .MS is treated as read-only. However, that workflow still requires the input .MS to be in the `general: msdir` directory.

That's a pity on shared machines. Multiple users may want to work on the same, large, input .MS with the read-only Caracal workflow, but they are all required to move the input .MS to their own `general: msdir`. That is a waste of disc space.

It would be nice if the input .MS could live in `general: rawdatadir`, which could be a shared, read-only directory, and only .MS files written by Caracal needed to live in `general: msdir`.

Is there any catch there? Can CASA mstransform be executed on a read-only .MS (necessary for. the read-only workflow)?

If we make this change we would also need to continue supporting the current mode, where the input .MS lives in the same directory as `general: msdir`. That may be just as easy as setting `general: rawdatadir = msdir`.

**Comment by IanHeywood** [comment]
Wouldn't a symbolic link work? I do this all the time on IDIA, run mstransform on a symlinked MS which is in an area that I do not have write permissions for.

Multiple users reading from the same MS I cannot vouch for.

**Comment by paoloserra** [comment]
I'm not too concerned about multiple users splitting simultaneously from the same read-only .MS.

Sym-linking might be a solution -- I just would like us to implement something in Caracal rather than asking users to create the symlink before running Caracal.

**Comment by o-smirnov** [comment]
Since msdir is mounted inside the container, a simple symlink to some other filesystem is not going to work directly (or is it?)

Rather just have the path to the read-only "data source" as an explicit parameter? Then ``msdir`` is just our private sandbox for splitting out calibrators and targets.

**Comment by paoloserra** [comment]
> Rather just have the path to the read-only "data source" as an explicit parameter?

We kind of have that already. It's `general: rawdatadir`. Normally that was meant to be the location of data to be converted to .MS. But it could work also as the location of the read-only shared .MS.

**Comment by SpheMakh** [comment]
What to do when user wants to concatenate MSs. The sensible option is to save the concatenated MS in `msdir`

**Comment by SpheMakh** [comment]
This will force a copy of the MSs in the case of virtconcat since the rawdata is readonly.

**Comment by SpheMakh** [comment]
I think it's simpler to have support virtually concatenated MSs but to leave the concatenation to the user.

**Comment by KshitijT** [comment]
I agree.

**Comment by gigjozsa** [comment]
Silly question: would a hard link work?

**Comment by gigjozsa** [comment]
And can you create hard links across different drives?

**Comment by paoloserra** [comment]
Does our old way of (virtually) concatenating make any sense within  the  framework of read-only input .MS files?

I think this is what should  happen.

- the original data live at `rawdatadir`
- when splitting the calibrators, if concat is on, we write a single file with all calibrators in `msdir`
- when splitting the targets, in concat is on, we write a single file per target in `msdir`

What do you  think?

**Comment by gigjozsa** [comment]
Isnt' the problem the containerization and the fact that it requires all directories to stay in the root directroy?

**Comment by gigjozsa** [comment]
Or is this a Stimela feature? Exposing my ignorance. Either way, you'd need to make a call to something exterior to Stimela.

**Comment by SpheMakh** [comment]
@paoloserra, sounds good.

**Comment by o-smirnov** [comment]
> And can you create hard links across different drives?

You can't, sadly.

I agree with @paoloserra. If we go the read-only raw data route, we should stop worrying about virtual concatenation of the inputs. If the user wants to virtually concatenate the original MS before giving it to the pipeline, that's their business. The transform step doesn't really care if the original MS is concatenated or not, right? Just split out a single MS for target and calibrators, and that's that.

In the glorious parallel future, there is a case to be made for **writing** split-and-virtually-concatenated MSs, to support node-level parallelism. But I think that should be completely decoupled and independent from what the raw readonly data was. We can worry about it in the future.

**Comment by SpheMakh** [comment]
@gigjozsa I remember there were issues with having symbolic and hard links when mounting from a shared filesystem.

**Comment by gigjozsa** [comment]
@SpheMakh yes, pretty silly question of mine. Obviously no hard links across file systems. Well, that is a problem.

**Comment by o-smirnov** [comment]
Yeah links and containers are a great way to lose hair, sleep, and what shreds of sanity we have remaining.
