### ISSUE TITLE
aoflagger "auto-read" overrules "indirect-read"

### ISSUE THREAD

**Issue by edeblok** [caracal-pipeline/caracal#1088]
aoflagger is currently run with both  `-indirect-read` and `-autoread-mode` options. The first one re-arranges the data in a temporary disk file and flags from there. The second one chooses between reading everything into memory (needs a lot of memory) or flagging directly from the MS (is slow).  For large MS (>memory) the indirect mode is best (according to aoflagger wiki). 

Running caracal with a large-ish MS (2000 chan) I noticed that aoflagger flooded the memory and crashed. This is probably related to how aoflagger seems to slightly mis-estimate the amount of memory available on my machine. Point is I was never able to force it use indirect-read mode instead, despite the `-indirect-read`. 

Testing shows that with the `-auto-read` switch seems to always have priority and *only* chooses between memory mode and direct mode. `-indirect-read` seems to always be  overruled. The only way I could use indirect mode was by disabling `-auto-read` in the `autoflagger/parameters.json` file.  This allowed flagging of large (>> memory) MS file with indirect-read. 

If confirmed, we should allow for indirect-read to be used without having to edit the json file.

**Comment by KshitijT** [comment]
We can add a parameter in the flagging worker to do correspond with the `auto-read-mode` of stimela.

**Comment by paoloserra** [comment]
I think the most transparent solution would be to add CARACal parameter `flag: flag_rfi: aoflagger: readmode` which can take the values `indirect-read`, `memory-read` or `auto-read` (where the latter lets AOflagger choose between `memory-read` and `direct-read`).

Based on this single CARACal parameter `flag: flag_rfi: aoflagger: readmode` we would set the 3 Stimela boolean parameters `indirect-read`, `memory-read` and `auto-read-mode` in the `flag` worker.
