### ISSUE TITLE
flagging steps missing in target flagging in workflow_new

### ISSUE THREAD

**Issue by edeblok** [caracal-pipeline/caracal#1089]
`workflow_new.yml` currently only contains the `flag_rfi` step for the target in `flag__2`. This means that other flagging steps that are used for the calibrators in `flag` (such as `flag_spw`, `flag_mask`, etc) may be inadvertently skipped by the user. For consistency they should be added to `flag__2` so target gets same flagging treatment as calibrators.

**Comment by svw26** [comment]
I'd agree about ```flag_mask``` being added for ```flag__2```. For ```flag_spw``` I'm not sure... Is there redundancy between this (with ```chans: '*:856~880MHz , *:1658~1800MHz, *:1419.8~1421.3MHz'```) and the static mask being applied for MeerKAT data? It depends on what science you want to do, so it might be good to inspect the targets, with minimal flagging, before applying any more. 

As for other flagging steps in ```flag``` in ```workflow_new.yml```:
```flag_autocorr``` is set to 'true', and is missing from ```flag__2```,
```flag_antennas``` and ```flag_scan``` are both set to 'false'.  x
