### ISSUE TITLE
new workflow has RFinder run by default for target

### ISSUE THREAD

**Issue by edeblok** [caracal-pipeline/caracal#1090]
in `workflow_new.yml` the `flag__2` step has `inspect: enable: true`. This means that RFinder is always run for the target. This takes a looong time (longer than aoflagger). For the calibrator flagging this is defined as false, so probably should be false here as well (saves a lot of time).

**Comment by KshitijT** [comment]
The defaults are a matter for general discussion to tagging the issue as such. The user can always switch off RFinder, but note that for really big data, if you want to check out the state of RFI , tools like plotms and rfigui are not going to do the trick.

**Comment by paoloserra** [comment]
I think I agree with @edeblok . Let's leave the rfinder line in the config, but disabled, so a user sees there's such an option but does not necessarily get stuck for a long time if running on a large file.
