### ISSUE TITLE
"inspect" schema has some plots that are always produced 

### ISSUE THREAD

**Issue by edeblok** [caracal-pipeline/caracal#1091]
In the `workflow_new.yml` file, the "inspect" part defines a number of plots. In addition to these, the schema also has `amp_chan` and `phase_chan` with default `enable: True`, so that these are always made, despite not being in the yml file (also the `avgtime` there is only 10s instead of the 60s from the yml file). These take a while to produce.

**Comment by o-smirnov** [comment]
I propose to copy over the inspect sections from ``carateConfig.yml``. There quite a few shadems plots in there which I find very nice (as well as the two people who bothered to vote on @svw26's poll! :laughing:), and fast, and ought to be complementary to ragavi's per-scan plots.

**Comment by svw26** [comment]
Yes, I noticed 😛But where are your votes, @o-smirnov ? You don't get points for just filling in your name! x

**Comment by o-smirnov** [comment]
I vote for everything, clearly! The more, the merrier! And they really don't take _that_ long (well not the new ones anyway).

But it always becomes a philosophical conversation about defaults. I think the sample config file should have all reasonable plots explicitly listed and enabled -- let the user go in and comment them out if they want to save some time. After all, if the user doesn't see all the riches available to them up front in the sample configs, where are they going to see them. What do you reckon @edeblok?

On the other hand, the fact that the schema sneakily enables plots which are not listed in the config at all, IMHO, should be treated as a bug.
