### ISSUE TITLE
add 'xcal' when transform.fields == 'calibrators'

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1095]
This currently splits off 'fcal','bpcal','gcal'. Add 'xcal' to the list.

**Comment by paoloserra** [comment]
but we've done away with polcal for now -- what are you going to do with it?

ok, maybe none of my business! :)

**Comment by KshitijT** [comment]
> This currently splits off 'fcal','bpcal','gcal'. Add 'xcal' to the list.

Only if xcal is different from fcal/bpcal/gcal?

**Comment by svw26** [comment]
The 'calfields' setting in flag_schema.yml suggests that it can be treated as a separate field... x

**Comment by o-smirnov** [comment]
> but we've done away with polcal for now -- what are you going to do with it?

I dunno, @SpheMakh put me up to it lol! But I like consistency, and I'd rather fix it than forget about it and have it bite me later. (Also, now that we've done away with polcal, it's high time to bring it back, but that's a separate discussion...)

> The 'calfields' setting in flag_schema.yml suggests that it can be treated as a separate field... x

...which by the way is mistakenly referred to as "calibrator_fields" in the "fields" docstring.

**Comment by paoloserra** [comment]
There's a fair bit that can be made more consistent there.

Another one is that, unless I'm mistaken, we make the implicit assumption primary = bpcal = fcal. so why having separate bpcal and fcal throughout the pipeline? It might be because of an earlier, more general approach, but we may want to change that now.

**Comment by PeterKamphuis** [comment]
I greatly appreciate the option to use the secondary as an additional bpcal though. Is that no longer possible in the newest cross_cal?

**Comment by o-smirnov** [comment]
Hmmm, maybe @gigjozsa can start a "Consistency aspirations" project and start collecting such issues and remarks there. We need a bit of an organizing hand to keep track.

**Comment by paoloserra** [comment]
> I greatly appreciate the option to use the secondary as an additional bpcal though. Is that no longer possible in the newest cross_cal?

It should still be possible, see https://caracal.readthedocs.io/en/latest/manual/workers/crosscal/index.html#secondary

**Comment by paoloserra** [comment]
But @PeterKamphuis's comment is yet another good reason to do away with the bpcal etc terms. What matter is what is the primary. and what. the secondary. Then how you use them is set by the settings of the crosscal worker. If i had a twisted mind I could solve for K only on the primary, and BG on the secondary -- so who's bpcal then?

**Comment by svw26** [comment]
> > The 'calfields' setting in flag_schema.yml suggests that it can be treated as a separate field... x
> 
> ...which by the way is mistakenly referred to as "calibrator_fields" in the "fields" docstring.

It was "calibrator_fields" when I looked at it :)  I guess @SpheMakh and @paoloserra changed the parameter name to "calfields" then forget to search the schema file for references of the old name. Noted for a future fix. x

**Comment by o-smirnov** [comment]
> If i had a twisted mind

How is that even a hypothetical, Mr DD-Amplitude?

**Comment by PeterKamphuis** [comment]
> But @PeterKamphuis's comment is yet another good reason to do away with the bpcal etc terms. What matter is what is the primary. and what. the secondary. 

So then you only implicitly assume/demand the primary is the flux calibrator. I guess actually calling them primary and secondary instead of bpcal, facal, gcal makes it  easier to understand the crosscal worker as well.

**Comment by paoloserra** [comment]
> > If i had a twisted mind
> 
> How is that even a hypothetical, Mr DD-Amplitude?

Believe me, that's a trick I'd be very proud of if only I could claim it for myself! Unfortunately, it's somebody else's trick.

**Comment by gigjozsa** [comment]
You mean TAO?

**Comment by gigjozsa** [comment]
Reading the above I indeed start to shiver. You know, we committed ourselves to some downwards compatibility...

**Comment by gigjozsa** [comment]
... although it's not explicitly written down anywhere. But it would look odd if v1.0.0 would immediately followed by v2.0.0

**Comment by PeterKamphuis** [comment]
> ... although it's not explicitly written down anywhere. But it would look odd if v1.0.0 would immediately followed by v2.0.0

Well you always have bug fixes and such when moving out of Beta Testing.

**Comment by o-smirnov** [comment]
> Reading the above I indeed start to shiver. You know, we committed ourselves to some downwards compatibility...

This is where alternative worker names come in. Freeze the crosscal worker as it is and only do bug fixes on it. Create a new worker for new and improved cross-calibration, with its own schema. Maybe then we can finally use an exciting name like "mendel". :P

**Comment by paoloserra** [comment]
geee, and I was the one with a twisted mind -- two workers doing the same thing with different parameter names!

**Comment by o-smirnov** [comment]
If only I could claim it for myself! Doesn't even AIPS have tasks with overlapping functionality? CASA has ``clean`` and ``tclean``. Unix has software packages with, gasp, different names that do the same thing. Why not workers?

**Comment by o-smirnov** [comment]
It's just giving the user ropes in different colours!

**Comment by gigjozsa** [comment]
@all Please keep our mission in sight!

**Comment by gigjozsa** [comment]
Why doesn't anyone ask what the mission is?

**Comment by svw26** [comment]
I was about to, then though I might regret it ;) x

**Comment by svw26** [comment]
Sorry, @gigjozsa  -- please remind us what The Mission is :) x

**Comment by gigjozsa** [comment]
We don't have one yet!

**Comment by gigjozsa** [comment]
But I suggest to find one in a democratic process, like the name.

**Comment by PeterKamphuis** [comment]
I thought the mission was to make CARACal a true python package by having lots of slightly differently named tasks that do the same thing but cause horrible crashes when you mix them in the wrong order? So for the new `crosscal` task I propose `set_crosscals`.

**Comment by o-smirnov** [comment]
``set_crosseyes``?
