### ISSUE TITLE
 WARNING: The shadems section is enabled, but doesn't specify any plot_by_field or plot_by_corr

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1106]
This is what happens with the default schema.

Either ignore the warning, or change the default to enable=False.

(Not that I'm a big fan of redundant enable keys, when plot_by_field=plot_by_corr=[] has the same meaning is enable=False, so maybe I should just take out the warning.)

**Comment by KshitijT** [comment]
Or change all the default configs?

**Comment by o-smirnov** [comment]
Well in any case, an inspect section that doesn't mention shadems should not result in a warning. Which it currently does. Or change the default to a small, reasonable set of plots. Or something.

**Comment by KshitijT** [comment]
>  a small, reasonable set of plots. 

Which plots would those be? 

A certain spreadsheet comes to mind. :)
