### ISSUE TITLE
meqtrees+visonly bug

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1107]
When `selfcal: calibrate_with: meqtrees` and `selfcal: cal_model_mode: vis_only`, the pipeline creates an empty sky model in the `input` directory, see

https://github.com/caracal-pipeline/caracal/blob/1afa8b0d4407ba9aacbdd88921f9e21b058c7350/caracal/workers/selfcal_worker.py#L1054-L1062

but then looks for it in `output/continuum/image_N/`, see

https://github.com/caracal-pipeline/caracal/blob/1afa8b0d4407ba9aacbdd88921f9e21b058c7350/caracal/workers/selfcal_worker.py#L1161-L1167

and https://github.com/caracal-pipeline/caracal/blob/1afa8b0d4407ba9aacbdd88921f9e21b058c7350/caracal/workers/selfcal_worker.py#L1197

I'm checking whether writing the empty sky model directly in the `output/continuum/image_N/` directory solves this.

**Comment by KshitijT** [comment]
Sheesh, sorry, this is my fault. Writing the sky model in the output directory should solve it. The change was made in an attempt to make meqtrees conform to the output directory struture, I completely forgot about the empty sky model.

**Comment by paoloserra** [comment]
@KshitijT are you ok with me replacing the line https://github.com/caracal-pipeline/caracal/blob/1afa8b0d4407ba9aacbdd88921f9e21b058c7350/caracal/workers/selfcal_worker.py#L1162

with `model_cal = model_cal.split(":output")[0]` ?

I'm finding that, for the case of this issue, the current line transforms `model_cal` from `<something>.txt` to `<something>.tx` -- which BTW I don't understand.

The proposed change will work both with and without a trailing `":output"` so I'm assuming it covers all cases.

**Comment by KshitijT** [comment]
Yes, that should work, though I also don't get why it removes the "t". Weird.

**Comment by paoloserra** [comment]
I swear, try it in Python! :). Even when there's a trailing ":output" ...?

```
>>> a='meqtrees_1-nullmodel.txt:output'
>>> a.strip(":output")
'meqtrees_1-nullmodel.tx'
```

**Comment by o-smirnov** [comment]
Because strip treats its argument as a *set* to be stripped, not a sequence. So it strips the longest consecutive sequence of characters in the given set. Hence the extra ``t``.

**Comment by o-smirnov** [comment]
I recommend searching the code for other instances of unintended stripping...

**Comment by paoloserra** [comment]
that was the only one in selfcal
