### ISSUE TITLE
Possible bug in Cubical -- better selfcalibrate XX,YY data with MeqTrees

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1109]
I'm having troubles reproducing some nice continuum images made a few weeks ago with CARACal. A few controlled experiments show that, of all the moving parts (imaging settings, clean masks, calibration software and settings), the one giving troubles is Cubical. The calibration does not seem to be able to converge -- while it used to.

This is for XX,YY-only data. Not sure whether the problem exists for full-pol data, too.

A few of us are looking into it. Until we understand what the problem is I recommend adopting MeqTrees as your calibrator in the selfcal worker. Do this by setting:

`selfcal: calibrate_with: meqtrees`

**Comment by bennahugo** [comment]
@paoloserra I've been using cubical in my pipeline to do phase-only calibration quite successfully. I don't think it is cubical (otherwise my maps would not have improved. most of the chi^2 values look quite sensible to me

**Comment by KshitijT** [comment]
This is probably a Caracal implementation issue, not a cubical bug per we.

**Comment by o-smirnov** [comment]
@bennahugo it works just fine for me too, but have you been using dual-corr data at all? From what @paoloserra showed me, there seemed a clear regression in a dual-corr scenario. I did have a big PR go in that fiddled with some of this behaviour, and dual-corr mode seems undertested to me, so... let's just say I'm just going to have a deep look at this tomorrow.

**Comment by o-smirnov** [comment]
So for the time being, the public service announcement is, no need to panic, but if you get weird selfcal results (especially with dual-corr data), try ``selfcal: calibrate_with: meqtrees``, and please tell us here on this issue if that works any better.

**Comment by bennahugo** [comment]
No you know I love meself some polarimetry! Never do duel corr any more

**Comment by o-smirnov** [comment]
Well, if there is a problem, this may be exactly why you have been dodging it...

**Comment by o-smirnov** [comment]
OK, I can confirm that the problem is there, and that it came in at 1.5.0 (with my big fat PR, no doubt). If @SpheMakh rolls us a cab with 1.4.7, Caracal can avoid this problem until I fix it properly.

**Comment by o-smirnov** [comment]
OK, this was a fun dataset/bug. CubiCal not Caracal, so I suggest interested parties read the discussion here: https://github.com/ratt-ru/CubiCal/issues/379. @paoloserra and @bennahugo in particular.

**Comment by o-smirnov** [comment]
BTW @paoloserra, that source of yours is pretty suspicious:

| | |
|-|-|
|![image](https://user-images.githubusercontent.com/6470079/82157616-cbc3d200-9882-11ea-8fcc-71bd3194d0e4.png)|![image](https://user-images.githubusercontent.com/6470079/82157562-843d4600-9882-11ea-8cee-1ff30a8a9dd0.png)|

**Comment by paoloserra** [comment]
Sssssshhhh! yYou weren't supposed to tell anybody! Now we'll have to take care of you...

**Comment by KshitijT** [comment]
The Tie-fighter seems to be be in a spiral?

**Comment by o-smirnov** [comment]
Seriously though, I stress the workaround:

* try complex-2x2 and update-type phase-diag, with thresholds of 10 and 12. Or use 1.4.7.

**Comment by paoloserra** [comment]
> Seriously though, I stress the workaround:
> 
>     * try complex-2x2 and update-type phase-diag, with thresholds of 10 and 12. Or use 1.4.7.

But why, you' ve got a Cibical PR that fixes it (thanks!), we'll get a new Stimela release with that fix included, and we'll live happily ever after -- why should we bother with workarounds?

**Comment by o-smirnov** [comment]
True. Workarounds are for cowards.

**Comment by paoloserra** [comment]
I confirm that this is fixed with Cubical 1.5.3 in Stimela 1.5.4.
