### ISSUE TITLE
AOflagger does not distinguish XX, YY and RR, LL but caracal does.

### ISSUE THREAD

**Issue by PeterKamphuis** [caracal-pipeline/caracal#1113]
Obtained this message when using my own strategy.

```
2020-05-18 13:09:43 CARACal ERROR: The selected flagging strategy input/GMRT_GSB_First_Pass.rfis will attempt to flag on ['xx', 'yy'] but this is not compatible with the ['RR', 'LL'] correlations available in GMRT_Original_10Nov_cal.ms. To proceed you can edit the flagging strategy or, if you know what you are doing, disable aoflagger: ensure_valid. [ValueError]
```

But that is clearly not so as I have developed the strategy for RR, LL

**Comment by KshitijT** [comment]
Erm, I don't know who put that message there, but I agree with you, @PeterKamphuis . Could you please take out that line?

**Comment by paoloserra** [comment]
Thanks for reporting @PeterKamphuis , let me take care of that. In case you're stuck, you can disable the AOflagger  strategy sanity check  with `ensure_valid: false`.

I'll ask for your help and review when fixing this.

**Comment by paoloserra** [comment]
So can you just confirm that AOflagger has no `rr`,`ll` options, and for the  GMRT you need to have 'xx' and 'yy' in your strategy?

**Comment by PeterKamphuis** [comment]
@paoloserra  yes, aoflagger does not distinguish, here is a screenshot from the strategy editor.

![Screenshot from 2020-05-18 15-10-22](https://user-images.githubusercontent.com/11264005/82216908-ea28dc80-9919-11ea-864e-e0bdb9a7421e.png)

I think the fix should be:
```
if ('stokes-u' in flag_corr and (('XY' not in ms_corr and 'RL' not in ms_corr) or ('YX' not in ms_corr and 'LR' not in ms_corr))) or\
                             ('stokes-v' in flag_corr and (('XY' not in ms_corr and 'RR' not in ms_corr) or ('YX' not in ms_corr and 'LL' not in ms_corr))) or\
                             ('stokes-i' in flag_corr and (('XX' not in ms_corr and 'RR' not in ms_corr) or ('YY' not in ms_corr and 'LL' not in ms_corr))) or\
                             (('stokes-q' in flag_corr) and (('XX' not in ms_corr and 'RL' not in ms_corr) or ('YY' not in ms_corr and 'LR' not in ms_corr))) or\
                             ('xy' in flag_corr and ('XY' not in ms_corr and 'RL' not in ms_corr )) or\
                             ('yx' in flag_corr and ('YX' not in ms_corr and 'LR' not in ms_corr)) or\
                             ('xx' in flag_corr and ('XX' not in ms_corr and 'RR' not in ms_corr)) or\
                             ('yy' in flag_corr and ('YY' not in ms_corr and 'LL' not in ms_corr)):
```

Starting from line https://github.com/caracal-pipeline/caracal/blob/bd1a1bd7c4fa460fbfe564b5701b2c16cd812892/caracal/workers/flag_worker.py#L400

If you agree I can push the commit though as @SpheMakh  doesn't like to read comments in the code apparently so I need to fix line https://github.com/caracal-pipeline/caracal/blob/bd1a1bd7c4fa460fbfe564b5701b2c16cd812892/caracal/workers/obsconf_worker.py#L123 as well.

**Comment by paoloserra** [comment]
great that you've implemented a fix already, please go ahead!
