### ISSUE TITLE
Why is the default correlation in inspect XX, YY when there is auto?

### ISSUE THREAD

**Issue by PeterKamphuis** [caracal-pipeline/caracal#1120]
This baffles me somewhat is there a good reason for not having the default correlation `auto` when that should work for  all datsets? Or is it then also doing all the cross terms?

**Comment by o-smirnov** [comment]
The intention indeed was to omit the cross-terms by default. The rest is just bigoted linearism.

Would it be useful to introduce settings of ``parallel`` and ``all``? (I would prefer ``all`` to ``auto``, as the latter sounds quite ambiguous, but of course we can leave it as an alias for ``all`` for backwards compatibility). Then the default could be ``parallel``. Or do we call them ``diag``?
