### ISSUE TITLE
Provide centralized repo of Singularity images, including on ilifu

### ISSUE THREAD

**Issue by KshitijT** [caracal-pipeline/caracal#1125]
Pulling the singularity images on ILIFU takes long time currently. For this reason (and also to reduce the amount of time taken by a CARACal job), it would be best to have all the images needed by CARACal (stimela + others, see #1104 ) in an area accessible by all ILIFU users of CARACal. 

We have tested this out with the current stimela release images and it seems to work fine. The images are currently stored at `/idia/software/containers/STIMELA_IMAGES` . Any CARACal user can copy over these images in their own area, e.g.  '/scratch/user/username/CARACAL_IMAGES' and invoke the CARACal run as :
`caracal -c config-file-name.yml -ct singularity -sid /scratch/user/username/CARACAL_IMAGES` and that should avoid the live pull of singularity images.

Since we need to update these images once in a while, the best solution might be to have an area in ILIFU to which the people responsible for updating images have write access and  others have read access. @Jordatious , could you please help?

**Comment by smasoka** [comment]
This is a good proposal to save bandwidth. CHPC is forced to work this way because compute nodes don't have internet access. 

To save storage space, users may choose not to copy files into their `scratch` workspace. I think read access is sufficient on the shared directory.

**Comment by Jordatious** [comment]
This is being follow up via email, but the plan is to have the singularity images in `/software/astro/caracal/` or similar, and that the CARACal developers with ilifu accounts will have write access to maintain the software and containers there. I will set this up once I have the list of users, and then move `/idia/software/containers/STIMELA_IMAGES` over to here as a starting point. I've also suggested to set the singularity cache and tmp directories to be at this path.

Thank you @smasoka, I agree it would be good if users didn't copy the singularity images to their own workspace.

**Comment by IanHeywood** [comment]
Hijacking this just to check whether these containers are up for grabs generally?

Myself and others have got a similar issue, namely lots of duplicate containers in various home areas. Grabbing these from a central location would save some hassle and disk space.

Cheers.

**Comment by IanHeywood** [comment]
@smasoka, is there a similar location on a shared area at CHPC? I have to scp containers in there via the `scp` node.

Cheers.

**Comment by KshitijT** [comment]
> Hijacking this just to check whether these containers are up for grabs generally?
> 
> Myself and others have got a similar issue, namely lots of duplicate containers in various home areas. Grabbing these from a central location would save some hassle and disk space.
> 
> Cheers.

I don't see why they can't be up for grabs. :)
Please note that it doesn't have the radiopadre image. I'll try and put it there sometime soon.

**Comment by KshitijT** [comment]
P.S. I think anyone on ILIFU can access that folder; please let me know if that's not the case.

**Comment by IanHeywood** [comment]
Thanks @KshitijT.

**Comment by o-smirnov** [comment]
I think we should build images ourselves after each release, and host them on the elwood ftp server.

ILIFU can then download them from elwood with wget. Much faster to wget 20G than to build 20G of images.

**Comment by smasoka** [comment]
> @smasoka, is there a similar location on a shared area at CHPC? I have to scp containers in there via the `scp` node.
> 
> Cheers.

@IanHeywood at CHPC the directory is `/apps/chpc/astro/stimela_images/`. The dir name might have to change as other images are not provided via `stimela`

**Comment by IanHeywood** [comment]
Thanks @smasoka!

**Comment by KshitijT** [comment]
The updated location of the singularity  images for CARACal on ILIFU:

```
 /software/astro/caracal/STIMELA_IMAGES_1.6.1
```


We request you to kindly switch to using these images for your CARACal reductions, rather than the older ones.  Note that the above folder also has the radiopadre images in it.

**Comment by Jordatious** [comment]
Thanks @KshitijT. To expand a little, we've set up a directory at `/software/astro/caracal` for the CARACal containers, and moved the previous directory `/idia/software/containers/STIMELA_IMAGES` to here. We've created a group `idia-caracal-dev` that includes a number of CARACal developers who are ilifu users, who have write access to this directory and can update and maintain the containers as needed. I think it would also be useful to put the CARACal software itself there (not just the containers). And as I said before, I suggest you also set any singularity cache and temp directories to also be in this directory - e.g.:
```
export SINGULARITY_CACHEDIR=/software/astro/caracal/.singularity_cache
export SINGULARITY_TMPDIR=/software/astro/caracal/.singularity_tmp
```
You may or may not need to do the same for `SINGULARITY_TMPDIR` and `SINGULARITY_LOCALCACHEDIR`.

Please start pointing ilifu users of CARACal to this location so they can remove their own local copies.

**Comment by paoloserra** [comment]
Just a heads up that @molnard89 has added the stimela 1.6.5 images at /software/astro/caracal/. From first tests they seem to be working fine. Those images are required for running current CARACal master.

**Comment by IanHeywood** [comment]
I just came here to ask if anyone would be willing to upgrade the images in `/idia/software/containers/STIMELA_IMAGES/`, only to discover the `/software/astro/caracal/` location now exists.

Might be worth removing the old location to avoid confusion, and also on that note, is there any reason to have multiple versions of various images? e.g.

```
$ ls -1 /software/astro/caracal/STIMELA_IMAGES_1.6.5/*wsclean*
/software/astro/caracal/STIMELA_IMAGES_1.6.5/stimela_wsclean_1.2.3.sif
/software/astro/caracal/STIMELA_IMAGES_1.6.5/stimela_wsclean_1.6.0-1.sif
/software/astro/caracal/STIMELA_IMAGES_1.6.5/stimela_wsclean_1.6.3.sif
```

Cheers.

**Comment by o-smirnov** [comment]
The multiple versions are on purpose, so that one can select e.g. a non-default wsclean version in the pipeline.

**Comment by KshitijT** [comment]
> Might be worth removing the old location to avoid confusion.

Let me give it a shot.

> Might be worth removing the old location to avoid confusion, and also on that note, is there any reason to have multiple versions of various images? e.g.

Backwards compatibility for certain things? There was a debate about this (using specific versions of wsclean for certain tasks, I forget the exact details). E.g. for CASA, some versions are not good for mstransform/split despite being newer.

**Comment by o-smirnov** [comment]
Hmmm, at this stage even getting a .gaul is proving elusive... BDSM is hanging, seemingly forever, on fitting islands. Any idea how to tell it not to fit so hard?

**Comment by KshitijT** [comment]
> Hmmm, at this stage even getting a .gaul is proving elusive... BDSM is hanging, seemingly forever, on fitting islands. Any idea how to tell it not to fit so hard?

Is this on ILIFU? For fluffy sources pybdsf generally takes loooong time to fit the last 'n' gaussians. I set it fitting and check it about 3 coffees later.

**Comment by Jordatious** [comment]
You can use multiple CPUs to speed up PyBDSF, possibly with the need to `export OMP_NUM_THREADS=32`, for example.

**Comment by Jordatious** [comment]
Wait where did you even get that quotation from? Was it removed? Accidentally in the wrong ticket?

**Comment by KshitijT** [comment]
Which quotation?

**Comment by o-smirnov** [comment]
Ah, I was missing the 3 coffees option, let me try it with that...

> Wait where did you even get that quotation from? Was it removed? Accidentally in the wrong ticket?

Life is an illusion, bug reports doubly so!

(Wrong repository syndrome: https://github.com/Athanaseus/aimfast/issues/43)

**Comment by KshitijT** [comment]
Ah, maybe Oleg removed the comment. Here's the proof that I haven't been day-drinking (at least noticeably):
 
![image](https://user-images.githubusercontent.com/9251962/93100419-6b666500-f6a9-11ea-80eb-a0d6b12bbec3.png)

**Comment by Jordatious** [comment]
Day-drinking 3 coffees, not alcohol?

**Comment by o-smirnov** [comment]
Make it an Irish coffee...

Geez, and I only deleted the comment 40 seconds after posting it... talk about eagle eyes!

**Comment by KshitijT** [comment]
> Day-drinking 3 coffees, not alcohol?

Ah, thanks for the reminder, gotta go get a fresh cup.

**Comment by o-smirnov** [comment]
@KshitijT, as an EU citizen, I hereby invoke my right-to-forget clause!

**Comment by KshitijT** [comment]
> @KshitijT, as an EU citizen, I hereby invoke my right-to-be-forgotten clause!

Sadly, I have an excellent memory. :P
But will try for an amarula.

**Comment by o-smirnov** [comment]
> You can use multiple CPUs to speed up PyBDSF, possibly with the need to export OMP_NUM_THREADS=32, for example.

Ahh good tip @Jordatious, I'm not sure the containerized version sets this. I'm glad I brought up this inappropriate topic!

**Comment by o-smirnov** [comment]
OK 3 coffees and a hike later I'm still waiting... shall I throw dinner and a nap into the mix?

**Comment by IanHeywood** [comment]
Throw a Ctrl+C into the mix.

**Comment by o-smirnov** [comment]
18 hours later:
```
# Fitting islands with Gaussians .......... : [/] 427/464
```
I don't have enough coffee @KshitijT!

On the bright side, two other runs (on images of the same field from different epochs) ended after 11h and 18h, respectively. So there is light at the end of the tunnel. Just a very red-shifted light.

Seriously though, hasn't anyone ever used PyBDSM with a large source in the field?

**Comment by paoloserra** [comment]
not me

**Comment by KshitijT** [comment]
> Seriously though, hasn't anyone ever used PyBDSM with a large source in the field?

I have, generally doesn't end well. Can I take a look at the settings?

**Comment by o-smirnov** [comment]
Let us cease and desist the hijacking of this issue, and move here: https://github.com/o-smirnov/meerkat-open-time/issues/18
