### ISSUE TITLE
How to disable final report and debug?

### ISSUE THREAD

**Issue by HaoChen-ast** [caracal-pipeline/caracal#1129]
I run the pipeline on ilifu with 
`caracal -c 1a9_hao_20200518.yml --container-tech singularity -sid /idia/projects/vela/CARACal_all/CARACal-18May2020/stimela-singularity-18May2020`

It takes 13 hours to finish the data reduction, but it spends 10 hours for the final report til now.
The only update of log file is:

> 2020-05-21 10:18:34 CARACal DEBUG: poll(): ready to read: []
> 2020-05-21 10:18:39 CARACal DEBUG: poll(): ready to read: []
> 2020-05-21 10:18:44 CARACal DEBUG: poll(): ready to read: []

So how can I stop it? Just cancel the job on the cluster (similar as Ctrl+C)?
I do not want to generate the final report and debug, but want to keep the inspect worker report.
Which parameter should I use? All the `-report -debug -nr`? Or just use `-report`?
Could I just run as:
`caracal -c 1a9_hao_20200518.yml --container-tech singularity -sid /idia/projects/vela/CARACal_all/CARACal-18May2020/stimela-singularity-18May2020 -report -debug -nr`
```
-report               (re)generates a final HTML report, if configured, then exits
-debug                enable debugging mode
-nr, --no-reports     disable generation of HTML reports throughout the pipeline
```

**Comment by o-smirnov** [comment]
There's process called ``run-radiopadre``, kill it and the pipeline should exit. Anyway, this is the very last step, so your run is complete.

To disable, just use ``-nr`` next time. This has nothing to do with the inspect worker.

Could you please send me the files in your ``~/.radiopadre/logs/``, perhaps as a tarball? I would like to understand why it's hanging.

**Comment by HaoChen-ast** [comment]
Thanks!

All the `~/.radiopadre/logs/` are uploaded here:
https://github.com/HaoChen-ast/logs/tree/master/log

**Comment by paoloserra** [comment]
> To disable, just use `-nr` next time.

So this cannot be disabled at the config file level? I thought that was what `general: final_report: false` would do.

If this

**Comment by o-smirnov** [comment]
That will disable it too.

I'm tempted to make disabled the default for 1.0.1, until I understand why it hangs like this on ILIFU...

**Comment by paoloserra** [comment]
yeah, might be a good idea if the hanging is not understood by the time 1.0.1 is due.

**Comment by KshitijT** [comment]
@HaoChen-ast , could you please confirm that you have the radiopadre singularity image downloaded? Asking because the STIMELA_IMAGES folder only has Stimela images; not the radiopadre one.

**Comment by HaoChen-ast** [comment]
@KshitijT Where should the radiopaque singularity image be?
No radiopadre singularity image in the STIMELA_IMAGES folder.

**Comment by o-smirnov** [comment]
It's in ``~/.radiopadre`` right now. We haven't got the feature to keep it in the Stimela folder yet (I only added that last night lol!)

**Comment by KshitijT** [comment]
> It's in ~/.radiopadre right now. 
On ILIFU? I can update the STIMELA_IMAGES folder then.

**Comment by o-smirnov** [comment]
Not yet, let me roll one with the latest release.
