### ISSUE TITLE
crosscal: fluxscale field - Index out of range

### ISSUE THREAD

**Issue by mpatir** [caracal-pipeline/caracal#1130]
@SpheMakh @molnard89 I am reducing VLA data: standard format with a primary and secondary calibrator.

I ran caracal in the "standard way" using the minimal config in default settings: 

crosscal:
  enable: true
  label_in: cal
  apply_cal:
    applyto:
      - gcal
      - bpcal
  report: true

I get an error reported below which I think has something to do indices of the calibrators. Is there a way to resolve this?

20-05-20 17:54:45 CARACal ERROR:   File "/home/ramatsoku/Softwares/caracal_venv/lib/python3.5/site-packages/caracal/workers/crosscal_worker.py", line 488, in worker
2020-05-20 17:54:45 CARACal ERROR:     fluxscale_field = pipeline.fcal[i][0]
2020-05-20 17:54:45 CARACal ERROR: IndexError: list index out of range
2020-05-20 17:54:45 CARACal INFO: exiting with error code 1

**Comment by molnard89** [comment]
Can you print pipeline.fcal[i]?

**Comment by KshitijT** [comment]
It might be that the correct scan intents are missing?

**Comment by mpatir** [comment]
@KshitijT @molnard89 

I do not think that scan intents are missing -- these data were reduced okay with "meerkathi" last year. 

I will check this though and see what happens when I print pipeline.fcal[i]

**Comment by mpatir** [comment]
caracal does not always automatically find field IDs (e.g., fcal, target, gcal, etc). In some cases, one has to specify the fields in the observation_config. 

Resolved

**Comment by molnard89** [comment]
I wouldn't close this, it's an issue if the pipeline struggles to find fields automatically based on stored intents. Or maybe open a new one dedicated to this more general problem?

**Comment by KshitijT** [comment]
I agree - I missed exactly how the auto field finding was missed if the intents were present. I don't know if this is a general problem, though.

**Comment by SpheMakh** [comment]
@mpatir could you please post the obsinfo.txt file from listobs

**Comment by SpheMakh** [comment]
This is either a bug, or the INTENTS are not "correctly" labelled in the MS. I put correctly in quotes because different observatories may use different labels, so we just need to keep updating the lists as needed

These are the assumptions made about how the INTENTS are labelled

https://github.com/caracal-pipeline/caracal/blob/867494fe5acf9a5601d7d4d2fc3d2af7c4e249dd/caracal/dispatch_crew/utils.py#L39-L45

**Comment by mpatir** [comment]
> @mpatir could you please post the obsinfo.txt file from listobs

Perhaps hash sign in the labels of the vla data is the problem? 

     ObservationID = 0         ArrayID = 0
  Date        Timerange (UTC)          Scan  FldId FieldName             nRows     SpwIds   Average Interval(s)    ScanIntent
  13-Jun-2017/01:08:24.0 - 01:13:20.0     1      0 J1257-3155               12987  [0]  [8] [SYSTEM_CONFIGURATION#UNSPECIFIED]
              01:13:28.0 - 01:18:16.0     2      0 J1257-3155               12636  [0]  [8] [CALIBRATE_AMPLI#UNSPECIFIED,CALIBRATE_PHASE#UNSPECIFIED]
              01:42:16.0 - 01:47:12.0     6      0 J1257-3155               12987  [0]  [8] [CALIBRATE_AMPLI#UNSPECIFIED,CALIBRATE_PHASE#UNSPECIFIED]
              02:11:12.0 - 02:16:08.0    10      0 J1257-3155               12987  [0]  [8] [CALIBRATE_AMPLI#UNSPECIFIED,CALIBRATE_PHASE#UNSPECIFIED]
              02:40:08.0 - 02:45:04.0    14      0 J1257-3155               12987  [0]  [8] [CALIBRATE_AMPLI#UNSPECIFIED,CALIBRATE_PHASE#UNSPECIFIED]
              03:09:04.0 - 03:14:00.0    18      0 J1257-3155               12987  [0]  [8] [CALIBRATE_AMPLI#UNSPECIFIED,CALIBRATE_PHASE#UNSPECIFIED]
              03:14:08.0 - 03:23:52.0    19      1 3C286                    25623  [0]  [8] [CALIBRATE_BANDPASS#UNSPECIFIED,CALIBRATE_FLUX#UNSPECIFIED]
              03:40:00.0 - 03:44:48.0    22      0 J1257-3155               12636  [0]  [8] [CALIBRATE_AMPLI#UNSPECIFIED,CALIBRATE_PHASE#UNSPECIFIED]
           (nRows = Total number of rows per scan) 
Fields: 2
  ID   Code Name                RA               Decl           Epoch   SrcId      nRows
  0    NONE J1257-3155          12:57:59.060804 -31.55.16.85186 J2000   0          90207
  1    NONE 3C286               13:31:08.287984 +30.30.32.95886 J2000   1          25623
....
...

**Comment by o-smirnov** [comment]
> Just got a MeerKAT ms with 'UNKNOWN' intent for J1939-6342 

A.k.a. the "we don't even know why we're doing this" scan!

@paoloserra indeed not fatal. I'm processing a GMRT MS with no intents at all right now (the completely unintentional observation), it's fine with setting calibrator IDs. In fact this is the least of my problems, but that's a different discussion.

**Comment by KshitijT** [comment]
Which leads me to that infamous point of contention, what to do when ones bandpass calibrators / gain calibrators are not shared among different measurement sets.
Ideally we should not care as long as at least one of the calibrator list is present for a single ms. Or just throw up a warning. 
What happens now is that the pipeline crashes, complaining about the missing calibrator. I have a vague memory of this being discussed (and indeed sorted out) before; so before I cry wolf and open an issue could the experts please opine?

**Comment by o-smirnov** [comment]
The current setting accepts a list of strings, right? I propose we extend the syntax as follows: if the string contains a ":", we parse it as "glob:field". If the glob matches the MS, the name of the field as added to the list of calibrators for that MS. So you would have something like:

```
bpcal:
  - 15578*:J1939
  - 15579*:0408 
```

**Comment by KshitijT** [comment]
> The current setting accepts a list of strings, right? I propose we extend the syntax as follows: if the string contains a ":", we parse it as "glob:field". If the glob matches the MS, the name of the field as added to the list of calibrators for that MS. So you would have something like:
> 
> ```
> bpcal:
>   - 15578*:J1939
>   - 15579*:0408 
> ```

LGTM.
