### ISSUE TITLE
rfimasker does not take units for uvranges

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1138]
``0~1000`` works, but ``0~1km`` does not, contrary to what the description in the schema says. Looking at the code, I think it only supports meters.

We need to either fix the masker, or fix the description.

**Comment by svw26** [comment]
Similarly, it would be good to check whether ```0~1000klambda``` actually works, as the description purports. This CARACal parameter (```uvrange```) is based on FLAGDATA (https://casa.nrao.edu/docs/TaskRef/flagdata-task.html) so it could be a problem with the underlying CASA cab. x

**Comment by o-smirnov** [comment]
I checked the code. Nothing works. :) It expects two numbers in meters, and that's that.

It's not CASA btw, it's a little standalone tool that somebody (maybe Ben?) put together. So it's allowed to not behave like CASA. But then we should adjust the documentation.

**Comment by svw26** [comment]
OK, then the original desc was very wrong 😛  x

**Comment by svw26** [comment]
Nope, it was actually me being misled by "CASA style range, e.g. lower~upper" and then trying to elaborate... Sorry :( x

**Comment by bennahugo** [comment]
I would remove it. As mentioned it is replaced by tricolour. We no longer
develop it.

**Comment by o-smirnov** [comment]
Yeah but other telescopes still may want to use a mask. And there are some opinionated individuals who still run aoflagger. And I hear rumours of some twisted professors who like to do mask+madmax on their targets. 

The mask may be uncomfortable, but it has its place....

![image](https://user-images.githubusercontent.com/6470079/82754902-6024bc00-9dd0-11ea-85a2-6d29b6c2b9ac.png)

**Comment by KshitijT** [comment]
Wait, who's removing masks now?
![image](https://user-images.githubusercontent.com/9251962/82754975-f0630100-9dd0-11ea-9e79-b8736a89b6eb.png)

**Comment by o-smirnov** [comment]
[Unmasking? Obamagate!](https://www.washingtonpost.com/politics/2020/05/21/obamagate-suffers-another-significant-blow/)

**Comment by bennahugo** [comment]
You misunderstand. The masker is built into tricolour. If there are further
features you need raise the issue there.

We won't develop the standalone utility any further.

**Comment by o-smirnov** [comment]
@bennahugo we understand perfectly. The bug was in how caracal invokes rfimasker, that's all. There's nothing to be fixed in rfimasker itself.

I understand it's frozen, but it still does the job, and other telescopes (for which tricolour is not yet an option) may want to use it.
