### ISSUE TITLE
check py3.5 test failure

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1147]
We're keeping 3.5 support for now, but check why the automated test setup with 3.5 fails.

**Comment by SpheMakh** [comment]
Fixed

**Comment by paoloserra** [comment]
@SpheMakh all PRs are now failing because of your commit https://github.com/caracal-pipeline/caracal/commit/72e329ac127b503a554798f25b2b957f46977b09 .
