### ISSUE TITLE
Error when using singularity images in a $SINGULARITY_PULLFOLDER

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1150]
I am encountering this error when reusing a $SINGULARITY_PULLFOLDER in caratekit (hence a bug label). I think I am using it the wrong way (should leave out -f), but I still do not understand the error.
The steps are:
- install caracal together with stimela
- export SINGULARITY_PULLFOLDER=singularity_pullfolder
- stimela pull -s -f
- delete and reinstall caracal together with stimela
- export SINGULARITY_PULLFOLDER=singularity_pullfolder
- stimela pull -s -f (that will reuse cached images)
- start caracal -ct singularity

```
...
# running cd /home/jozsa/software/caracal_tests/test/minitestConfig-singularity && singularity pull  --name stimela_casa_1.2.6.sif docker://stimela/casa:1.2.6
# FATAL:   Image file already exists: "/home/jozsa/software/caracal_tests/singularity_pullfolder/stimela_casa_1.2.6.sif" - will not overwrite
2020-05-27 18:13:59 CARACal ERROR: cd /home/jozsa/software/caracal_tests/test/minitestConfig-singularity && singularity returns error code 255 [StimelaCabRuntimeError]
2
...
```

**Comment by KshitijT** [comment]
This shouldn't happen, @SpheMakh  modified stimela specifically to avoid this issue. Could you please confirm your stimela version?

**Comment by gigjozsa** [comment]
Stimela release: 1.6.1

**Comment by gigjozsa** [comment]
@KshitijT so long, can you confirm that I should not use -f in stimela pull -f -s ?

**Comment by KshitijT** [comment]
No, I can't confirm this - I just tried stimela pull -s -f on a pre-existing stimela image folder and got this:

```
# 
#  0 B / 8.05 KiB [--------------------------------------------------------------]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [=========================================================]
#  8.05 KiB / 8.05 KiB [======================================================] 3s
# Writing manifest to image destination
# Storing signatures
# INFO:    Creating SIF file...
# INFO:    Build complete: stimela_casa_1.2.6.sif
```

**Comment by KshitijT** [comment]
On the other hand, running just stimela pull -s (sans the -f option) gives the intended behaviour (i.e. stimela won't pull an image if it exists already), so maybe it's better to switch to stimela pull -s throughout. 
But I can't reproduce the error which you get above.

**Comment by gigjozsa** [comment]
@KshitijT the error occurs when I run caracal. For some reason it tries to reinstall an image and it can't.

**Comment by KshitijT** [comment]
Yes, I tried that too - for me it goes through without fail, so I don't really know what's going wrong there.

**Comment by gigjozsa** [comment]
Looking into it. What I also do is playing around with renaming ${HOME} etc.

**Comment by gigjozsa** [comment]
There are tons of hidden directories that we are adding directly or indirectly to the home directory. I want to prevent that and to redirect to a local directory.

**Comment by gigjozsa** [comment]
Maybe some /home/$USER vs. $HOME confusion, let's see. I am now re-pulling the images, takes a while.

**Comment by o-smirnov** [comment]
Do we actually have code that says ``/home/$USER`` anywhere? If yes, somebody needs to stand on the naughty step.

**Comment by gigjozsa** [comment]
OK, it is a Singularity feature. And the issue is a different one. It does not even work once for me:
```
workspace=/home/jozsa/software/caracal_tests
test_data_dir=/home/jozsa/software/caracal_tests/pull_request_data
caracal_test_id=handtest
local_caracal=/home/jozsa/software/caracal
workspace_root=${workspace}/${caracal_test_id}
cvirtualenv=${workspace_root}/caracal_venv
HOME_OLD=${HOME}

export HOME=${workspace_root}/home
mkdir -p ${workspace_root}/home

cd ${workspace_root}
virtualenv $cvirtualenv
. ${cvirtualenv}/bin/activate
export PYTHONPATH=''
pip install pip setuptools wheel -U
rm -rf ${workspace_root}/caracal
cp -r /home/jozsa/software/caracal ./

pip install -U --force-reinstall ${workspace_root}/caracal
export SINGULARITY_PULLFOLDER=${workspace_root}/singularity_pullfolder
mkdir -p ${workspace_root}/singularity_pullfolder
stimela pull --singularity -f

rm -rf ${workspace_root}/minitestConfig-singularity
mkdir -p ${workspace_root}/minitestConfig-singularity/msdir
sed "s/dataid: \[.*\]/dataid: ['1532022061_subset']/" ${workspace_root}/caracal/caracal/sample_configurations/minitestConfig.yml > ${workspace_root}/minitestConfig-singularity/minitestConfig.yml
cp -r ${test_data_dir}/1532022061_subset.ms  ${workspace_root}/minitestConfig-singularity/msdir/
cd ${workspace_root}/minitestConfig-singularity
caracal -c minitestConfig.yml -ct singularity
```
results in:
```
2020-05-28 15:56:25 CARACal INFO: obsconf: initializing
# running cd /home/jozsa/software/caracal_tests/handtest/minitestConfig-singularity && singularity pull  --name stimela_casa_1.2.6.sif docker://stimela/casa:1.2.6
# FATAL:   Image file already exists: "/home/jozsa/software/caracal_tests/handtest/singularity_pullfolder/stimela_casa_1.2.6.sif" - will not overwrite
2020-05-28 15:56:25 CARACal ERROR: cd /home/jozsa/software/caracal_tests/handtest/minitestConfig-singularity && singularity returns error code 255 [StimelaCabRuntimeError]
2020-05-28 15:56:25 CARACal INFO:   More information can be found in the logfile at output/logs-20200528-155623/log-caracal.txt
2020-05-28 15:56:25 CARACal INFO: exiting with error code 1
```

and this also happens when using Singularity by hand:
```
(caracal_venv) jozsa@jolap:/home/jozsa/software/caracal_tests/handtest/minitestConfig-singularity$ singularity pull  --name stimela_casa_1.2.6.sif docker://stimela/casa:1.2.6
FATAL:   Image file already exists: "/home/jozsa/software/caracal_tests/handtest/singularity_pullfolder/stimela_casa_1.2.6.sif" - will not overwrite
```

@SpheMakh I assume that Stimela is supposed to either look into SINGULARITY_PULLFOLDER to check if an image already exists or it ignores the error issued by Singularity. This doesn't seem to work here.

**Comment by gigjozsa** [comment]
Now I am wondering if it is the singularity version. As we know, I have just upgraded my computer. I'll check.

**Comment by KshitijT** [comment]
> Now I am wondering if it is the singularity version. As we know, I have just upgraded my computer. I'll check.

Which version of singularity are you using? I did my tests with singularity version 3.1.0.

**Comment by gigjozsa** [comment]
3.5

**Comment by gigjozsa** [comment]
In any case I am stumbling about the meaning of two environment variables:

STIMELA_PULLFOLDER vs. SINGULARITY_PULLFOLDER

I can transform the above error into another one if I set both variables to point to the same directory containing the images. This resolves the issue that the pullfolder is not identified [here](https://github.com/ratt-ru/Stimela/blob/cd8d5a816253df41be9fb812df84c0e9e3f60914/stimela/singularity.py#L43-L49) in Stimela, a method being called and apparently using  STIMELA_PULLFOLDER instead of SINGULARITY_PULLFOLDER to identify SINGULARITY_PULLFOLDER. Again, I don't know the meaning of STIMELA_PULLFOLDER, though.

Just to check if this feature has occurred before, as a consequence I am now getting a fatal error stopping the pipeline, issued by Singularity:
```
# FATAL:   while parsing bind path: wrong bind syntax: /home/jozsa/software/caracal_tests/handtest/minitestConfig-singularity/.stimela_workdir-1590733661589039/passwd:/etc/passwd:rw
```
That is stranga, as I think the syntax is correct. I will now check if the directory exists when the call is made. But let me know if this happened before.

**Comment by gigjozsa** [comment]
SINGULARITY_PULLFOLDER , by the way, is an environment variable that is recognized by Singularity.

**Comment by KshitijT** [comment]
Sorry, I am lost.

What is STIMELA_PULLFOLDER?

**Comment by gigjozsa** [comment]
I am now turning to com08 (Singularity 2.6) to see if I get the same result. In any case, @SpheMakh , is it possible that SINGULARITY_PULLFOLDER and STIMELA_PULLFOLDER have the same meaning?

**Comment by KshitijT** [comment]
@gigjozsa , I am pretty sure there are no two folders and both STIMELA_PULLFOLDER and SINGULARITY_PULLFOLDER should be the same folder.  Both CARACal and Stimela documentation refers to only SINGULARITY_PULLFOLDER variable and I can attest that if it is defined, stimela pull -s will put the images in the path/folder defined by that variable.

**Comment by o-smirnov** [comment]
Yes, we just discovered that this is indeed a bug in Stimela: https://github.com/ratt-ru/Stimela/issues/632

The *intention* is to use STIMELA_PULLFOLDER throughout, but it seems ``stimela pull`` ignores it, causing Singularity to fall back onto SINGULARITY_PULLFOLDER. 

The safest workaround, for now, to avoid confusion, is to set both variables to point to the same folder, which @gigjozsa has already discovered I think.

**Comment by gigjozsa** [comment]
@o-smirnov yes, this was the discovery, thanks! With my singularity version, though, this lead to another problem. I will test if this issue is solved by setting the two variables to the same value, then will have a look at the follow-up crash by using an older Singularity.

**Comment by KshitijT** [comment]
To confirm, if one explicitly runs CARACal as:

caracal -c myconfig.yml -ct singularity -sid PATH_TO_STORED_IMAGES,

it should be correct? 

vs

caracal -c myconfig.yml -ct singularity 

will run into this error?

**Comment by gigjozsa** [comment]
@KshitijT no, the explicit definition of the image folder did not help, I tried that. But I can retry.

**Comment by gigjozsa** [comment]
I think it is because of some confusion of the two variables as mentioned above. Strange that it works for you, though.

**Comment by KshitijT** [comment]
> I think it is because of some confusion of the two variables as mentioned above. Strange that it works for you, though.

Which is why I am a bit worried. :/

**Comment by gigjozsa** [comment]
Ah, wait, it might have been that I run into the second error instead. Will have to check tomorrow.

**Comment by gigjozsa** [comment]
OK, I can confirm that by setting both
``SINGULARITY_PULLFOLDER``
and
``STIMELA_PULLFOLDER``
to the same directory
results in a working CARACal test run (which runs at least further than before so far) on com08 with Singularity 2.6 using precisely the same script above (modulo file names) that leads to a crash on my laptop with singularity version 3.6.0-rc.2+32-gf58ec7834
The same can be achieved by explicitly specifying the pullfolder. But there is definitively some confusion in Stimela about the two variables.

**Comment by gigjozsa** [comment]
The problem with Singularity 3.6 remains.
