### ISSUE TITLE
Keeping home directory clean (generate a flexible radiopadre config directory)

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1153]
Currently there are several hidden directories in the home directory that get created by caracal or rather its dependants. Their total volume is 1.5 GB in a test of mine with 1.35 falling to radiopadre because radiopadre creates a docker/singularity image in the .radiopadre folder in the home directory. There are two problems connected:
i) there is no obvious possibility to generate radiopadre notebooks offline (while the obvious use case of remotely inspecting images of course depends on being online with the server. On the other hand there might be use cases).
ii) depending on the server philosophy, 1.35 GB might already be a bit of storage in the home directory.

The third problem arises when you rename and recreate the home directory to keep the data reduction completely separate from all the rest (like I do in caratekit). One would then like to have a place that can be specified where container images are stored. Using STIMELA_PULLFOLDER one can use pre-fabricated images for Stimela, but for radiopadre this is currently not possible. The solution might be a similar environment variable for radiopadre, which specifies the whereabouts of .radiopadre. I will clone this issue to the radiopadre github.

**Comment by o-smirnov** [comment]
Upgrade ``radiopadfre-client`` please. The 1.0 version supports setting ``RADIOPADRE_DIR`` for the work/cache folder, default is ``~/.radiopadre``.

There is also ``RADIOPADRE_SINGULARITY_IMAGE_DIR`` that can be set separately (and defaults to ``RADIOPADRE_DIR`` otherwise).
