### ISSUE TITLE
Inconsistent behaviour using Singularity v2.6 and v3.5: unable to run with Singularity v2.6

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1154]
This is a Stimela problem. I am trying to reproduce a situation operating on a computing cluster with little space (and low allowed traffic) in the home directory, so I redirect all io to the local directory and the test directory. This is using the current Stimela master (see [minitestConfig-singularity-sysinfo.txt](https://github.com/caracal-pipeline/caracal/files/4720776/minitestConfig-singularity-sysinfo.txt)), which has addressed #1150 via https://github.com/ratt-ru/Stimela/issues/632 and https://github.com/ratt-ru/Stimela/pull/633

Using Stimela v2.6, system details here:
[minitestConfig-singularity-sysinfo.txt](https://github.com/caracal-pipeline/caracal/files/4720776/minitestConfig-singularity-sysinfo.txt)
and following this script (via carate):
[minitestConfig-singularity.sh.txt](https://github.com/caracal-pipeline/caracal/files/4720781/minitestConfig-singularity.sh.txt)
first issuing a stimela pull using a STIMELA_PULLFOLDER and then running caracal using the config file for the minimal test
[minitestConfig-singularity.yml.txt](https://github.com/caracal-pipeline/caracal/files/4720801/minitestConfig-singularity.yml.txt)
the creation of the Stimela images in ``STIMELA_PULLFOLDER=/home/jozsa/caracal_tests/stimela_pullfolder`` fails and caracal crashes immediately after starting:
[minitestConfig-singularity-log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4720799/minitestConfig-singularity-log-caracal.txt). Repeating the caracal error message (this is at runtime):
```
2020-06-02 21:56:40 CARACal INFO: obsconf: initializing
# running cd /home/jozsa/caracal_tests/stimela_pullfolder && singularity pull  --name stimela_casa_1.2.6.img docker://stimela/casa:1.2.6
# 
# WARNING: pull for Docker Hub is not guaranteed to produce the
# WARNING: same image on repeated pull. Use Singularity Registry
# WARNING: (shub://) to pull exactly equivalent images.
# ERROR: Image file exists, not overwriting.
2020-06-02 21:56:40 CARACal ERROR: cd /home/jozsa/caracal_tests/stimela_pullfolder && singularity returns error code 1 [StimelaCabRuntimeError]
2020-06-02 21:56:40 CARACal INFO:   More information can be found in the logfile at output/logs-20200602-215638/log-caracal.txt
2020-06-02 21:56:40 CARACal INFO: exiting with error code 1
```
The pull before repeatedly issues warnings but not an error (for the complete install script see [minitestConfig-singularity.sh.txt](https://github.com/caracal-pipeline/caracal/files/4720781/minitestConfig-singularity.sh.txt)):
```
workspace=/home/jozsa/caracal_tests
...
export SINGULARITY_CACHEDIR=${workspace}/.singularity/cache
mkdir -p ${SINGULARITY_CACHEDIR}
export SINGULARITY_LOCALCACHEDIR=${workspace}/.singularity/localcache
mkdir -p ${SINGULARITY_LOCALCACHEDIR}
export SINGULARITY_TMPDIR=${workspace}/.singularity/tmp
mkdir -p ${SINGULARITY_TMPDIR}
export STIMELA_PULLFOLDER=${workspace}/stimela_pullfolder
mkdir -p ${workspace}/stimela_pullfolder
mkdir -p ${workspace}/stimela_pullfolder
stimela pull --singularity
...
# WARNING: it may be missing some functionality.
# running cd /home/jozsa/caracal_tests/stimela_pullfolder && singularity pull  --name stimela_msutils_1.4.6.img docker://stimela/msutils:1.4.6
# Docker image path: index.docker.io/stimela/msutils:1.4.6
# WARNING: pull for Docker Hub is not guaranteed to produce the
# Cache folder set to /home/jozsa/caracal_tests/.singularity/cache/docker
# 
# [1/1] ||----------------------------------|   0.0%
# [1/1] |===================================| 100.0%
# Importing: base Singularity environment
# WARNING: same image on repeated pull. Use Singularity Registry
# WARNING: (shub://) to pull exactly equivalent images.
# tar: ./.exec: implausibly old time stamp -9223372036854775808
# tar: ./.run: implausibly old time stamp -9223372036854775808
# tar: ./.shell: implausibly old time stamp -9223372036854775808
# tar: ./.singularity.d/actions/exec: implausibly old time stamp -9223372036854775808

...

# Exploding layer: sha256:5b7339215d1d5f8e68622d584a224f60339f5bef41dbd74330d081e912f0cddd.tar.gz
# Exploding layer: sha256:14ca88e9f6723ce82bc14b241cda8634f6d19677184691d086662641ab96fe68.tar.gz

...

# Exploding layer: sha256:d392f2a9c98d545f08d54d972f68580ddb09f29f116121ce1b1b6faca7cc6d9b.tar.gz
# Building Singularity image...
# tar: ./var: implausibly old time stamp -9223372036854775808
# tar: .: implausibly old time stamp -9223372036854775808
# WARNING: Building container as an unprivileged user. If you run this container as root
# Singularity container built: /home/jozsa/caracal_tests/.singularity/cache/stimela_msutils_1.4.6.img
# Cleaning up...
# Done. Container is at: /home/jozsa/caracal_tests/.singularity/cache/stimela_msutils_1.4.6.img
# WARNING: it may be missing some functionality.
...
```
so there is no indication that anything would go wrong. But if I try to list the content of the pullfolder I get an empty directory:
```
ls /home/jozsa/caracal_tests/stimela_pullfolder/
jozsa@ray:~/caracal_tests$
```
while if I list the singularity cache (``${workspace}/.singularity/cache``) the images are stored there:
```
jozsa@ray:~/caracal_tests$ ls .singularity/cache/
docker                       stimela_chgcentre_1.2.0.img        stimela_montage_1.2.4.img       stimela_sharpener_1.2.0.img
metadata                     stimela_codex-africanus_1.3.2.img  stimela_msutils_1.4.6.img       stimela_simms_1.2.0.img
stimela_aegean_1.2.0.img     stimela_cubical_1.4.3.img          stimela_owlcat_1.2.5-1.img      stimela_sofia_1.2.5-1.img
stimela_aimfast_dev.img      stimela_cubical_1.5.4.img          stimela_politsiyakat_1.2.0.img  stimela_sunblocker_1.2.0.img
stimela_aoflagger_1.2.0.img  stimela_curl_1.2.0.img             stimela_pybdsf_1.2.0.img        stimela_tigger_1.2.0.img
stimela_astropy_1.2.0.img    stimela_ddfacet_1.3.3.img          stimela_pyddi_1.1.3.img         stimela_tricolour_1.4.5.img
stimela_casa_0.3.0-1.img     stimela_eidos_1.2.0.img            stimela_ragavi_1.6.1.img        stimela_wsclean_1.2.3.img
stimela_casa_1.2.6.img       stimela_katdal_1.6.0.img           stimela_rfimasker_1.2.0.img     stimela_wsclean_1.6.0-1.img
stimela_casa47_1.4.2.img     stimela_meqtrees_1.2.0.img         stimela_rfinder_1.2.0.img       stimela_wsclean_1.6.0.img
stimela_casarest_1.2.0.img   stimela_meqtrees_1.2.4.img         stimela_shadems_1.4.2-4.img
stimela_catdagger_1.2.0.img  stimela_montage_1.2.0.img          stimela_shadems_1.4.6.img
```
That might be an indication what is going wrong. So I re-define the singularity cache to be in the local directory (as on ilifu e.g. a cache in the home would lead to problems) and use stimela_pullfolder in the local directory with the result above. **Using singularity v3.5.3 on my laptop with exactly the same setup works just fine.**

**Comment by gigjozsa** [comment]
Addendum: the caracal branch used is [fourth_dan](https://github.com/caracal-pipeline/caracal/tree/fourth_dan), which is not differing substantially from master.

**Comment by SpheMakh** [comment]
Wait, did you include the `--force/-f` option when pulling for the second time? It may be singularity issues a warning instead of crashing after 2.6.0, but the `-f` is the solution otherwise.

**Comment by gigjozsa** [comment]
Maybe but I suspect that this is not really the issue. The issue is that no images are created in an empty ``STIMELA_PULLFOLDER`` at the beginning. Then it goes on. The crash happens at runtime. It does not find an image, so it tries to pull the image. But Singularity for some reason looks into the cache instead of the pullfolder and stops. 99% sure that -f will not solve this. Shall I rerun using -f to check?

**Comment by SpheMakh** [comment]
Ahh, I see. You are right `-f` would not solve this.

**Comment by SpheMakh** [comment]
Ok, I got it. Singularity ignores the specified pull folder if you have $SINGULARITY_CACHEDIR set manually.

**Comment by SpheMakh** [comment]
This one is beyond the powers of stimela. We should add a note in the README, then encourage users to use latest version of singularity

**Comment by gigjozsa** [comment]
Did you find out from which version onwards this is solved?

**Comment by gigjozsa** [comment]
@KshitijT do you happen to know the singularity version used at ilifu?

**Comment by KshitijT** [comment]
> @KshitijT do you happen to know the singularity version used at ilifu?

Yes.

**Comment by gigjozsa** [comment]
And?

**Comment by gigjozsa** [comment]
Is it > 3.0 ?

**Comment by gigjozsa** [comment]
Because it's a nasty one. The cache can grow to a large volume and then only symlinks can help, and that's twisted.

**Comment by KshitijT** [comment]
It's 3.5.2. :)

**Comment by KshitijT** [comment]
> Because it's a nasty one. The cache can grow to a large volume and then only symlinks can help, and that's twisted.

BTW, symlinks also help only so much in the current recommended ILIFU settings, eventually one needs to nuke the caches for the pipeline to work.

**Comment by gigjozsa** [comment]
@KshitijT what do you mean? Setting SINGULARITY_DISABLE_CACHE="True" ?

**Comment by KshitijT** [comment]
So my bashrc file has:
```
export SINGULARITY_CACHEDIR=/idia/users/kshitij/.singularity_cache
export SINGULARITY_TMPDIR=/idia/users/kshitij/.singularity_tmp

```
After some time running fine the singularity cache fills up and I get the famous "No space left on disk error". Don't know if that is pertinent to this issue.

**Comment by SpheMakh** [comment]
What is the TMPDIR for?

**Comment by KshitijT** [comment]
Good question. I actually don't know. I was following suggestions from ILIFU. 

@Jordatious , could you please comment?

**Comment by gigjozsa** [comment]
Not know (but they explain it, I only don't understand what a squashfs filesystem is). There are three directories of this kind. It's described here:
https://singularity.lbl.gov/build-environment

**Comment by gigjozsa** [comment]
Point is, setting SINGULARITY_DISABLE_CACHE="True" would suppress caching.

**Comment by gigjozsa** [comment]
So there is variant 1 that I wanted to try:
Use the common STIMELA_PULLFOLDER with the images uploaded by Kshitij/us all. Set SINGULARITY_TMPDIR and SINGULARITY_CACHEDIR to a local directory. In the ideal world, Singularity sees that the images are already in the SINGULARITY_PULLFOLDER aliased to STIMELA_PULLFOLDER and leaves the cache empty (actually I think this is what is happening).

Variant 2 would be the same but setting SINGULARITY_DISABLE_CACHE="True" in addition. My hope would be that this is not needed and you can get away with variant 1. Ach, d*mn, I will just quickly enable this in caratekit.

**Comment by SpheMakh** [comment]
Thanks @gigjozsa. Disabling caching seems like the easy way out to me since we don't build singularity images, and the pulling should be a once off thing. Either way, it is shocking that disk fills up with what really should be a few dozen Gb of data.

**Comment by KshitijT** [comment]
It depends where you are saving the cache? On Rhodes machines we have allocations of 25 GB on home so that fills up pretty fast.

**Comment by gigjozsa** [comment]
OK, it's in. Somebody look at and approve #1157 . Let us for now put Singularity version > 3.5 into the README. Please correct if you find out/know from which version onwards above bug is removed in Singularity.

**Comment by gigjozsa** [comment]
Can we close this?

**Comment by SpheMakh** [comment]
Yup

**Comment by Jordatious** [comment]
Hey @gigjozsa, not totally sure what's happening here without spending longer reading it, but looks like it was resolved. Were you able to get it working and still keep the `TMPDIR` inside your WD?

**Comment by gigjozsa** [comment]
@Jordatious thanks, the conclusion is that this is a Singularity < 3.5 problem, which does not occur for Singularity.

**Comment by AlecThomson** [comment]
Hi all, 

Sorry to bump this older issue, but I've encountered the same problem with both singularity/3.7.3 and singularity/3.8.4. Are there some extra stimela environment variables that need to be set?

For reference there's here my log:
```
2022-02-02 16:10:21 CARACal.Stimela.obsconf INFO: ---------------------------------
2022-02-02 16:10:21 CARACal.Stimela.obsconf INFO: Stimela version 1.7.3
2022-02-02 16:10:21 CARACal.Stimela.obsconf INFO: Running: obsconf
2022-02-02 16:10:21 CARACal.Stimela.obsconf INFO: ---------------------------------
2022-02-02 16:10:21 CARACal.Stimela.obsconf INFO: Config directory cannot be found. Will create /scratch2/tho822/MeerKAT/caracal_test/.stimela_workdir-16437786214004805/stimela_parameter_files
2022-02-02 16:10:21 CARACal INFO: obsconf: initializing
# running cd /scratch2/tho822/MeerKAT/caracal_test && singularity pull  --name stimela_casa_1.7.1.sif docker://quay.io/stimela/casa:1.7.1
# FATAL:   Image file already exists: "/scratch2/tho822/singularity_images/stimela_casa_1.7.1.sif" - will not overwrite
2022-02-02 16:10:21 CARACal ERROR: cd /scratch2/tho822/MeerKAT/caracal_test && singularity returns error code 255 [StimelaCabRuntimeError]
2022-02-02 16:10:21 CARACal INFO:   More information can be found in the logfile at /scratch2/tho822/MeerKAT/caracal_test/logs-20220202-161019/log-caracal.txt
2022-02-02 16:10:21 CARACal INFO:   You are running version 1.0.6
2022-02-02 16:10:21 CARACal ERROR: Traceback (most recent call last):
2022-02-02 16:10:21 CARACal ERROR:   File "/scratch1/tho822/miniconda3/envs/caracal/lib/python3.8/site-packages/caracal/main.py", line 187, in __run
2022-02-02 16:10:21 CARACal ERROR:     pipeline.run_workers()
2022-02-02 16:10:21 CARACal ERROR:   File "/scratch1/tho822/miniconda3/envs/caracal/lib/python3.8/site-packages/caracal/workers/worker_administrator.py", line 441, in run_workers
2022-02-02 16:10:21 CARACal ERROR:     worker.worker(self, recipe, config)
2022-02-02 16:10:21 CARACal ERROR:   File "/scratch1/tho822/miniconda3/envs/caracal/lib/python3.8/site-packages/caracal/workers/obsconf_worker.py", line 37, in worker
2022-02-02 16:10:21 CARACal ERROR:     recipe.add('cab/casa_listobs', step,
2022-02-02 16:10:21 CARACal ERROR:   File "/scratch1/tho822/miniconda3/envs/caracal/lib/python3.8/site-packages/stimela/recipe.py", line 612, in add
2022-02-02 16:10:21 CARACal ERROR:     job.setup_job(image=image, config=config,
2022-02-02 16:10:21 CARACal ERROR:   File "/scratch1/tho822/miniconda3/envs/caracal/lib/python3.8/site-packages/stimela/recipe.py", line 298, in setup_job
2022-02-02 16:10:21 CARACal ERROR:     singularity.pull(image_url,
2022-02-02 16:10:21 CARACal ERROR:   File "/scratch1/tho822/miniconda3/envs/caracal/lib/python3.8/site-packages/stimela/singularity.py", line 44, in pull
2022-02-02 16:10:21 CARACal ERROR:     utils.xrun(f"cd {directory} && singularity", ["pull",
2022-02-02 16:10:21 CARACal ERROR:   File "/scratch1/tho822/miniconda3/envs/caracal/lib/python3.8/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
2022-02-02 16:10:21 CARACal ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2022-02-02 16:10:21 CARACal ERROR: stimela.utils.StimelaCabRuntimeError: cd /scratch2/tho822/MeerKAT/caracal_test && singularity returns error code 255
2022-02-02 16:10:21 CARACal INFO: exiting with error code 1
```
