### ISSUE TITLE
caracal on singularity hanging at report rendering

### ISSUE THREAD

**Issue by healytwin1** [caracal-pipeline/caracal#1166]
I've had 3 recent caracal jobs that have run through to completion on ilifu, but seem to be hanging at the report step:
```
2020-06-07 06:26:15 CARACal INFO: selfcal: finished
2020-06-07 06:26:15 CARACal INFO: Rendering report(s)
# running run-radiopadre --non-interactive --singularity --update --nbconvert output/A2626_x3_v1-detailed-final-report.ipynb
slurmstepd: error: *** JOB 1405268 ON slwrk-115 CANCELLED AT 2020-06-07T12:22:06 ***
```

2 of the jobs I cancelled after it became apparent they had finished but yet to relinquish the node (1 is still 'running'). The cancelled jobs have now shifted the ilifu worker nodes they were using to the 'CG' state:
```
             JOBID PARTITION     NAME     USER    ST       TIME  NODES NODELIST(REASON)
           1402150      Main     A2626-x3 juliahea CG   20:56:12      1  slwrk-152
           1405268      Main    A2626-x3 juliahea CG 1-01:26:09      1 slwrk-115

```

I updated my caracal on Friday to the latest developer version.

cc @Jordatious

**Comment by KshitijT** [comment]
The final reports are produced, right? Which singularity image folder are you using?

**Comment by healytwin1** [comment]
Yes, I think so - I can see the reports in the output folder.
I am using my own singularity image folder /idia/projects/healy-a2626/stimela

**Comment by KshitijT** [comment]
Ok, I was wondering if it is the singularity pull of the radiopadre image which is taking the time, but if you are using the same folder, I guess it must be there already.

**Comment by KshitijT** [comment]
Probably @o-smirnov can help here.

**Comment by healytwin1** [comment]
which is the radiopadre image? I have just done a stimela pull, so the images are up-to-date

**Comment by o-smirnov** [comment]
> Yes, I think so - I can see the reports in the output folder.

Wait, can you see the actual .html reports? That would be weird -- I don't expect it to hang *after* the reports are written out.

@healytwin1 could you try running caracal with ``-debug -report``? This will do nothing except try to re-render the final report, with debug output enabled. It might be clearer from the debug output what stage it hangs at.

> Ok, I was wondering if it is the singularity pull of the radiopadre image which is taking the time, but if you are using the same folder, I guess it must be there already.

OK hang on there's some confusion here. Radiopadre is not under Stimela, so stimela pull doesn't have anything to do with its image. There's a separate ``run-radiopadre --pull-singularity`` command to build its singularity image. (In 1.0.4, we'll integrate everything into a single command via https://github.com/caracal-pipeline/caracal/issues/1104). 

@KshitijT, are you providing radiopadre singularity images on ILIFU? If so, could you please pull down a 1.0 image? It was released on Friday and fixes some of these annoyances. @healytwin1, you should also ``pip install -U radiopadre`` in your virtualenv to update to the 1.0 release. This supports setting RADIOPADRE_SINGULARITY_IMAGE_DIR to use pre-provisioned images.

In caracal 1.0.3 (released on Saturday), the final report rendering is disabled by default.

**Comment by KshitijT** [comment]
> @KshitijT, are you providing radiopadre singularity images on ILIFU? If so, could you please pull down a 1.0 image? It was released on Friday and fixes some of these annoyances. @healytwin1, you should also pip install -U radiopadre in your virtualenv to update to the 1.0 release. This supports setting RADIOPADRE_SINGULARITY_IMAGE_DIR to use pre-provisioned images.

I hadn't gotten around to that. I just did a `run-radiopadre --pull-singularity` to check, the image looks like `osmirnov_radiopadre:1.0pre12.singularity.img`; probably not the latest, since I haven't updated my CARACal install since yesterday. But shouldn't the suffix be `.sif` and not `.img` , @o-smirnov ? If the image above is the latest I can just add it to the shared image folder and @healytwin1 can copy it from there.

**Comment by healytwin1** [comment]
> Wait, can you see the actual .html reports? That would be weird -- I don't expect it to hang _after_ the reports are written out.

Sorry, no reports. I was looking at the wrong files.

> @healytwin1 could you try running caracal with `-debug -report`? This will do nothing except try to re-render the final report, with debug output enabled. It might be clearer from the debug output what stage it hangs at.

I can do that. The one job that I haven't cancelled, but is hanging is stuck at this point:
```
2020-06-06 20:45:24 CARACal INFO: Rendering report(s)
# running run-radiopadre --non-interactive --singularity --update --nbconvert output/Epoch2_v1-detailed-final-report.ipynb
# INFO:    Starting build...
# time="2020-06-06T20:45:26+02:00" level=warning msg="\"/run/user/10173\" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR
.: stat /run/user/10173: no such file or directory: Trying to pull image in the event that it is a public image."
# time="2020-06-06T20:45:29+02:00" level=warning msg="\"/run/user/10173\" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR
.: stat /run/user/10173: no such file or directory: Trying to pull image in the event that it is a public image."
# Getting image source signatures
# Copying blob sha256:5b7339215d1d5f8e68622d584a224f60339f5bef41dbd74330d081e912f0cddd
# Copying blob sha256:14ca88e9f6723ce82bc14b241cda8634f6d19677184691d086662641ab96fe68
# Copying blob sha256:a31c3b1caad473a474d574283741f880e37c708cc06ee620d3e93fa602125ee0
# Copying blob sha256:b054a26005b7f3b032577f811421fab5ec3b42ce45a4012dfa00cf6ed6191b0f
# Copying blob sha256:eccd46fd422dddc03dccc42d60fd2e4960ecce674cdc658b724eec85573572c8
# Copying blob sha256:b482420cdb23ca4c82cf06971b6a4afeb10a6efd52bf9d3a919daf53be5d285c
# Copying blob sha256:41c49cf50b98064ccd814bb48f858c0ff73316ef6edcca82feddf7b8270807f8
# Copying blob sha256:23cf6329d4a1e7ba6457a3c97e4e39a6e0368a69c1a27faa30697c5686ff6b78
# Copying blob sha256:489e5faf835ac85162967f18e0bcf959f134242a6af996a4c87e8aadc5a68b07
# Copying blob sha256:bd6713383782137dabc50cf980a4eb9cbb43b021cc93deb03c79eaccb48aeb33
# Copying blob sha256:402bbe16827853bc8d560936374b58b7e99d755b0265479c2d9cec9512db64e4
# Copying blob sha256:4cbadb63fd3766f77a4e6deab012d7c4f129097c3543afe5c71aa7cef2875c4f
# Copying blob sha256:d9d963d987a9120601f9d0234c300fbf251193ccbfb3521d1969973cc429e92f
# Copying blob sha256:5edf04faf6f5b82baaf858eb39bd79b0159efb83948c5c42aa293455f25fe874
# Copying blob sha256:63fb7cca3d5cb002deac99522f4b8ba19aae84439bdaf180bef7ecf6f463bff4
# Copying blob sha256:ce64aeb3c8f1ded82bac98d70b67b6acad7a01cf224ddbc2551ffc14f0d4eda0
# Copying blob sha256:43e425662d135842fa562a785e7079706e298859421a7dd79016859964362bf3
# Copying blob sha256:85f02dffbb931a636abce22db0e8972d6110280c3cc94778ab2bb31b68801c91
# Copying blob sha256:054e2f5f879a215ce06f3f028f8f784a7565a7fa2d516d43cba24376ac4d130a
# Copying blob sha256:3c61429739e75c7f3f791325a2437323b7282bbd91d02e588aa098b2f4b8ead6
# Copying blob sha256:fb63def4cec21dbc263f820ba02eb2dd7c8ce801fb405c976c4b9ad6099807d6
# Copying blob sha256:c062446ece85db6eb0057df503eb569c5f4b5b7d40cfeb30a0d5fdcc58303472
# Copying config sha256:99213f3d7ead487d9ec4b306932e505b2dd5401783a4dcc60f22e3b678a5c29a
# Writing manifest to image destination
# Storing signatures
# 2020/06/06 20:46:16  info unpack layer: sha256:5b7339215d1d5f8e68622d584a224f60339f5bef41dbd74330d081e912f0cddd
# 2020/06/06 20:46:17  info unpack layer: sha256:14ca88e9f6723ce82bc14b241cda8634f6d19677184691d086662641ab96fe68
# 2020/06/06 20:46:17  info unpack layer: sha256:a31c3b1caad473a474d574283741f880e37c708cc06ee620d3e93fa602125ee0
# 2020/06/06 20:46:17  info unpack layer: sha256:b054a26005b7f3b032577f811421fab5ec3b42ce45a4012dfa00cf6ed6191b0f
# 2020/06/06 20:46:17  info unpack layer: sha256:eccd46fd422dddc03dccc42d60fd2e4960ecce674cdc658b724eec85573572c8
# 2020/06/06 20:46:17  info unpack layer: sha256:b482420cdb23ca4c82cf06971b6a4afeb10a6efd52bf9d3a919daf53be5d285c
# 2020/06/06 20:46:17  info unpack layer: sha256:41c49cf50b98064ccd814bb48f858c0ff73316ef6edcca82feddf7b8270807f8
# 2020/06/06 20:46:17  info unpack layer: sha256:23cf6329d4a1e7ba6457a3c97e4e39a6e0368a69c1a27faa30697c5686ff6b78
# 2020/06/06 20:46:18  info unpack layer: sha256:489e5faf835ac85162967f18e0bcf959f134242a6af996a4c87e8aadc5a68b07
# 2020/06/06 20:46:19  info unpack layer: sha256:bd6713383782137dabc50cf980a4eb9cbb43b021cc93deb03c79eaccb48aeb33
# 2020/06/06 20:46:19  info unpack layer: sha256:402bbe16827853bc8d560936374b58b7e99d755b0265479c2d9cec9512db64e4
# 2020/06/06 20:46:19  info unpack layer: sha256:4cbadb63fd3766f77a4e6deab012d7c4f129097c3543afe5c71aa7cef2875c4f
# 2020/06/06 20:46:19  info unpack layer: sha256:d9d963d987a9120601f9d0234c300fbf251193ccbfb3521d1969973cc429e92f
# 2020/06/06 20:46:19  info unpack layer: sha256:5edf04faf6f5b82baaf858eb39bd79b0159efb83948c5c42aa293455f25fe874
# 2020/06/06 20:46:31  warn rootless{usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-ptp-helper} ignoring (usually) harmless EPERM on setxattr "security.capability"
# 2020/06/06 20:46:38  info unpack layer: sha256:63fb7cca3d5cb002deac99522f4b8ba19aae84439bdaf180bef7ecf6f463bff4
# 2020/06/06 20:46:38  info unpack layer: sha256:ce64aeb3c8f1ded82bac98d70b67b6acad7a01cf224ddbc2551ffc14f0d4eda0
# 2020/06/06 20:46:38  info unpack layer: sha256:43e425662d135842fa562a785e7079706e298859421a7dd79016859964362bf3
# 2020/06/06 20:46:38  info unpack layer: sha256:85f02dffbb931a636abce22db0e8972d6110280c3cc94778ab2bb31b68801c91
# 2020/06/06 20:46:46  info unpack layer: sha256:054e2f5f879a215ce06f3f028f8f784a7565a7fa2d516d43cba24376ac4d130a
# 2020/06/06 20:46:46  info unpack layer: sha256:3c61429739e75c7f3f791325a2437323b7282bbd91d02e588aa098b2f4b8ead6
# 2020/06/06 20:46:46  info unpack layer: sha256:fb63def4cec21dbc263f820ba02eb2dd7c8ce801fb405c976c4b9ad6099807d6
# 2020/06/06 20:47:00  info unpack layer: sha256:c062446ece85db6eb0057df503eb569c5f4b5b7d40cfeb30a0d5fdcc58303472
# INFO:    Creating SIF file...
# INFO:    Build complete: /users/juliahealy/.radiopadre/osmirnov_radiopadre:1.0.singularity.img.new.img

```

> In caracal 1.0.3 (released on Saturday), the final report rendering is disabled by default.

Great, will update once the current jobs have completed.

I have tried `pip install -U radiopadre` - the install fails - does it work with python 3?

**Comment by o-smirnov** [comment]
@healytwin1 sorry, misleading you: do ``pip install -U radiopadre-client``. You don't need the main package, that's what the images are for...

@KshitijT, same for you, then pull again. You need the 1.0 release, not the rc12 pre-release. The suffix doesn't matter.

The output is interesting, as it suggests that the image has been built at least... ok let's see what the debug output says...

**Comment by healytwin1** [comment]
@o-smirnov I have run caracal again with `-debug -report` on one of the jobs that hung. No reports were created despite radiopadre being up-to-date. Attached is the log file.
[fullband_E2-1408326-stderr.log](https://github.com/caracal-pipeline/caracal/files/4752397/fullband_E2-1408326-stderr.log)

**Comment by o-smirnov** [comment]
As Trump would say, that's a perfect log! I see

```
# radiopadre.client: Using existing radiopadre singularity image /users/juliahealy/.radiopadre/osmirnov_radiopadre:1.0.singularity.img
```

And I see it ending with

```
# [NbConvertApp] Writing 9076961 bytes to Epoch2_v1-detailed-final-report.html
2020-06-08 16:48:50 CARACal INFO: Rendered report output/Epoch2_v1-detailed-final-report.html
```

And you're saying the .HTML file is not actually there?

**Comment by healytwin1** [comment]
Found it. I was looking in the reports directory

**Comment by o-smirnov** [comment]
Ah, good point! We are, perhaps, rendering it to the wrong directory.

**Comment by healytwin1** [comment]
I think though that the hanging was fixed by updating radiopadre manually.
