### ISSUE TITLE
transform worker does not handle two targets / two MSs correctly

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1170]
I have two targets observed across two MSs (i.e. each MS contains both targets). When it gets to the target splitting stage, transform does this for the first MS, which is correct:

```
mstransform(vis="/stimela_mount/input/1557766852_sdp_l0_1284.full_pol.ms",outputvis="/stimela_mount/msdir/od1-1557766852_sdp_l0_1284.full_pol-CGCG044_046-corr.ms"
```

and then this for the second MS:

```
mstransform(vis="/stimela_mount/input/1568538661_sdp_l0.ms",outputvis="/stimela_mount/msdir/od1-1557766852_sdp_l0_1284.full_pol-CGCG044_046-corr.ms"
```

which is not correct -- notice how the output name is based on the first MS. This causes a crash, of course, because the output MS already exists.

@paoloserra assigning to you for redistribution. :)

**Comment by paoloserra** [comment]
I'm puzzled, we've used this so many times by now.

I've just run two a test with your exact situation (two .MS files both including the same two targets) and here's what I get:

```
2020-06-09 10:42:08 CARACal INFO: Extracting MS info from output/obsinfo/gps1-obsinfo.json 
2020-06-09 10:42:08 CARACal INFO: ====================================
2020-06-09 10:42:08 CARACal INFO: TARGET
2020-06-09 10:42:08 CARACal INFO:  ---------------------------------- 
2020-06-09 10:42:08 CARACal INFO: T29R03C01 (ID=2) : 54.78 minutes | RA=142.50 deg, Dec=-52.60 deg
2020-06-09 10:42:08 CARACal INFO: T29R03C03 (ID=3) : 52.91 minutes | RA=141.33 deg, Dec=-51.91 deg

2020-06-09 10:42:09 CARACal INFO: Extracting MS info from output/obsinfo/gpsx-obsinfo.json 
2020-06-09 10:42:09 CARACal INFO: ====================================
2020-06-09 10:42:09 CARACal INFO: TARGET
2020-06-09 10:42:09 CARACal INFO:  ---------------------------------- 
2020-06-09 10:42:09 CARACal INFO: T29R03C01 (ID=2) : 54.78 minutes | RA=142.50 deg, Dec=-52.60 deg
2020-06-09 10:42:09 CARACal INFO: T29R03C03 (ID=3) : 52.91 minutes | RA=141.33 deg, Dec=-51.91 deg

mstransform(vis="/stimela_mount/msdir/gps1.ms",outputvis="/stimela_mount/msdir/gps1-T29R03C01_corr.ms"

mstransform(vis="/stimela_mount/msdir/gps1.ms",outputvis="/stimela_mount/msdir/gps1-T29R03C03_corr.ms"

mstransform(vis="/stimela_mount/msdir/gpsx.ms",outputvis="/stimela_mount/msdir/gpsx-T29R03C01_corr.ms"

mstransform(vis="/stimela_mount/msdir/gpsx.ms",outputvis="/stimela_mount/msdir/gpsx-T29R03C03_corr.ms"

```

Possibly unrelated, I've noticed that your output .MS names have an `od1-` prefix. I'm not sure where that comes from.

**Comment by o-smirnov** [comment]
> your output .MS names have an od1- prefix

That's just my general: prefix. Pipeline overdose 1!

Hehe, it's even weirder. Looking closer, here are my three transform calls.

The good (log-transform-split_field-ms0-0, so first target, first MS):
```
mstransform(vis="/stimela_mount/input/1557766852_sdp_l0_1284.full_pol.ms",outputvis="/stimela_mount/msdir/od1-1557766852_sdp_l0_1284.full_pol-CGCG044_046-corr.ms",createmms=False,separationaxis="auto",numsubms="auto",
tileshape=[0],field="CGCG044-046",spw="",scan="",antenna="",
```

The bad (log-transform-split_field-ms0-1, so second target, first MS:
```
mstransform(vis="/stimela_mount/input/1557766852_sdp_l0_1284.full_pol.ms",outputvis="/stimela_mount/msdir/od1-1568538661_sdp_l0-CGCG044_046-corr.ms",createmms=False,separationaxis="auto",numsubms="auto",
tileshape=[0],field="CGCG021-063",spw="",scan="",antenna="",
```
Notice how outputvis doesn't match the target name? And of course the ugly, ms1-0:
```
mstransform(vis="/stimela_mount/input/1568538661_sdp_l0.ms",outputvis="/stimela_mount/msdir/od1-1557766852_sdp_l0_1284.full_pol-CGCG044_046-corr.ms",createmms=False,separationaxis="auto",numsubms="auto",
tileshape=[0],field="CGCG044-046",spw="",scan="",antenna="",
```

Just looks like the MS/target indices are swapped around somewhere, no?

**Comment by paoloserra** [comment]
> > your output .MS names have an od1- prefix
> 
> That's just my general: prefix. Pipeline overdose 1!

sure, but prefixes shouldn't get used for .MS file names. (And I know this is not the main problem, just posting this one while I think about the rest.)

**Comment by paoloserra** [comment]
> Notice how outputvis doesn't match the target name?

In my test I don't see this either.

**Comment by SpheMakh** [comment]
This is with the the issue-1086 branch right?

**Comment by o-smirnov** [comment]
> This is with the the issue-1086 branch right?

Ah yes. Does that make a difference to the transform worker?

**Comment by SpheMakh** [comment]
Yes, it does. I'm pretty sure the bug introduced be me :) I'll have a look and get back to you

**Comment by o-smirnov** [comment]
Ah ok. @paoloserra nevermind, at least we know why you don't see it.

**Comment by paoloserra** [comment]
good

**Comment by o-smirnov** [comment]
> sure, but prefixes shouldn't get used for .MS file names.

So apparently in the new "readonly source MS" workflow they do, split-out MSs will have prefixes. I'd like some time to process my thoughts on this -- but it's a big enough change that we should probably discuss at the next meeting.

**Comment by paoloserra** [comment]
Note that at some point (and for a short amount of time) we used to have prefixes in the obsinfo files. That turned out to be very annoying. I suspect this will be the same.

**Comment by SpheMakh** [comment]
Lol, I totally missed that obsinfo files did not have prefixes.

**Comment by paoloserra** [comment]
The reason for removing the prefix from the obsinfo file was that if, e.g., you wanted to re-image the same .MS with different imaging settings and a new prefix, the pipeline would crash because it couldn't find the obsinfo file. The same would happen if we included the prefix in the .MS file name.

**Comment by o-smirnov** [comment]
> The same would happen if we included the prefix in the .MS file name.

Yeah same reason it makes me uneasy. 

I see the argument that the split MS is an "output product" and therefore should have the prefix on it.

On the other hand, it's a BFOP (big effing output product), while trial reruns with a different prefix are small and cheap. So maybe BFOPs should be treated separately, and not get the prefix (by default).

Anyway, let's discuss at the next meeting.

**Comment by SpheMakh** [comment]
The fate of the obsinfo prefix is entangled to whether the MSs get one or not. It makes the most sense to have obsinfo as `{msbase}.{ext}`.

**Comment by paoloserra** [comment]
I'm very happy with the current behaviour and suggest to not change that.

**Comment by o-smirnov** [comment]
So here's an interesting conundrum with this new R/O workflow (related/not related to prefixes).

I ran the pipeline from the start. I have 6 obsinfo outputs:

```
output-od1-meerkat-skymodel-true/obsinfo/1568538661_sdp_l0-obsinfo.json
output-od1-meerkat-skymodel-true/obsinfo/1557766852_sdp_l0_1284.full_pol-obsinfo.json
output-od1-meerkat-skymodel-true/obsinfo/od1-1568538661_sdp_l0-CGCG044_046-corr-obsinfo.json
output-od1-meerkat-skymodel-true/obsinfo/od1-1557766852_sdp_l0_1284.full_pol-CGCG044_046-corr-obsinfo.json
output-od1-meerkat-skymodel-true/obsinfo/od1-1568538661_sdp_l0-cal-obsinfo.json
output-od1-meerkat-skymodel-true/obsinfo/od1-1557766852_sdp_l0_1284.full_pol-cal-obsinfo.json
```
The first two come from my raw MSs. The other ones were created when the calibrators and targets were split out.

Now I want to make a new output directory and run crosscal with different parameters (I'm digging into #1049). Very specifically with a different output directory, because I want to compare the two side-by-side. I restart the pipeline from crosscal with a new output directory name, BOOM, nothing works because all my obsinfos are in the other output directory... 

The pipeline knows how to re-make obsinfos from the raw MSs, but it doesn't know what to do about the split MSs, because, conceptually, those only appear in the transform worker, which in this case I'm skipping.

The only way to get those obsinfos for me is to (a) re-split, which is time-consuming and wasteful, or (b) copy the files by hand, which is messy and error-prone.

Offhand, my proposed solution would be to keep obsinfo files in msdir. They are not, after all, output products -- they are properties of the MS (in fact, all they do is summarize some stuff about the MS in Caracal-readable form), so they belong alongside the MS, not under output. Well a copy could be placed in output for convenience -- but transform and the like should write them to msdir.

**Comment by paoloserra** [comment]
can close this?
