### ISSUE TITLE
do we need to rerun obsinfo & make elevation plots every time

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1172]
Currently these two steps happen every time the pipeline is invoked, even if it is from an intermediate worker. 

This is harmless, but seems wasteful, as both obsinfo and the plots are already available each time, and do not really need to be regenerated. It's also annoying, for a couple of reasons:

* It slows down debugging (if I'm debugging the inspect worker, for example, I rerun with ``-sw inspect -ew inspect`` many many times. Each time I wait for elevation plots...)

* It makes it annoying to inspect logs, in the multiple stop-restart scenario. A useful pattern (again, when debugging), is to look at the logs in chronological order with ``ls logs-*/log*txt -rt``. But this list becomes polluted with redundant log-obsconf* entries.

This is only a minor fix, and since I'm the only one who seems annoyed, I volunteer to do it.

**Comment by SpheMakh** [comment]
Yeah, I find this annoying also. I usually add `--obscocnf-obsinfo-enable false` whenever I re-run to avoid it, but something simpler like `--no-osbinfo/-no`  would save me a lot typing

**Comment by o-smirnov** [comment]
OK. And just because I don't want to open a separate issue, I'll eliminate all the endless ``open(msinfo, 'r')`` calls. I estimate that file is read and discarded a few dozen times in obsinfo...

**Comment by SpheMakh** [comment]
Yes, please!

**Comment by o-smirnov** [comment]
@gigjozsa, on that note, what file does sunblocker generate? Is it a fixed filename?

**Comment by paoloserra** [comment]
can close this?
