### ISSUE TITLE
make the splitting of extensions off the MS more consistent

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1173]
I've already briefly complained about this before, but now I see him again. Yes, it's him, the butt-chinned alien from the Mos Eisley Cantina. Just tilt your head left and you'll see his vidage all over the code:
```
$ grep ":-3" */*py
workers/line_worker.py:            pipeline.obsinfo, msfile[:-3])
workers/line_worker.py:                pipeline.obsinfo, msfile[:-3])
workers/line_worker.py:                            "listfile": '{0:s}-obsinfo.txt'.format(msname_mst[:-3]),
workers/line_worker.py:                        "outfile": '{0:s}-obsinfo.json'.format(msname_mst[:-3]),
workers/line_worker.py:                        pipeline.obsinfo, msfile[:-3])
workers/line_worker.py:                pipeline.obsinfo, msfile[:-3])
workers/line_worker.py:                        pipeline.obsinfo, msfile[:-3])
workers/line_worker.py:                pipeline.obsinfo, msfile[:-3])
workers/selfcal_worker.py:                           "prefix": '{0:s}_{1:s}_{2:d}_meqtrees'.format(pipeline.dataid[i], msname[:-3], num),
workers/selfcal_worker.py:                           "prefix": '{0:s}_{1:s}_{2:d}_meqtrees'.format(pipeline.dataid[i], msname[:-3], num),
workers/selfcal_worker.py:            msinfo = '{0:s}/{1:s}-obsinfo.json'.format(pipeline.obsinfo, msname[:-3])
workers/selfcal_worker.py:                                                                                  pipeline), prefix, msname[:-3], num),
workers/selfcal_worker.py:            msinfo = '{0:s}/{1:s}-obsinfo.json'.format(pipeline.obsinfo, msname_out[:-3])
workers/selfcal_worker.py:                                                                              msname_out[:-3], num),
workers/selfcal_worker.py:        filename='{0:s}/{1:s}-obsinfo.json'.format(pipeline.obsinfo,msname[:-3])
workers/transform_worker.py:                        listfile = '{0:s}-obsinfo.txt'.format(tms[:-3])
workers/transform_worker.py:                        listfile = '{0:s}-obsinfo.json'.format(tms[:-3])
```
The discussion about whether MSs are allowed to have a ``.vis`` extension is moot until butt-chin is purged, because they won't work anyway...

**Comment by o-smirnov** [comment]
He has a friend: ``msname.split('.ms')[0]``. Sometimes they even show up together in the same line of code. I will shoot them both.

**Comment by o-smirnov** [comment]
There are too many. I am overwhelmed and going to sleep.

**Comment by KshitijT** [comment]
> He has a friend: `msname.split('.ms')[0]`. Sometimes they even show up together in the same line of code. I will shoot them both.

This seems...familiar. 

Note that I am absolutely NOT confessing to coming up with that line.

**Comment by o-smirnov** [comment]
@KshitijT, since you're in a (not) confessional mood, any idea what's meant here in ddcal:
```
        mspref = mslist[0].split('.ms')[0].replace('-','_')
        step = 'img_wsclean-{0:s}-{1:s}'.format(mspref,field)
```
Is mspref just meant as a unique label to put into the step name?

**Comment by KshitijT** [comment]
> @KshitijT, since you're in a (not) confessional mood, any idea what's meant here in ddcal:
> 
> ```
>         mspref = mslist[0].split('.ms')[0].replace('-','_')
>         step = 'img_wsclean-{0:s}-{1:s}'.format(mspref,field)
> ```
> 
> Is mspref just meant as a unique label to put into the step name?

Yup. It was long time ago; I was young and innocent and did not know these notions of allowing datasets ending with ".vis" / ".MS"/ ".myfluffycat". :sob:

**Comment by o-smirnov** [comment]
I wasn't worried about the split anymore because I understand the meaning 100%... its the ``mspref`` thing that had me in some doubt.

**Comment by KshitijT** [comment]
> I wasn't worried about the split anymore because I understand the meaning 100%... its the `mspref` thing that had me in some doubt.

Ah, just my silly way of coming up with a ms-specific label.

**Comment by o-smirnov** [comment]
It's as good a way as any. Better than most, actually. But why ``replace('-','_')``? 

(Not asking in criticism, just making sure there isn't some cunning logic that my changes might break...)

**Comment by KshitijT** [comment]
Stimela label don't fancy a hyphen..

**Comment by o-smirnov** [comment]
Yes it does. And you already have hyphens in the label anyway, look:  ``img_wsclean-``

**Comment by KshitijT** [comment]
Wow. Ok, then that's just needless, please remove it if you are planning to change that line in your PR.
