### ISSUE TITLE
Use the Mauch et al. primary beam correction for mosaicing and primary beam correction

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1180]
@bnamumba found a significant difference between total HI fluxes of HIPASS sources and total HI fluxes of galaxies detected in a MeerKAT observation and primary-beam corrected using our standard Gaussian. We had a look and the difference might well be due to the fact that the Gaussian is significantly narrower than the Mauch et al. 2019 primary beam found to be more accurate for the MeerKAT primary beam. Therefore, could we implement:

```
fwhm = 8.783e10/(60.*nu)

            fwhm.resize((basedata.shape[0], 1, 1))
            theta = np.sqrt(datacube)
            # a = (np.cos(1.189*np.pi*(theta/FWHM))/(1-4*(1.189*(theta/FWHM))**2))**2
            datacube = pow((pow(np.cos(1.189*np.pi*(theta/fwhm))/(1-4*pow(1.189*(theta/fwhm),2)),2))/rmsbeam[i],2)

```

**Comment by paoloserra** [comment]
@gigjozsa Thanks for taking care of this. Could you please implement it in such a way that we have either a telescope option (e.g., MeerKAT, VLA), or a function option (e.g. gauss, mauch)?

**Comment by svw26** [comment]
👍 'Gaussian' and 'Mauchian' sounds good to me...! x

**Comment by gigjozsa** [comment]
Mauchian, that's great. The cos^6 of WSRT would be a "Brouwian"

**Comment by dane-kleiner** [comment]
Hey @gigjozsa, @paoloserra and I have decided that we need to use the Mauchian primary beam model for our paper, so unless you're (almost) ready to commit the changes, I'm happy to make and implement the changes myself.

**Comment by gigjozsa** [comment]
@dane-kleiner thank you, please go ahead, I am myself currently busy with #779 in the same context.

**Comment by dane-kleiner** [comment]
@paoloserra, please have a look at the [mauchian](https://github.com/caracal-pipeline/caracal/tree/mauchian) branch to see if we can figure out those anomalous pixels before creating a PR.

**Comment by paoloserra** [comment]
#1215 should have closed this. Mauch et al. (2020) PB now available both in the line and mosaic workers.
