### ISSUE TITLE
Existential crisis: What doesn't kill CARACal only makes it wronger.

### ISSUE THREAD

**Issue by KshitijT** [caracal-pipeline/caracal#1195]
Currently the pipeline does not check if all the measurement sets mentioned in the obsinfo:dataid list actually exist - as long as a single one exists it seems to be fine. 

This is not the ideal state of things and needs to go.

**Comment by KshitijT** [comment]
Note the milestone.

**Comment by o-smirnov** [comment]
The French invented democracy, existentialism...

**Comment by KshitijT** [comment]
> The French invented democracy, existentialism...

I'll be sure to mention Tricolour issues next time.

**Comment by KshitijT** [comment]
This issue is closed by #1196 . 

Must be, what, the fastest fix ever? 

Thanks, @SpheMakh !
