### ISSUE TITLE
ddcal does not apply pb correction

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1197]
In ddcal worker, I set `use_pb: true`, but it has not applied primary beam correction to the precal image. Does it apply primary beam correction to both pre-and postcal images? Thanks.

**Comment by KshitijT** [comment]
Could you please share the log?

**Comment by viralp** [comment]
It seems that `--Beam-Model` did not set to FITS.  

[log-ddcal-make-pb-20200702-195356.txt](https://github.com/caracal-pipeline/caracal/files/4878208/log-ddcal-make-pb-20200702-195356.txt)
[log-ddcal-ddf_image-Abell3376East-20200702-195356.txt](https://github.com/caracal-pipeline/caracal/files/4878209/log-ddcal-ddf_image-Abell3376East-20200702-195356.txt)

**Comment by KshitijT** [comment]
Ah, wait. I am being silly. 

The pb-image is made only post-calibration. Note that the way cubical is set to do dd-correction is not yet set to using primary beams - hence only the postcal image is imaged with the beam. 

If you want a beam applied image before dd-calibration, I can add the feature, but please confirm that is what you want.

**Comment by viralp** [comment]
Thanks Kshitij for clarification. If it is hard to change, then I will simply run DDFacet outside of the Caracal as I just want to make pb corrected image.

**Comment by KshitijT** [comment]
> Thanks Kshitij for clarification. If it is hard to change, then I will simply run DDFacet outside of the Caracal as I just want to make pb corrected image.

That might be best for the moment. I'll add an option to include the beam in the precal image in a day or two.
