### ISSUE TITLE
All your time are belong MeqTrees

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/caracal#1202]
It took MeqTrees **9hrs** to simulate bandpass field. I think this is because of the small tile-size hardcoded in the crosscal worker 

https://github.com/caracal-pipeline/caracal/blob/9ccbb0aad07b6a71b0d5da8b4c2344eb66632dd4/caracal/workers/crosscal_worker.py#L500

```
### Stopping the meqserver
### All your batch are belong to us. Bye!
Container [set_model_cal_0-13965993688318415946652621373048] has executed successfully
Runtime was 9:00:15.509844.
```

**Comment by SpheMakh** [comment]
It may not be entirely the tile-size's fault 

![Screenshot from 2020-07-14 07-25-03](https://user-images.githubusercontent.com/6624280/87387524-2f2c6080-c5a3-11ea-8073-0489135fd867.png)

**Comment by bennahugo** [comment]
Are those actually meqserver threads? If so try resetting the page cache in
the kernel.

**Comment by SpheMakh** [comment]
No, that's someone else running crystalball; I suspect MeqTrees would've been much faster if it had more resources to work with.
