### ISSUE TITLE
allow the use of a subset of the band for GK solutions

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1204]
I vaguely recall discussing this with @IanHeywood way back, but looking at "my" uGMRT data really brings this home.

There may be an advantage to be had in picking a "clean" part of the band and using only that bit for the G/K solutions. The gaincal() task supports it via the spw argument, which Stimela exposes.

(Currently looking at some data where one antenna got really low G-ampl solutions on the primary, for reasons unknown -- this got locked into a super-high bandpass amplitude instead...)

Suggest adding a ``primary: spw`` and ``secondary: spw`` parameter, which is then passed onto gaincal.

**Comment by IanHeywood** [comment]
I've been doing this for UHF to try to keep things close to the top end of the band and it seems to work well. The UHF RFI situation is of course a lot better than that of L-band.

I think the SDP pipeline does something similar:

https://github.com/ska-sa/katsdpcal/blob/master/katsdpcal/conf/pipeline_params/pipeline_parameters_meerkat_L.txt#L6

This would probably also dodge the issues with the fluxscale task and the spectrum of the secondary, but I never got around to implementing it on L-band to test it. I don't know what the implications are for weaker secondaries either, but give the user enough rope and all that.

**Comment by bennahugo** [comment]
Btw Ian I have models for UHF bandpass calibrators which I verified the
flux scale with if you are still interested.

**Comment by IanHeywood** [comment]
I am most definitely interested, thanks @bennahugo.

**Comment by SpheMakh** [comment]
Yeah, I can't believe we didn't do this before! 

How should we treat the on the fly auto flagging, should we pass the `spw` to the flagged also?

**Comment by IanHeywood** [comment]
> should we pass the spw to the flagged also?

You'd have to modify ragavi-gains to allow channel selection if you only flagged the cal region, otherwise phaseball-type plots wouldn't be a very good diagnostic.

**Comment by o-smirnov** [comment]
> How should we treat the on the fly auto flagging, should we pass the spw to the flagged also?

No. Nor should we pass it to the bandpass task. The idea is to use the full remaining band for everything else.

If the user wants to use a subset of the band for *everything*, they can simply flag the rest of the band in the flagging worker.

> You'd have to modify ragavi-gains to allow channel selection if you only flagged the cal region, otherwise phaseball-type plots wouldn't be a very good diagnostic.

I'm confused -- you mean ragavi-vis surely, since ragavi-gains doesn't do phaseballs. Even then, applycal should be applied to the entire unflagged band, so the phaseball plots ought to stay meaningful?

**Comment by IanHeywood** [comment]
Sorry ignore me, I meant ragavi-vis, which has channel selection.

**Comment by IanHeywood** [comment]
I think if you don't flag the entire band for the secondary then you'll just have a load of residual RFI dominating the plot.

**Comment by o-smirnov** [comment]
@SpheMakh I sort of need this now so I volunteer to do it. Unless you've already done it.

**Comment by SpheMakh** [comment]
It's done, I'm just running a test. I'll push my branch now

**Comment by o-smirnov** [comment]
Even better!

**Comment by o-smirnov** [comment]
In case either of you is curious about the mystery of how my phaseballs are squaring the circle, I've added you to https://github.com/o-smirnov/gmrt-reductions. (Also experimenting with hosting radiopadre HTML reports on github.io...)

**Comment by SpheMakh** [comment]
I just pushed the branch, its issue-1204

**Comment by o-smirnov** [comment]
```
# 2020-07-16 14:05:50   INFO    gaincal::::+    ##########################################
# 2020-07-16 14:05:50   INFO    gaincal::::+    ##### Begin Task: gaincal            #####
# 2020-07-16 14:05:50   INFO    gaincal::::     gaincal(vis="/stimela_mount/msdir/4C12.03-610-cal.ms",caltable="/stimela_mount/output/4C12.03-4C12.03-610-1gc1_primary.K1",field="3C48",spw="650~750MHz",intent="",
# 2020-07-16 14:05:50   INFO    gaincal::::+            selectdata=True,timerange="",uvrange="",antenna="",scan="",
# 2020-07-16 14:05:50   INFO    gaincal::::+            observation="",msselect="",solint="inf",combine="None",preavg=-1.0,
# 2020-07-16 14:05:50   INFO    gaincal::::+            refant="C01",refantmode="flex",minblperant=4,minsnr=3.0,solnorm=False,
# 2020-07-16 14:05:50   INFO    gaincal::::+            normtype="mean",gaintype="K",smodel=[],calmode="ap",solmode="",
# 2020-07-16 14:05:50   INFO    gaincal::::+            rmsthresh=[],append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,
# 2020-07-16 14:05:50   INFO    gaincal::::+            docallib=False,callib="",gaintable=['/stimela_mount/output/4C12.03-4C12.03-610-1gc1_primary.G0', '/stimela_mount/output/4C12.03-4C12.03-610-1gc1_primary.B0'],gainfield=['3C48', '3C48'],interp=['nearest', 'linear'],
# 2020-07-16 14:05:50   INFO    gaincal::::+            spwmap=[],parang=False)
# 2020-07-16 14:05:50   INFO    gaincal::calibrater::open       ****Using NEW VI2-driven calibrater tool****
# 2020-07-16 14:05:50   INFO    gaincal::calibrater::open       Opening MS: /stimela_mount/msdir/4C12.03-610-cal.ms for calibration.
# 2020-07-16 14:05:50   INFO    gaincal::Calibrater::   Initializing nominal selection to the whole MS.
# 2020-07-16 14:05:50   INFO    gaincal::::     NB: gaincal automatically excludes auto-correlations.
# 2020-07-16 14:05:50   INFO    calibrater::setdata     Beginning selectvis--(MSSelection version)-------
# 2020-07-16 14:05:50   INFO    calibrater::reset       Reseting solve/apply state
# 2020-07-16 14:05:50   INFO    Calibrater::selectvis   Performing selection on MeasurementSet
# 2020-07-16 14:05:50   INFO    Calibrater::selectvis+   Selecting on spw: '650~750MHz'
# 2020-07-16 14:05:50   INFO    Calibrater::selectvis+   Selecting on field: '3C48'
# 2020-07-16 14:05:50   INFO    Calibrater::selectvis+   Selecting with TaQL: 'ANTENNA1!=ANTENNA2'
# 2020-07-16 14:05:50   INFO    Calibrater::selectvis   By selection 362355 rows are reduced to 97440
# 2020-07-16 14:05:50   INFO    Calibrater::selectvis   Frequency selection:
# 2020-07-16 14:05:50   INFO    Calibrater::selectvis   .  Spw 0:0~6143 (6144 channels, step by 1)
# 2020-07-16 14:05:50   INFO    calibrater::setdata     chanmode=none nchan=1 start=0 step=1 mStart='0km/s' mStep='0km/s' msSelect='ANTENNA1!=ANTENNA2'
# 2020-07-16 14:05:50   INFO    calibrater::setapply    Beginning setapply--(MSSelection version)-------
```
Should I be worried about this log? The lines:

```
# 2020-07-16 14:05:50   INFO    Calibrater::selectvis+   Selecting on spw: '650~750MHz'
# 2020-07-16 14:05:50   INFO    Calibrater::selectvis   Frequency selection:
# 2020-07-16 14:05:50   INFO    Calibrater::selectvis   .  Spw 0:0~6143 (6144 channels, step by 1)
```

...are mutually contradictory.

**Comment by o-smirnov** [comment]
Ah wait, should it be ``0:650~750MHz`` perhaps?

**Comment by o-smirnov** [comment]
Yes it should. Output is sensible now.

**Comment by KshitijT** [comment]
> In case either of you is curious about the mystery of how my phaseballs are squaring the circle, I've added you to https://github.com/o-smirnov/gmrt-reductions. (Also experimenting with hosting radiopadre HTML reports on github.io...)

Could you please add me too?

**Comment by o-smirnov** [comment]
Here's a thought though. You might want to use a bigger subset for K (perhaps full band for K, subset for G). The discretization of the K estimate is 1/bandwidth... I'll make a fix on the branch...

**Comment by o-smirnov** [comment]
OK, I'll reopen, since I want a different subset for G and K potentially.
