### ISSUE TITLE
allow filling of MODEL_DATA even when NRAO standard calibrators are used

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1206]
This else-clause: https://github.com/caracal-pipeline/caracal/blob/master/caracal/workers/crosscal_worker.py#L514 

...forces ``usescratch=False`` for NRAO standard calibrators. I'd like to be allowed ``usescratch=True`` in this case as well.

**Comment by paoloserra** [comment]
What about just changing to `usescratch=True` ? This is just the calibrators MS, we don't need to be that worried about disk space.
