### ISSUE TITLE
report error when crosscal order doesn't match combine, solint and/or calmode 

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1208]
This has bit me a few times, it's too easy to screw up when experimenting...

Please check that the lengths of the crosscal order, combine, solint and calmode sequences are the same, and throw an error if they're not. If there is a discrepancy, it can be hard to spot from just looking at the config file, and the pipeline just carries on running, with very confusing results (because calmodes/intervals/etc. end up being used at the wrong spot in the sequence...)

**Comment by paoloserra** [comment]
BTW, some of  our sample config files set `calmode = a` for `K` and `= ap` for `B`. However, I think that `calmode` is only relevant for `G`. I typically set it to an empty string for `K` and `B` and CARACal does what it should.

It would be good if somebody could confirm this. We can then change the sample config files and the documentation accordingly.

**Comment by o-smirnov** [comment]
OK this just tripped me up again. Maybe I'm just being uniquely moronic, but it really frustrates me to run a reduction for 24 hours, just to find it full of crap because I missed something so simple. I'm upping the Defcon level accordingly.

**Comment by paoloserra** [comment]
I think you're right, it's easy to make mistakes here.
