### ISSUE TITLE
Better header in the line worker

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1209]
We had a comment that the header in the line worker should carry the a cunit3 = 'm/s' header item. I am not sure about the conventions, I thought SI units are default.

**Comment by paoloserra** [comment]
That should indeed be the case. For the same reason, there is no need to have CUNIT1 and 2 as degrees.

**Comment by paoloserra** [comment]
However, if you look at the latest recommendations they state to always include units. See https://fits.gsfc.nasa.gov/fits_standard.html

**Comment by gigjozsa** [comment]
OK, then, thanks for looking this up!

**Comment by gigjozsa** [comment]
Anyone who can find the time...
