### ISSUE TITLE
Pipeline crashes randomly with 'filedescriptor out of range in select()'

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1213]
This happens on the com machines com04 and stevie. I am reducing a mosaic of 25 pointings with beautiful results if the pipeline manages to go through. It manages to perform a few steps. Experiments with using ulimit to icrease the the stack and the maximum number of filepointers are not successful. The error usually occurs when using source finding in the line worker or when using mstransform. So there is either some upper limit to the number of open files that cannot be controlled using ulimit (on that machine) or some other problem. This is with docker. Please see an example here: 

[meerhogs_se_04-02-sysinfo.txt](https://github.com/caracal-pipeline/caracal/files/4975933/meerhogs_se_04-02-sysinfo.txt)
[meerhogs_se_04-02-meerhogs_se_04_b-log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4975934/meerhogs_se_04-02-meerhogs_se_04_b-log-caracal.txt)
[meerhogs_se_04-02-meerhogs_se_04_b.yml.txt](https://github.com/caracal-pipeline/caracal/files/4975936/meerhogs_se_04-02-meerhogs_se_04_b.yml.txt)
[meerhogs_se_04-02.sh.txt](https://github.com/caracal-pipeline/caracal/files/4975937/meerhogs_se_04-02.sh.txt)

**Comment by gigjozsa** [comment]
@o-smirnov is there some hardcoded upper limit for open files on those machines?

**Comment by o-smirnov** [comment]
No, I suspect it has something to do with a select() bug/limitation that I didn't know about: https://stackoverflow.com/questions/5357445/select-max-sockets

I'll make a branch of Stimela to test a fix...

**Comment by o-smirnov** [comment]
However, for the bug to be activated, one of our workers must be opening massive amounts of files and not closing them. (Not inside a container -- rather, this happens in the Python code itself.) So that may be a bug too.

**Comment by gigjozsa** [comment]
It would be a relieve if it is not one of the packaged components. Could it be that the logfiles aren't closed?

**Comment by gigjozsa** [comment]
May make sense as I produce 25x more logfiles, so we could hit the 1024 just by doing that.

**Comment by o-smirnov** [comment]
Well, maybe you can do a little investigating... you can check what it's got open by doing ``ls -l /proc/PID/fd`` in another window while it's running...

**Comment by gigjozsa** [comment]
Indeed, many logfiles.

**Comment by gigjozsa** [comment]
[open_files.txt](https://github.com/caracal-pipeline/caracal/files/4976148/open_files.txt)

**Comment by gigjozsa** [comment]
I am now counting open files every 10s . Let's see where it goes.

**Comment by o-smirnov** [comment]
Good call, it looks like log FileHandlers for each job aren't being destroyed.

Well this too will need to be a Stimela bugfix.

**Comment by gigjozsa** [comment]
Well, just to confirm that this is happening here:
Pipeline threw that error, and I was doing:
```
while true; do ls -l /proc/ID/fd | wc >> blafilescount; sleep 10; done
cat blafilescount

...
   1023   11246  192519
   1023   11246  192519
   1023   11246  192519
      0       0       0
      0       0       0
      0       0       0
...
```
1024 is indeed the max, while I tried ever larger and larger ulimit -n

But we knew this anyway.

**Comment by o-smirnov** [comment]
Yeah 1024 is a funny additional limit in select() which has nothing to do with ulimits. 

@gigjozsa please test with the ``issue-662-663-664`` branch of Stimela and see if the problem persists.

**Comment by gigjozsa** [comment]
Hey, that went fast, thanks. Will test as soon as my series of 20 data reductions, each with one worker, has finished.
