### ISSUE TITLE
selfcal worker has hardwired local-rms=True and auto-mask settings

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1214]
Having local-rms on is particularly bad for fields with bright objects. Causes no deconvolution to be done at all.

In fact local-rms seems to have been introduced to support some exotic LOFAR fields, so having it hardwired on for MeerKAT seems a good way to keep a loaded firearm snug against one's foot.

Auto-mask should also be tunable I would say.

**Comment by paoloserra** [comment]
@o-smirnov local-rms is not hardwired to True. It uses the user settings `selfcal: image: cleanmask_localrms` (one value for each  imaging iteration).

The line you're probably worried about is https://github.com/caracal-pipeline/caracal/blob/2853f0939c3ae0be2938c63538bc0f681ed01536/caracal/workers/selfcal_worker.py#L466

However, that's only used for the 0th (a.k.a., "fake") imaging iteration when `selfcal: image: cleanmask_method[0] = sofia`. That image is only used to run SoFiA on to make an initial clean mask, to be used for the 1st "real" imaging iteration. The latter uses whatever local-rms settings the user gave with `selfcal: image: cleanmask_localrms` . The default is `False`.

Unless I'm terribly mistaken, that's what you'll see if you look at the log. That is, stop staring at the code!! ;p

**Comment by o-smirnov** [comment]
Well, the log is currently not very informative because of [The Zombie Issue That Just Would Not Resolve](https://github.com/ratt-ru/Stimela/issues/664).

I did read the docs, but missed ``cleanmask_localrms`` to be honest. I think my brain just blanked out when I saw "SOFIA" and "clean masks" in the same sentence, I just wasn't ready for that mode yet! But in retrospect the docs look to make sense.

The default may be false, but I suspect that, because ``cleanmask_localrms_window`` is not 0 by default, wsclean enables the mode anyway (at least when I run outside the pipeline, I get different results -- i.e. a shallower shittier clean -- when I have ``-local-rms-window 31`` but no ``-local-rms``). So it actually ends up being on by default -- foot, meet gun, boom!

**Comment by paoloserra** [comment]
> I suspect that, because `cleanmask_localrms_window` is not 0 by default, wsclean enables the mode anyway (at least when I run outside the pipeline, I get different results -- i.e. a shallower shittier clean -- when I have `-local-rms-window 31` but no `-local-rms`). So it actually ends up being on by default

That's surprising. That's not the behaviour for WSClean's multi-scale clean, for example. The scales are ignored if multi-scale is off.

**Comment by o-smirnov** [comment]
Yep, I agree it's not consistent behaviour, but there we have it -- I did double-check. Guess it proves that Andre is human. :P

**Comment by paoloserra** [comment]
hehe :)

**Comment by paoloserra** [comment]
@o-smirnov would you mind reviewing the `selfcal` worker change in #1215? It should address this issue.

**Comment by paoloserra** [comment]
@o-smirnov please reopen if this is still not doing what you want.

**Comment by o-smirnov** [comment]
Thanks! Sorry, I meant to finish my review but never did. Had a tab open since yesterday....
