### ISSUE TITLE
fit-spectral-pol in selfcal should be disableable

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1221]
Currently the ``-fit-spectral-pol`` switch is passed to wsclean regardless of value.

In fact the fitting mode can be disabled by omitting the switch, but we have no way of specifying this in the config. The ``img_specfit_nrcoeff`` value is passed regardless, so we always ask for fitting to be enabled.

I propose interpreting -1 as "disable". I don't know what the defaults should be -- discuss?

**Comment by KshitijT** [comment]
> I propose interpreting -1 as "disable". I don't know what the defaults should be -- discuss?

Commensurate with the channelisation defaults? It's 3 at the moment. img_specfit_nrcoeff can be 1, I guess, don't see much point fitting a second order polynomial with only three points..

**Comment by o-smirnov** [comment]
Ha well then you need to have two magic values in the schema: "disable" and "commensurate with the channelisation defaults". In the current scheme, -1 and -2 which is kind of ugly. Pity pykwalify doesn't allow the flexibility.

**Comment by KshitijT** [comment]
Hmmm. Why can't we keep the value to be 1 by default (and the user can change it according to their own recipe and proclivities)? The -1 value will act as a disable switch but do we need it to be default? WSClean anyway doesn't take primary beams for most of the telescopes, so I guess we need the fit-spectral-pol parameter?

**Comment by gigjozsa** [comment]
This is BTW relevant, I think. I have heard from data reductions where we did not produce an appropriate spectral index a data reduction. I suspect spectral index fitting with too few coefficients to be the cause.

**Comment by o-smirnov** [comment]
That's why I said "discuss"...

You don't *need* fit-spectral-pol as such. If you don't use it, then the model in each subband is independent, so it actually fits the apparent spectrum anyway. Spectral fitting provides an extra degree of regularization (and the ability to interpolate to a finer degridded spectrum), but according to Andre, sometimes it actually makes things worse...

Anyway, three separate issues here:

* we need a "disable" setting. I'll push a fix where this is -1

* maybe we may need an "auto" setting which uses number of subbands -1.

* what should be the default?

**Comment by KshitijT** [comment]
> If you don't use it, then the model in each subband is independent, so it actually fits the apparent spectrum anyway. 

What happens to the sourcelist (which is then used by crystalball) output by wsclean if we switch off the polynomial fitting?

**Comment by o-smirnov** [comment]
I have no idea, but I know how you can find out!

**Comment by paoloserra** [comment]
> we need a "disable" setting. I'll push a fix where this is -1

Isn't that simply `img_specfit_nrcoeff: 0` ?

You're fitting 0 terms, i.e., you're not fitting.

**Comment by paoloserra** [comment]
> maybe we may need an "auto" setting which uses number of subbands -1.

I'm not in favour of that. For bright sources that's fine. For faint sources that might not be. I think an auto setting is only really useful when we're really sure about what's best.

**Comment by paoloserra** [comment]
> what should be the default?

I think that the current default is OK: 3 sub-bands, 1st order fitting (2 terms). Not to be confused with the current settings in the various sample configs. Those might be more important to fine tune.

**Comment by o-smirnov** [comment]
> You're fitting 0 terms, i.e., you're not fitting.

Yeah you're right @paoloserra... I was thinking in terms of polynomial order, but of course 0 should mean no fitting. Just wonder if WSClean takes it the same way.

> What happens to the sourcelist (which is then used by crystalball) output by wsclean if we switch off the polynomial fitting?

@KshitijT I have an answer (drum roll). This happens!

```
# + An exception occured:
# + >>> Can't write component list, because you have not specified a spectral fitting method. You probably want to add '-fit-spectral-pol'.
```
:laughing:

**Comment by KshitijT** [comment]
> Just wonder if WSClean takes it the same way.

It probably becomes unduly excited and starts complaining..

> @KshitijT I have an answer (drum roll). This happens!

```
# + An exception occured:
# + >>> Can't write component list, because you have not specified a spectral fitting method. You probably want to add '-fit-spectral-pol'.
```
Yeah, then let's not switch off the polynomial fitting by default or we are going to run into trouble a little bit down the road..

**Comment by o-smirnov** [comment]
OK, well the consensus seems to be, use 0 to indicate no fitting, leave the current default of 2 terms, and don't bother with any fiddly auto modes.

**Comment by paoloserra** [comment]
So I've just tried to run CARACal (master) fitting 0 terms. It runs through with no problems and does not save a source list. Not sure about the exception reported by @o-smirnov . Was that a different WSClean than the one we have in CARACal?

**Comment by o-smirnov** [comment]
> Was that a different WSClean than the one we have in CARACal?

No, it's my branch of Caracal where I don't pass any ``-fit-spectral-pol`` argument to WSClean if the value is 0 in the config file. It then throws that exception, unless I take out ``-savesourcelist`` as well.

By our logic above, ``-fit-spectral-pol 0 -savesourcelist`` ought to be an error too, so I have no idea what's happening there.

**Comment by paoloserra** [comment]
**EDIT** I take it back. I got tricked by the 0th image (the one used to make a clean mask but not to selfcalibrate) because in there we have hardcoded  `savesourcelist: False`. As soon as I start with the real imaging I get your same error. So that needs to be fixed. In fact, it might be the only thing that needs changing?

**Comment by o-smirnov** [comment]
Yeah I'll make a PR.

**Comment by IanHeywood** [comment]
> (and the ability to interpolate to a finer degridded spectrum)

Does this actually work now? I thought crystalball was motivated by wsclean being unable do this...

**Comment by paoloserra** [comment]
I think @o-smirnov meant that if you haven't fit a polynomial then other software (e.g., crystalball) doesn't know what to interpolate.

**Comment by o-smirnov** [comment]
I think WSClean *will* interpolate if you have -channels-out set higher than -deconv-channels, but there's only so far you can push it before you run out of RAM...

**Comment by paoloserra** [comment]
Not gonna work when we're talking 1000's of channels-out indeed. I think I've tried it and it didn't end well.
