### ISSUE TITLE
Use SoFIA mask as an input to define channels excluded from contsub in mstransform section

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1224]

**Comment by paoloserra** [comment]
If you have a SoFiA mask you should also have a SoFiA catalogue. The catalogue can already be used to do exactly what you are interested in. See the `uvlin` section in https://caracal.readthedocs.io/en/latest/manual/workers/line/index.html#mstransform and, in particular, the parameters `exclude_known_sources`, `known_sources_cat`, `known_sources_radius`, `known_sources_flux` and `known_sources_dv`. All you will need to do is some slight re-formatting of the SoFiA catalogue to follow the convention explained under `known_sources_cat` in the documentation.
