### ISSUE TITLE
Running CARACal jobs on Slurm

### ISSUE THREAD

**Issue by KshitijT** [caracal-pipeline/caracal#1226]
Recently the slurm cluster has been upgraded and anaconda has been removed from everyone's path.

So, if you are using a virtualenv made before this (say anytime before the past couple of weeks), you are likely to face this error:

```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f49a1c38740 (most recent call first):
/var/lib/slurm/slurmd/job08208/slurm_script: line 19: 22259 Aborted                 (core dumped) caracal -c 3C403_source.yml -ct singularity -sid /scratch/users/kshitij/STIMELA_IMAGES_NEW/
```

To resolve this issue, please remake your virtualenv while ensuring that the python version is the same as slurm (especially, if like me, you had made the previous environment on Whiplash or some other node like that). In the new virtualenv, install CARACal as usual and the error should go away.

**Comment by HaoChen-ast** [comment]
I meet the same problem.

During remaking the virtualenv `module load anaconda3` should be loaded before `pip install -U pip setuptools wheel` to install the correct version of **pip** & **setuptools**.
After re-installation, the new virtualenv will work.

**Comment by Jordatious** [comment]
Thanks @KshitijT. Yes, it'd be best to build the virtualenv on a compute node with anaconda3, using `module load anaconda3`, as @HaoChen-ast has mentioned. This may have been one reason for some of the previous issues.

@KshitijT, can you make a version available at `/software/astro/caracal/`?

P.S. Is there some way to follow an issue without commenting on it?

**Comment by KshitijT** [comment]
> @KshitijT, can you make a version available at /software/astro/caracal/?

Will do.

> P.S. Is there some way to follow an issue without commenting on it?

I can assign it to you. ;)

**Comment by KshitijT** [comment]
This is covered in the main page instructions.
