### ISSUE TITLE
misleading selfcal message: "INFO: Number of iterations reached: 2"

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1228]
Cosmetic I know, but the past tense suggests something has taken place, when in fact this message is printed at the **start** of a selfcal loop. No matter how many times I've seen it, I still get an "oh shit, reached already, something must be wrong" moment. Perhaps "to be done" rather than "reached"?

**Comment by KshitijT** [comment]
Fixed by #1256.
