### ISSUE TITLE
changing calibrators in obsconf has no effect because summary.json needs to be regenerated

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1233]
I've been a bit too clever in changing the code to generate the summary.json file only when it doesn't exist yet.

If one changes the calibrator settings in the ``obsconf`` section, summary.json needs to be regenerated, because that's where the calibrator choices are stored. At the moment one has to remove the file by hand for the changes to take effect.

In passing, I note that @SpheMakh default setting of "longest" made for an incorrect bpal/fcal selection on @KshitijT 4C12.03 data, selecting the secondary for bpcal/fcal. Perhaps this is simply due to the bpcal scan intent being set to 'UNKNOWN" in this MS.

```
2020-09-03 16:19:59 CARACal INFO:     4C12.03 (ID=2) : 59.87 minutes | RA=2.47 deg, Dec=12.73 deg
2020-09-03 16:19:59 CARACal INFO:     J0022+0014 (ID=1) : 11.83 minutes | RA=5.61 deg, Dec=0.25 deg
2020-09-03 16:19:59 CARACal INFO:     PKS1934-63 (ID=0) : 9.86 minutes | RA=294.85 deg, Dec=-63.71 deg
```

**Comment by o-smirnov** [comment]
And as requested by @paoloserra, add the colnames of the MS to the summary object.

**Comment by o-smirnov** [comment]
> And as requested by @paoloserra, add the colnames of the MS to the summary object.

@paoloserra: I'm looking, but this is not a Caracal issue really but an msutils one, so we need to bribe @SpheMakh.

Do you still need it, given your newly-discovered abilities for using casacore directly?

On a related note (back to this issue), should I add an error for when ``bpcal`` or ``gcal`` fails to configure automatically? Pros: alert the user of the problem early, rather than letting them get all the way to crosscal before having to restart. Cons: what if they're running some weird setup without a ``bpcal`` -- is this even possible?

Maybe I should produce an error if it's not empty. If the user really wants to run without a bpcal, let them set ``bpcal: ''`` explicitly.

**Comment by KshitijT** [comment]
> On a related note (back to this issue), should I add an error for when bpcal or gcal fails to configure automatically?

For MeerKAT BPCAL we do have a list which is pretty short. Can't we just cross-match the coordinates (I think we already do this somewhere) and change the intent / set bpcal manually?

**Comment by o-smirnov** [comment]
Seems like the sort of clever that can easily be too clever... can you draw a simple flowchart?

**Comment by paoloserra** [comment]
> > And as requested by @paoloserra, add the colnames of the MS to the summary object.
> 
> @paoloserra: I'm looking, but this is not a Caracal issue really but an msutils one, so we need to bribe @SpheMakh.
> 
> Do you still need it, given your newly-discovered abilities for using casacore directly?

In the long run it'd be nice to have it in the summary.json, which would indeed require bribing @SpheMakh .

Meanwhile, I can add it to the INFO printed to terminal.

**Comment by KshitijT** [comment]
> Seems like the sort of clever that can easily be too clever... can you draw a simple flowchart?

Sorry, can't do, but here is a mildly complicated flowchart instead:
![Untitled Diagram (1)](https://user-images.githubusercontent.com/9251962/94993121-02c72580-058f-11eb-8ecc-3de97ee8f379.png)

This should present a unified framework relevant to #1233, #1203, #1049.

**Comment by KshitijT** [comment]
N.B. The flowchart is very specific to MeerKAT issues but can be generalised; I note GMRT measurement sets sometimes don't specify intents too.
