### ISSUE TITLE
ENOLCK error at ILIFU

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1239]
I see lots of lines like this in the CARACal log at  ILIFU. It doesn't seem to be doing much damage, but still... Does anybody know what it is?

```
*** The ENOLCK error was returned by the kernel.
*** It usually means that a lock for an NFS file could not be
*** obtained, maybe because the statd or lockd daemon is not running.
*** The ENOLCK error was returned by the kernel.
*** It usually means that a lock for an NFS file could not be
*** obtained, maybe because the statd or lockd daemon is not running.
```

**Comment by KshitijT** [comment]
Not seen it before.

**Comment by o-smirnov** [comment]
I think we need to ask @Jordatious. Looks like some kind of glitch on the shared filesystem.

**Comment by Jordatious** [comment]
Sorry, I was the one who pointed Paolo to this and said we're not sure what it is.

**Comment by o-smirnov** [comment]
Full circle then...

**Comment by paoloserra** [comment]
I no longer see this.
