### ISSUE TITLE
Obsolete keyword report in flag worker?

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1241]
https://github.com/caracal-pipeline/caracal/blob/abade14b42c761e16506b8002f442ee5a80ea9d8/caracal/schema/flag_schema.yml#L422-L426

I do not see where this is still being used. The flagging summary is generated anyway if summary is True (which is true by default):

https://github.com/caracal-pipeline/caracal/blob/6021afe0c880d7678869bbc3c515d1f3b59b3119/caracal/workers/flag_worker.py#L507-L527

**Comment by paoloserra** [comment]
We've got `summary`, `inspect` and `report`. I agree with you that `report` is not being used and could be removed.

**Comment by o-smirnov** [comment]
Aha, I missed that. It is being used, it's a universal keyword that is recognized for every worker: https://github.com/caracal-pipeline/caracal/blob/master/caracal/workers/worker_administrator.py#L409

**Comment by o-smirnov** [comment]
It determines when to re-generate the HTML reports from the notebooks. Normal behaviour is to only do it at the end of the pipeline, but you can force the report to be regenerated after any given worker using this keyword.
