### ISSUE TITLE
need stimela 1.6.7 at ilifu

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1243]
We need the Stimela 1.6.7 images at ilifu at /software/astro/caracal

Can somebody please remind me the procedure to do this, or do it?

@KshitijT @molnard89

**Comment by KshitijT** [comment]
> We need the Stimela 1.6.7 images at ilifu at /software/astro/caracal
> 
> Can somebody please remind me the procedure to do this, or do it?
> 
> @KshitijT @molnard89

There is nothing to it; one needs to pull the corresponding singularity images somewhere and scp them to the /software/astro/caracal in a separate folder (we all have access to the shared area). Let me know if you would like me to do it.

**Comment by paoloserra** [comment]
pulling goes as explained in the caracal readme?

**Comment by paoloserra** [comment]
I'm afraid the only environment where I have Singularity is ilifu itself -- elsewhere I have Docker only. I guess this means I cannot do this myself?

**Comment by KshitijT** [comment]
> I'm afraid the only environment where I have Singularity is ilifu itself -- elsewhere I have Docker only. I guess this means I cannot do this myself?

Ah, yes. Let me give it a shot.

**Comment by IanHeywood** [comment]
You can pull stimela's containers with singularity, e.g.

```
$ singularity pull docker://stimela/cubical:1.5.4
```

This used to work on the login node but singularity has (wisely) been blocked there now. Easiest way is to book a part of a node with `salloc`, e.g. 

```
$ salloc --time=06:00:00 --partition=Main --ntasks=1 --nodes=1 --cpus-per-task=4 --mem=8GB
```

and then use that to pull the containers. This used to work well, I haven't tried it for a while since I've just been hijacking your container folders...

**Comment by KshitijT** [comment]
The issue with pulling images on ilifu was that it used to be extremely slow, definitely longer than 6 hours (almost as slow as pybdsf on Stimela!), but I haven't tried using the method you have mentioned above - maybe it would be faster than pulling it from Whiplash like olden times?

**Comment by paoloserra** [comment]
but that's one image at a time?

**Comment by IanHeywood** [comment]
I just ran the above `salloc` command and then [this](https://github.com/IanHeywood/oxkat/blob/master/tools/pull_containers.sh) (probably somewhat out of date) list of container pulls. It's taking 2-3 minutes per container it seems:

```
$ ls -lh *sif
-rwxr-xr-x 1 ianh idia-group 1.3G Sep 17 18:19 casa_1.2.6.sif
-rwxr-xr-x 1 ianh idia-group 718M Sep 17 18:22 cubical_1.5.4.sif
```

**Comment by KshitijT** [comment]
Cool, that's definitely way faster than pulling from Whiplash. I'll set it up and see how that goes.

**Comment by IanHeywood** [comment]
Maybe whiplash needs renaming... 🤔

**Comment by paoloserra** [comment]
Thanks @IanHeywood , but do we then need to maintain an updated list of images that need to be pulled? Or I am missing something  :(

**Comment by paoloserra** [comment]
I guess my point is that for CARACal we probably need the whole (or most) of stimela, not just a few selected images?

**Comment by IanHeywood** [comment]
I think if you omit the version number it might just download the latest one, but I'm not too sure.

**Comment by IanHeywood** [comment]
Updated timestamps....

```
$ ls -lh *sif
-rwxr-xr-x 1 ianh idia-group 1.3G Sep 17 18:19 casa_1.2.6.sif
-rwxr-xr-x 1 ianh idia-group 718M Sep 17 18:22 cubical_1.5.4.sif
-rwxr-xr-x 1 ianh idia-group 1.6G Sep 17 18:33 ddfacet_0.5.3.1.sif
-rwxr-xr-x 1 ianh idia-group 1.8G Sep 17 18:44 killms_2.7.0.sif
-rwxr-xr-x 1 ianh idia-group 362M Sep 17 18:45 meqtrees_1.2.4.sif
-rwxr-xr-x 1 ianh idia-group 880M Sep 17 18:45 ragavi_1.2.6.sif
-rwxr-xr-x 1 ianh idia-group 606M Sep 17 18:48 shadems_1.7.0.sif
```

DDFacet and killMS took about 11 minutes each. Everything else seems to be very fast.

**Comment by KshitijT** [comment]
Ok, I tried to be clever and just make an sbatch file for a stimela pull (nothing fancy) - shadems took about 10 minutes to go through - I am going to see what's the average time for a few more images before deciding whether to kill the job or not..

**Comment by KshitijT** [comment]
Update - shadems and astropy took 10 minutes or more, other three images took less than 5 minutes. Being super lazy, I have decided to leave the job running - at this speed, it should not take more than 4-5 hours. Is that ok @paoloserra ?

**Comment by paoloserra** [comment]
of course, and thanks! you're putting them at /software/astro/caracal already?

**Comment by KshitijT** [comment]
> of course, and thanks! you're putting them at /software/astro/caracal already?

No, but I'll put it there once all the images are pulled. You can thank STIMELA_PULLFOLDER for that...

**Comment by paoloserra** [comment]
@KshitijT I'm waiting for the new Stimela images before starting new Fornax tests at ILIFU. Our reserved nodes are idle so please let me know as soon as they are available. Thanks for your understanding.

It would be nice to post at https://github.com/caracal-pipeline/caracal/wiki detailed instructions on how to update the Stimela images at ILIFU for the purpose of running  CARACal. Then anybody could do it and I would stop bugging you. :)

**Comment by KshitijT** [comment]
Sorry for the delay, @paoloserra. For benchmarking reference, it took 4 hours 30 minutes. The stimela images for 1.6.7 are in  /software/astro/caracal/STIMELA_IMAGES_1.6.7 now. Please check and confirm. 

I'll add the detailed instructions at https://github.com/caracal-pipeline/caracal/wiki.

**Comment by paoloserra** [comment]
Thank you so much @KshitijT

**Comment by paoloserra** [comment]
and yes, I can see them now

**Comment by KshitijT** [comment]
I have added the instructions at: https://github.com/caracal-pipeline/caracal/wiki/Update-Stimela-images-on-ILIFU.
N.B. Step 8 is absolutely crucial for correctly updating the images.
