### ISSUE TITLE
mosaic worker

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1258]
Could someone please post parameters of the mosaic worker? I could not find it in the default config file. Thanks.

**Comment by svw26** [comment]
Read the docs! :) https://caracal.readthedocs.io/en/latest/manual/workers/mosaic/index.html x

**Comment by viralp** [comment]
Thanks Sarah. Actually I want the mosaic schema to include in the config file.

**Comment by o-smirnov** [comment]
You mean like a sample config to build from? There's this: https://github.com/caracal-pipeline/caracal/blob/master/caracal/sample_configurations/mosaic_basic_config.yml, but arguably it is a little simplistic...

**Comment by viralp** [comment]
Yes Oleg, thanks.
