### ISSUE TITLE
crosscal: apply_cal: applyto ignores xcal

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1264]
Can probably be fixed in the add_polcal branch?

**Comment by francescaLoi** [comment]
xcal has been added to the apply_cal list in crosscal in the add_polcal branch. Parang is set to False to avoid double parang correction if one decides to split the calibrators after crosscal and before polcal since in polcal parang=True. Hope this is ok for you.

**Comment by o-smirnov** [comment]
Is this a recent change on the ``add_polcal`` branch?
