### ISSUE TITLE
Is the "dot" in output/.logo really necessary?

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1277]
On ILIFU, having hidden files/directories like `output/.logo` is making it difficult to handle permissions in shared folders. We can of course continue looking for a solution, but removing the "dot" would save us time.

**Comment by o-smirnov** [comment]
I was just being shy and trying to hide my artwork. But ILIFU wants me to be all millennial about it, sure... I'll fix it together with #1167.

**Comment by svw26** [comment]
This coming from the guy who described himself as "The Inimitable Oleg Smirnov" :) x
http://www.ast.uct.ac.za/ast/meetings-workshops/3gc4/participants

**Comment by paoloserra** [comment]
In fact, he was being pretty humble there.

**Comment by o-smirnov** [comment]
Hehe, pretty sure it wasn't me. I blame one of my unsuccessful would-be imitators.

My modesty is only eclipsed by my inimitability!

**Comment by svw26** [comment]
The plot thickens x

**Comment by KshitijT** [comment]
> Hehe, pretty sure it wasn't me. I blame one of my unsuccessful would-be imitators.

I am Spartacus... erm Oleg Smirnov !
![download (1)](https://user-images.githubusercontent.com/9251962/98233817-391a0b00-1f68-11eb-9309-21d12fbd36f7.jpeg)

**Comment by o-smirnov** [comment]
I don't sing my praises outside of karaoke bars...
