### ISSUE TITLE
Allowing ragavi to render gain plot reports in png too

### ISSUE THREAD

**Issue by molnard89** [caracal-pipeline/caracal#1279]
Currently ragavi only produces plotgain png's in the crosscal worker, if the html report is too large in size (see https://github.com/ratt-ru/ragavi/blob/0bef87257ce8484191230eebd9f813ef6d3d42bd/ragavi/ragavi.py#L2196-L2206). Since it only happens for bandpass reports in our 32k data, and we would like to include png figures of all gain solutions for our internal MFS reports, we thought about adding a manual option to save gain plots in png. I made a branch (plotgainPNG) that does this, but it invalidates previous config files, because instead of 

```
plotgains: true
```

it requires

```
plotgains:
  enable: true
  savepng: true
```

There are two alternative solutions to keep things backwards compatible:

1) just hardcode that ragavi always makes a png alongside the html report. It doesn't add significant computational or storage overhead, so I think it should be fine
2) add the savepng option to the config like this
```
plotgains: true
savepng: true
```
but this is not consistent with how we structure the rest of the config files and isn't very userfriendly to interpret.

What do you think is the best way to implement this?

**Comment by paoloserra** [comment]
I would always make both HTML and PNG plots (your option 1 above).

**Comment by molnard89** [comment]
Seconded, I think the pngs take up negligible extra storage and processing time, and it's important to not wreck previously working config files.

**Comment by paoloserra** [comment]
@molnard89 I think this is a case of tacit agreement. Can you put this change in a new PR?

**Comment by molnard89** [comment]
@paoloserra aye aye captain

**Comment by paoloserra** [comment]
https://github.com/caracal-pipeline/caracal/pull/1281
