### ISSUE TITLE
crosscal needs to export multiple sets of caltables

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1280]
Ran into this with @francescaLoi when working on polcal. 

Crosscal currently produces a single set of caltables listed in its output json file, like so:

```
{"transfer_fluxscale": {"caltable": "full_bw_test-1600463770_sdp_l0-1kgb_secondary.F0", "fldmap": "nearest", "interp": "nearest"}, 
"delay_cal": {"caltable": "full_bw_test-1600463770_sdp_l0-1kgb_primary.K2", "fldmap": "nearest", "interp": "nearest"}, 
"bp_cal": {"caltable": "full_bw_test-1600463770_sdp_l0-1kgb_primary.B1", "fldmap": "nearest", "interp": "linear"}}
```

The meaning of this is: this is the set of KGB tables one must apply to the target to get the "best" corrected data.

@francescaLoi then reads this json file inside the polcal worker to figure out which KGB tables to apply to the xcal. 

The problem now is the following: once polcal is done, inside the polcal worker, we want to apply KGB+polcal to the primary field too, as a diagnostic -- to make sure the phaseballs come out right. However, the above KGB set is not appropriate to the primary, since for the primary we have better KG solutions. The result is this:

![image](https://user-images.githubusercontent.com/6470079/98956707-05f7ee80-2509-11eb-8e9e-d45d44989a6a.png)

Clearly, it must apply KG from the primary instead. However, the polcal worker doesn't know anything about the primary KG tables, since they're not contained in the json file coming out of crosscal.

Proposed solution: have crosscal add a second key to the output dict, listing the tables appropriate to the primary.

Even better: have this dict use field names for keys, with the field now called ``transfer_fluxscale`` named ``default`` instead. The logic on the consumer side should be: if I want to apply solutions to a field, I will first look in the dict by field name, and if I find nothing, I will use the ``default`` set of tables instead.

Even better: dump JSON and make it human-friendly YML instead. Then the user can at least edit the tables as needed. If you're going to give plenty of rope, better that it's velvet rope, right?

**Comment by francescaLoi** [comment]
This is the syntax used for the callib files in casa: https://casa.nrao.edu/casadocs/casa-5.1.0/reference-material/cal-library-syntax
I think we could simply include all the caltables in the callib files (also the polcal solutions are not the same for all of the calibrators) adding the "field" keyword which specified over which fields the caltable has to be applied. 

I am wondering if it could be better to directly write a txt file...

**Comment by o-smirnov** [comment]
But then we would need to add some code to read the text file too (assuming we need this info inside the worker, i.e. it's not just a black box to be given to CASA). It's very easy to save and load yaml, and also very easy to write out txt, but reading txt is unnecessary complexity.

**Comment by francescaLoi** [comment]
Even if we need to solve this (and probably the additional key would be the best solution) I just want to say that there's a way to avoid this issue in the `add_polcal` branch. 
Following the meerkat-fullStokes-continuum-defaults.yml sample configuration, we have to split the kgb corrected calibrators after crosscal. Obviously applycal in crosscal have to be enabled and all the cal fields have to be included (in the branch this issue #1264 has been fixed, xcal is not ignored). Afterwards we can pol calibrate without applying kgb corrections otf (`otfcal` False).

**Comment by o-smirnov** [comment]
Is anybody particularly attached to the current callib structure? It is not fit for purpose. Time to kill and rewrite.

**Comment by paoloserra** [comment]
as long as it continues doing its job for unsophisticated non-pol souls like me

**Comment by o-smirnov** [comment]
You may not be interested in the polarization, but the polarization is interested in you...

**Comment by paoloserra** [comment]
you give me terrible news

**Comment by o-smirnov** [comment]
Nah should be ok. We'll test before we merge, like we always do ;).

**Comment by paoloserra** [comment]
@o-smirnov is this issue attached to #1217 ?
