### ISSUE TITLE
UVLIN channel selection is relative to the channel grid of the input MS

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1282]
The `line` worker uses CASA `mstransform` to run simultaneously UVLIN continuum subtraction and Doppler correction on an input MS. See `line: mstransform: uvlin` and `line: mstransform: doppler`.

For the purpose of continuum subtraction, users can set which line-free channels to include in the fit with `uvlin: fitspw`.

A doubt I have had for a while is whether, in case of simultaneous Doppler correction, `uvlin: fitspw` is relative to the channel grid of the input MS or to that of the output, Doppler-corrected MS. 

Based on the following test I've decided that `uvlin: fitspw` refers to the channel grid of the input MS. "Line people" please read along and let me know whether you agree. If so, I think that this information should be included in our documentation.

I have an input MS with 100 channels. If I set `uvlin: fitspw: '0:0~99'` with no Doppler correction everything works just fine. If I set `uvlin: fitspw: '0:0~100'` with no Doppler correction`mstransform` complains that the channel selection for the UVLIN fit is not valid and corrects it.

```
# 2020-11-14 12:43:16	INFO	UVContSubTVI::parseConfiguration	Fit order is 1
# 2020-11-14 12:43:16	INFO	UVContSubTVI::parseConfiguration	Line-free channel selection is 0:0~100
# 2020-11-14 12:43:16	INFO	UVContSubTVI::parseConfiguration	Using denoising lib (GSL based)
# 2020-11-14 12:43:16	WARN	MSSpw Expression parser::MSSpwIndex::convertToChannelIndex (file ../../ms/MSSel/MSSpwIndex.cc, line 439)	Channel 100 out of range for SPW 0 (valid range 0~99). Limiting it to be within the available range.
```

This establishes that `mstransform` does check whether the line-free channel selection is valid.

I've then set up Doppler correction to create an output MS with 60 channels. Also in this case `mstransform` complains when `uvlin: fitspw: 0:0~100'` but not when `uvlin: fitspw: 0:0~99'`.

I think that this establishes that `uvlin: fitspw` is relative to the channel grid of the input MS and not to that of the output, Doppler-corrected MS.

It also means that `mstransform` operates as follows:
- read in a visibility spectrum;
-  run UVLIN continuum subtraction;
-  Doppler correct;
-  write the spectrum to the output MS.

Let me know whether you have comments on this.

**Comment by edeblok** [comment]
I have a 1000 channel ms, with uvlin channels `fitspw: '0:0~199;800~999'`. `mstransform` produces a 997-channel ms after doppler correction, but doesn't complain about the mismatch in number of channels. So either it's subtracting before doppler, or it's doing something very clever under the hood. 
`MSTransformManager::regridSpwAux        Output SPW:   997 channels`
`UVContSubTVI::parseConfiguration        Line-free channel selection is 0:0~199;800~999`

**Comment by edeblok** [comment]
Confirmed by CASA itself, see [https://casa.nrao.edu/casadocs/casa-5.4.1/uv-manipulation/manipulating-visibilities-with-mstransform](url)
where the order is listed. Step 5 is "UV continuum subtraction", and Step 9 is "Spectral regridding and reference frame transformation".

**Comment by paoloserra** [comment]
:)  I really should learn to read documentation!!!
