### ISSUE TITLE
Corr selection not pased to Shadems when iterating over fields

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1285]
The following request for 4 by-field plots in the CARACal config (XXph-freq, YYph-freq, XXam-freq, YYam-freq)

```
2020-11-20 16:34:44 CARACal INFO:     shadems:
2020-11-20 16:34:44 CARACal INFO:       enable:                       True
2020-11-20 16:34:44 CARACal INFO:       default_column:               DATA
2020-11-20 16:34:44 CARACal INFO:       plots_by_field:               -x FREQ   -y phase --corr XX, -x FREQ   -y phase --corr YY, -x FREQ   -y amp  --corr XX, -x FREQ   -y amp  --corr YY
2020-11-20 16:34:44 CARACal INFO:       plots_by_corr:                [""]
2020-11-20 16:34:44 CARACal INFO:       plots:                        [""]
2020-11-20 16:34:44 CARACal INFO:       ignore_errors:                True
```

results in the following 4 runs of shadems, where the corr selection is ignored

```
# 2020-11-20 15:10:31: Running shadems /stimela_mount/msdir/1604775670_sdp_l0-cal.ms -x FREQ -y phase --corr XX,YY --title '{ms} {_field}{_Spw}{_Scan}{_Ant}{_title}{_Alphatitle}{_Colortitle}' --col DATA --png pre_1gc1-1604775670_sdp_l0-cal-{field}{_Spw}{_Scan}{_Ant}-{label}{_alphalabel}{_colorlabel}{_suffix}-corr-XX-YY.png --iter-field  --field J1939-6342,J0440-4333
...
# 2020-11-20 15:12:48: Running shadems /stimela_mount/msdir/1604775670_sdp_l0-cal.ms -x FREQ -y phase --corr XX,YY --title '{ms} {_field}{_Spw}{_Scan}{_Ant}{_title}{_Alphatitle}{_Colortitle}' --col DATA --png pre_1gc1-1604775670_sdp_l0-cal-{field}{_Spw}{_Scan}{_Ant}-{label}{_alphalabel}{_colorlabel}{_suffix}-corr-XX-YY.png --iter-field  --field J1939-6342,J0440-4333
...
# 2020-11-20 15:15:01: Running shadems /stimela_mount/msdir/1604775670_sdp_l0-cal.ms -x FREQ -y amp --corr XX,YY --title '{ms} {_field}{_Spw}{_Scan}{_Ant}{_title}{_Alphatitle}{_Colortitle}' --col DATA --png pre_1gc1-1604775670_sdp_l0-cal-{field}{_Spw}{_Scan}{_Ant}-{label}{_alphalabel}{_colorlabel}{_suffix}-corr-XX-YY.png --iter-field  --field J1939-6342,J0440-4333
...
# 2020-11-20 15:17:07: Running shadems /stimela_mount/msdir/1604775670_sdp_l0-cal.ms -x FREQ -y amp --corr XX,YY --title '{ms} {_field}{_Spw}{_Scan}{_Ant}{_title}{_Alphatitle}{_Colortitle}' --col DATA --png pre_1gc1-1604775670_sdp_l0-cal-{field}{_Spw}{_Scan}{_Ant}-{label}{_alphalabel}{_colorlabel}{_suffix}-corr-XX-YY.png --iter-field  --field J1939-6342,J0440-4333
```

I'm guessing Shadems is fine, and this is a bug in the way we pass arguments to Shadems in CARACal's `inspect` worker.

**Comment by o-smirnov** [comment]
I used to be clever about this, but @Mulan-94 didn't carry this across in her refactoring. My code is clearly too twisted for my collaborators to appreciate. :P

@Mulan-94: there used to be this statement here which accomplished exactly this: https://github.com/caracal-pipeline/caracal/blob/v1.0.3/caracal/workers/inspect_worker.py#L230

Its point was to propagate things from the dict of options into the command line, but only if they were not already there. So in @paoloserra's case, the corr variable would not be propagated into the command line.

**Comment by francescaLoi** [comment]
I am afraid there's still something weird with `inspect`.
I want to make plots only for the bpcal field but even with this parset:
`inspect:
  enable: true
  label_plot: par1
  dirname: par1
  standard_plotter: none
  field: 'bpcal'
  correlation: 'all'
  report: True
  shadems:
    enable: true
    ignore_errors: true
    plots_by_corr:
      - "-x FREQ   -y phase"
      - "-x FREQ   -y amp "
      - "-x real   -y imag "
      - "-x phase   -y amp "
`
it tries to make plots for all the fields together:
`# 2020-11-25 10:13:50 - shadems - INFO - ------------------------------------------------------
# 2020-11-25 10:13:50 - shadems - INFO - : Data selected for plotting:
# 2020-11-25 10:13:50 - shadems - INFO - Antenna(s)       : all
# 2020-11-25 10:13:50 - shadems - INFO - Baseline(s)      : all except autocorrelations
# 2020-11-25 10:13:50 - shadems - INFO - Field(s)         : all
# 2020-11-25 10:13:50 - shadems - INFO - SPW(s)           : all
# 2020-11-25 10:13:50 - shadems - INFO - Scan(s)          : all
# 2020-11-25 10:13:50 - shadems - INFO - Channels         : all
# 2020-11-25 10:13:50 - shadems - INFO - Corr/Stokes      : XX
# 2020-11-25 10:13:50 - shadems - INFO - ------------------------------------------------------
`

**Comment by Mulan-94** [comment]
Hi @francescaLoi 
could you please try this:
```
shadems:
    enable: true
    ignore_errors: true
    plots_by_corr:
      - "-x FREQ   -y phase --field {bpcal}"
      - "-x FREQ   -y amp --field {bpcal}"
      - "-x real   -y imag --field {bpcal}"
      - "-x phase   -y amp --field {bpcal}"
```
There are two types of plots in inspect. The older "mainstream" plots and the new `shadems` plots. The `field` argument only works for the older plots it seems. I'm checking on it

**Comment by o-smirnov** [comment]
Arguably, it should work for the new plots as well. They do honour the top-level ``correlation`` setting, right? So it would be logical to honour ``field`` too.

**Comment by Mulan-94** [comment]
Yeap you're right

**Comment by francescaLoi** [comment]
It's working correctly now, thanks. Sorry if I deleted the comment but I realized that I was on `add_polcal` and I was not sure that your changes were already there but they are.

**Comment by paoloserra** [comment]
closed via https://github.com/caracal-pipeline/caracal/pull/1287
