### ISSUE TITLE
More additions (!!!) to the selfcal worker

### ISSUE THREAD

**Issue by KshitijT** [caracal-pipeline/caracal#1309]
As requested by @o-smirnov  (please **do** let me know if I lost something in translation - and thanks @paoloserra for reminding me):

Essentially we need a mode where delay-cal , phase-cal and amplitude-phase cal are all available at different points of the calibration process; to "solve for delays, gain phase and amplitude in one go" . 

My first instincts towards arriving at a solution all point to burning down the selfcal worker and writing it again from scratch. Just kidding ! (Not really). 

Will document progress (or lack thereof) in this issue.

**Comment by paoloserra** [comment]
> My first instincts towards arriving at a solution all point to burning down the selfcal worker and writing it again from scratch. Just kidding ! (Not really).

be my guest!

**Comment by o-smirnov** [comment]
Burn baby burn! :fire:

All good code needs at least two good rewrites, and the current incarnation looks pretty Gothic... That which kills you only makes you stronger, as a Romanian colleague used to say.

**Comment by KshitijT** [comment]
> That which kills you only makes you stronger, as a Romanian colleague used to say.

Don't you mean a _Polish_ colleague ? :P

**Comment by PeterKamphuis** [comment]
> Essentially we need a mode where delay-cal , phase-cal and amplitude-phase cal are all available at different points of the calibration process; to "solve for delays, gain phase and amplitude in one go" .

On different time/frequency intervals?

Rewriting the whole thing is probably a good idea as likely anything that I wrote into it was probably crappy python code.

**Comment by KshitijT** [comment]
> On different time/frequency intervals?

Yes, that too, thanks for reminding. Seriously, I get nostalgic about the lists we used to have per selfcal iteration in which to specify everything - while not as elegant as the current setup, it was very flexible.

**Comment by KshitijT** [comment]
Quartical will be here when it'll be here. ;)
