### ISSUE TITLE
f-slope gain type

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1318]
Hi there,

I am trying to use the `f-slope` in the `gain_matrix_type` of cubical (selfcal worker) but getting the following error -

`2021-03-25 18:45:52 CARACal ERROR: ValueError: f-slope is not a viable matrix_type`

Could anyone please check this? Thanks in advance!

Cheers,
Viral

**Comment by KshitijT** [comment]
Are you using "f-slope" or "Fslope" ?
Please see the schema: https://github.com/caracal-pipeline/caracal/blob/master/caracal/schema/selfcal_schema.yml#L513

**Comment by viralp** [comment]
Ok thanks @KshitijT, it works now.
