### ISSUE TITLE
ddcal worker - DDFacet error: IndexError: index 819 is out of bounds for axis 1 with size 819

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1321]
Hi,

I am getting a similar error reported in #950.
```
#   File "/usr/local/bin/DDF.py", line 453, in <module>
#     main(OP, messages)
#   File "/usr/local/bin/DDF.py", line 287, in main
#     Imager.main()
#   File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 1171, in main
#     FacetMachine=self.FacetMachine, BaseName=self.BaseName)
#   File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/HOGBOM/ClassImageDeconvMachineHogbom.py", line 117, in Init
#     weights=kwargs["PSFVar"]["WeightChansImages"], PSFServer=self.PSFServer)
#   File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/HOGBOM/ClassModelMachineHogbom.py", line 74, in setFreqMachine
#     self.FreqMachine.set_Method()
#   File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassFrequencyMachine.py", line 132, in set_Method
#     self.S[iChannel, ind] = 1.0/nchunk
# IndexError: index 819 is out of bounds for axis 1 with size 819
```
I also upgraded stimela to 1.6.9.
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/6303699/log-caracal.txt)

**Comment by KshitijT** [comment]
@viralp , I don't think this is the same error.

Could you please append the ddfacet log (it's probably in the 3GC folder in the output directory) ?

**Comment by viralp** [comment]
Here is the ddfacet log file
[mypipelinerun_ABELL2631-DD-precal.log](https://github.com/caracal-pipeline/caracal/files/6304572/mypipelinerun_ABELL2631-DD-precal.log)

**Comment by o-smirnov** [comment]
@SpheMakh please roll another DDFacet image.

**Comment by bennahugo** [comment]
0.6.0 is not released yet - there is a large remaining issue in hogbom that has to be fixed

**Comment by bennahugo** [comment]
You can use the stimela ddfacet-060 branch. The images work, I'm just finetuning an acceptance test for this. I'm going to go ahead and close the ticket.
