### ISSUE TITLE
wrong mask name in ddcal worker

### ISSUE THREAD

**Issue by francescaLoi** [caracal-pipeline/caracal#1322]
I noticed that the output mask name in the postcal step "make a mask for the initial ddf image" is wrong:
https://github.com/caracal-pipeline/caracal/blob/f4c143f8217041dece9065d14266cc52fa64dcf4/caracal/workers/ddcal_worker.py#L166

It should be:
`                 'output' : '{0:s}mask_ddf_postcal_{1:s}.fits:output'.format(output_folder,field),`

I'll soon push a change to fix it.

**Comment by francescaLoi** [comment]
This has been fixed in the `ddcal_tests` branch, where I also cleaned the postcal imaging functions (there were a lot of repetitions there). 
However, ddcal is still not working properly so I'll open a separate issue for it if needed.
@KshitijT and @o-smirnov , since you are the experts what do you think: would it be better to merge this minor change in the master branch or to wait until we fix all the issues (for example the wrong frequencies in the beam by eidos plus other stuff we are still not aware of)?

**Comment by KshitijT** [comment]
> @KshitijT and @o-smirnov , since you are the experts what do you think: would it be better to merge this minor change in the master branch 

I think it's best to merge it right away if you have it ready @francescaLoi .

**Comment by francescaLoi** [comment]
Ok, I'll push it now then!
