### ISSUE TITLE
Crasa.Crasa.CasaException: CASA raised a SEVERE exception while running task listobs

### ISSUE THREAD

**Issue by Kincaidr** [caracal-pipeline/caracal#1327]
Hi,

When i try and run caracal script: **caracal -c A2384_new_data.yml -ct singularity -sid ~/STIMELA_IMAGES2/**  
i get:

![image](https://user-images.githubusercontent.com/53697426/117568987-a3506b80-b0c3-11eb-9572-50a3a136b4c6.png)
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/6447306/log-caracal.txt)

**Comment by KshitijT** [comment]
Well, that's probably because the ms in question can't be found. The log says:

```
# --> CrashReporter initialized.
# 2021-05-09 10:39:13   INFO    listobs::utils::verify  Verifying arguments....File existence checking failed for vis /stimela_mount/msdir/A2384_new_data.ms
# 2021-05-09 10:39:13   WARN    listobs::utils::verify  Argument vis failed to verify.

```

Could you please confirm that "A2384_new_data.ms" is where it should be?

**Comment by viralp** [comment]
@Kincaidr check your ms file is present or not in the msdir.

**Comment by Kincaidr** [comment]
I have soft linked the ms so ill check if i have done this correctly:

![image](https://user-images.githubusercontent.com/53697426/117569442-fc210380-b0c5-11eb-8d3d-a3e1998666cd.png)

**Comment by Kincaidr** [comment]
It works now when i run in ms location. It was a soft link technicality. Thanks!
