### ISSUE TITLE
inspect worker throws TypeError: can only join an iterable

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1336]
It's clearly trying to make a more user-friendly message, but falling over in the process: https://github.com/caracal-pipeline/caracal/blob/master/caracal/workers/inspect_worker.py#L546

**Comment by Mulan-94** [comment]
@o-smirnov my mistake. Can I add the fix to an existing pull request?

**Comment by o-smirnov** [comment]
Whatever you prefer...

**Comment by o-smirnov** [comment]
Nah, make a tiny PR rather.
