### ISSUE TITLE
 pip install "decorator<5" needed on Ubuntu 20.04 with python 3.8

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1342]
I must be the first one trying 20.04? It's only been a year...

Anyway, vanilla install complained about decorator versions, solved by adding ``pip install "decorator<5"``. I can blindly add this to setup.py, or I can investigate a little to understand what and why.

**Comment by KshitijT** [comment]
As seen on ILIFU, I forget which OS they use.

**Comment by o-smirnov** [comment]
> I think this goes away when you upgrade setuptools

Not for me. Setuptools is a bit shite at figuring out complex cases, isn't it?

So here's the full causal chain: we need aplpy, which needs networkx, which needs decorator<5 for now (https://github.com/networkx/networkx/blob/v2.5/requirements/default.txt). Current decorator has gone to 5.x. We also have decorator as an explicit requirement, without a specific version number. 

Somehow pip decides that the best way out of this is to install decorator>5, and then complain about networkx whenever you run something.

**Comment by KshitijT** [comment]
> So here's the full causal chain: we need aplpy, which needs networkx, which needs decorator<5 for now (https://github.com/networkx/networkx/blob/v2.5/requirements/default.txt). Current decorator has gone to 5.x. We also have decorator as an explicit requirement, without a specific version number.

Omg. This is pretty horrible. so I guess specifying the decorator version is the way out?

**Comment by o-smirnov** [comment]
Yep, seems to work for now. Let's add ``decorator<5``, with a comment linking to this issue

**Comment by KshitijT** [comment]
@o-smirnov , can I add this through the UHF branch? The PR will be out on Monday.

**Comment by o-smirnov** [comment]
Sure, why not.
