### ISSUE TITLE
Caracals handling of 2 flux calibrators: No setjy for 2nd flux calibrator.

### ISSUE THREAD

**Issue by Kincaidr** [caracal-pipeline/caracal#1343]
Hi,

I have data from a gmrt observation in which we utilized 2 flux calibrators : at the start(3C48) and at the end(3C147):

![image](https://user-images.githubusercontent.com/53697426/121516826-f08b6a00-c9ee-11eb-8462-89757bf15965.png)
 
I have inserted them into the observation config worker like this:

![image](https://user-images.githubusercontent.com/53697426/121514651-8eca0080-c9ec-11eb-8214-a34bab0dc20e.png)

When i check the log fields from the caracal run, i see only 1 setjy task, which is for 3C48:

![image](https://user-images.githubusercontent.com/53697426/121516650-c043cb80-c9ee-11eb-9f0a-896ac808fe74.png)

Why is there no other setjy task for the other flux calibrator 3C147?
 Full log file is here:
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/6630932/log-caracal.txt)

**Comment by KshitijT** [comment]
@Kincaidr , that's because if you give two flux calibrators, CARACal uses the one observed the longest:
```
2021-05-31 14:30:59 CARACal INFO: Found more than one flux calibrator.Will use the one observed the logest (3C48).
```
I am probably missing something; but why would you want setjy done twice?

**Comment by Kincaidr** [comment]
Ok i see.

I thought that setjy needs to be run on each flux calibrator thats why i thought it had to be there twice.

**Comment by KshitijT** [comment]
Ah, no. I don't think that's needed.
