### ISSUE TITLE
Remove aplpy as a dependency and potentially decomission observation report

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1348]
See #1346
aplpy is getting old, so it should not be added as a dependency any more. It appears in the [Observation Report](https://github.com/caracal-pipeline/caracal/blob/f4c143f8217041dece9065d14266cc52fa64dcf4/caracal/scripts/Observation%20Report.ipynb)
and the [Selfcal Diagnostics](https://github.com/caracal-pipeline/caracal/blob/f4c143f8217041dece9065d14266cc52fa64dcf4/caracal/scripts/obs_report/SelfCal%20Diagnostics.ipynb)
So the suggestion is to remove the dependency from the scripts or removing/rewriting them completely.

**Comment by Sinah-astro** [comment]
`ll`

**Comment by Sinah-astro** [comment]
> ll
