### ISSUE TITLE
Can we bring flagging stats back into the log file ?

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1358]
I've just realised that #1328 replaces the flag stats that we used to write to the log files with some nice plots.

I and others (e.g., @edeblok ) use the flag stats written to the log when writing our reports. The plots are a great addition, but  can we please get back the text flag stats too? Ideally in a similar a format as what they used to have.

@o-smirnov @Athanaseus Could this be given some priority? Thanks!

**Comment by o-smirnov** [comment]
Ha, as the Russian saying goes, to be broke is to be cunningly inventive... but really, relying on the logfiles to contain certain output formatted in a certain way is a very twisted practice, and you get everything you deserve. You're always one CASA minor version away from disaster anyway. :stuck_out_tongue: 

I suggest @Athanaseus adds a couple of lines of code to his flagstats tool to spit out the statistics structure as a yml file (under outputs). Then you can load the file in your reports, replacing lines and lines of twisted log parsing with a single ``yaml.safe_load()`` call.

**Comment by paoloserra** [comment]
yeah man, we do what we can, the yml solution is fine of course.

**Comment by o-smirnov** [comment]
> we do what we can

Sorry, don't mean to sound preachy about it. But I would very much like to encourage everyone to discuss interfaces ("worker X needs piece of info Y, what's the best way to get it?") e.g. on the mailing list, before implementing creative solutions. Otherwise we end up with spaghetti dependencies, where touching one piece of code breaks seemingly unrelated workers...

**Comment by paoloserra** [comment]
Not a problem @o-smirnov ! But note that the reports I was mentioning are external to CARACal, so luckily our creative solutions were not part of CARACal. And sure, they were broken by CARACal improvements, but that is not a CARACal problem at all!

So the only point is, really, let's get the flag stats to the user (optionally), such that they can use them if they want.

**Comment by o-smirnov** [comment]
Excellent, well that ought to be easy to arrange, right @Athanaseus?

**Comment by Fil8** [comment]
another option, that would be nice to activate is to output a `.png` of the new flagging plots summary along with the html version.

**Comment by o-smirnov** [comment]
Ah yes, good idea. We already do that for the KGB plots. Ought to be easy!

**Comment by Athanaseus** [comment]
> I suggest @Athanaseus adds a couple of lines of code to his flagstats tool to spit out the statistics structure as a yml file (under outputs). Then you can load the file in your reports, replacing lines and lines of twisted log parsing with a single yaml.safe_load() call.

There is already a json file produced with the plots in `diagnostic_plots`, and it contains all the statistical information of the flags.
Is this not the required file format and content?

**Comment by o-smirnov** [comment]
> Is this not the required file format and content?

Sounds good to me. @paoloserra or @edeblok can check this perhaps?

**Comment by molnard89** [comment]
As @Athanaseus  said, the flagging stats are indeed under `/output/diagnostic_plots/*flagging_summary*.json` and we routinely read these for our MFS reports, so they work fine. We agreed during today's telecon that this is sufficient, and there's no need to add these stats to the logs, so I'm closing the issue with @paoloserra 's blessing.
