### ISSUE TITLE
Assertion error on `convert_pb_to_casaspi()` function in prep worker

### ISSUE THREAD

**Issue by healytwin1** [caracal-pipeline/caracal#1359]
I am running the latest (1.0.4) version of caracal on ilifu using the 1.7.0 stimela images. I have successfully run caracal on this particular dataset on ilifu in the past with almost identical config set-up, so I am not sure why this fails.

Here is the log-obsconf-listobs:
```
Starting container [listobs_ms0-14054063986603216270616345053227]. Timeout set to -1. The container ID is printed below.
running cd /scratch3/users/juliahealy/LowFreq/.stimela_workdir-16270616344841087 && singularity run --workdir /scratch3/users/juliahealy/LowFreq/.stimela_workdir-16270616344841087 --containall  --bind /scratch3/users/juliahealy/LowFreq/.stimela_workdir-16270616344841087/stimela_parameter_files/listobs_ms0-14054063986603216270616345053227.json:/stimela_mount/configfile:ro --bind /scratch3/users/juliahealy/caracal_venv/lib/python3.8/site-packages/stimela/cargo/cab/casa_listobs/src:/stimela_mount/code:ro --bind /scratch3/users/juliahealy/LowFreq/.stimela_workdir-16270616344841087/passwd:/etc/passwd:rw --bind /scratch3/users/juliahealy/LowFreq/.stimela_workdir-16270616344841087/group:/etc/group:rw --bind /scratch3/users/juliahealy/caracal_venv/bin/stimela_runscript:/singularity:ro --bind /idia/projects/healy-a2626/cutdata:/stimela_mount/msdir:rw --bind /scratch3/users/juliahealy/LowFreq/input:/stimela_mount/input:ro --bind /scratch3/users/juliahealy/LowFreq/msdir:/stimela_mount/output:rw --bind /scratch3/users/juliahealy/LowFreq/msdir/tmp:/stimela_mount/output/tmp:rw /software/astro/caracal/STIMELA_IMAGES_1.7.0/stimela_casa_1.6.3.sif /singularity
FATAL:   Failed to retrieve information for /users/juliahealy/.singularity: stat /users/juliahealy/.singularity: no such file or directory
cd /scratch3/users/juliahealy/LowFreq/.stimela_workdir-16270616344841087 && singularity returns error code 255
job failed at 2021-07-23 19:33:54.847413 after 0:00:00.116136
Traceback (most recent call last):
  File "/scratch3/users/juliahealy/caracal_venv/lib/python3.8/site-packages/stimela/recipe.py", line 710, in run
    job.run_job()
  File "/scratch3/users/juliahealy/caracal_venv/lib/python3.8/site-packages/stimela/recipe.py", line 422, in run_job
    self.job.run(output_wrangler=self.apply_output_wranglers)
  File "/scratch3/users/juliahealy/caracal_venv/lib/python3.8/site-packages/stimela/singularity.py", line 124, in run
    utils.xrun(f"cd {self.execdir} && singularity", ["run", "--workdir", self.execdir, "--containall"] \
  File "/scratch3/users/juliahealy/caracal_venv/lib/python3.8/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
    raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
stimela.utils.StimelaCabRuntimeError: cd /scratch3/users/juliahealy/LowFreq/.stimela_workdir-16270616344841087 && singularity returns error code 255
```

**Comment by SpheMakh** [comment]
The error seems to come from this line. But even the file `/users/juliahealy/.singularity` does not exist, I would think it would be created on the fly. 
```bash
FATAL:   Failed to retrieve information for /users/juliahealy/.singularity: stat /users/juliahealy/.singularity: no such file or directory
```

Can you attach the full logfile (output/log-caracal.txt)

**Comment by healytwin1** [comment]
> The error seems to come from this line. But even the file `/users/juliahealy/.singularity` does not exist, I would think it would be created on the fly.

Ah, so I may be the culprit here. I had a broken link for /users/juliahealy/.singularity - I have removed the dead link and have resubmitted the job, hopefully that has fixed it. Will let you know once the job starts.


> Can you attach the full logfile (output/log-caracal.txt)
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/6877388/log-caracal.txt)

**Comment by healytwin1** [comment]
I am definitely the culprit. It is running fine now.

**Comment by healytwin1** [comment]
An `Assertion Error` now pops up later when running the prep worker.

[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/6877661/log-caracal.txt)

**Comment by KshitijT** [comment]
> An `Assertion Error` now pops up later when running the prep worker.
> 
> [log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/6877661/log-caracal.txt)

What's your calibrator for these observations, @healytwin1 ?

**Comment by healytwin1** [comment]
gain: J2253+1608
flux: J1939-6342

**Comment by SpheMakh** [comment]
@KshitijT you may have an easier time chasing down, it's seems to come from this PR https://github.com/caracal-pipeline/caracal/commit/55d344e92a22b9802985c1da6c711f45c2435682

**Comment by KshitijT** [comment]
@healytwin1 , I don't know exactly why you are getting the error (this has nothing to do with the choice of the calibrator as such); I haven't faced the error myself on ILIFU with the same version of CARACal and the same settings. 
The only possibility I see here is that it is related to #1354 (which anyway needs fixing).
To that end, I have made a branch: `fix_issue_1354`; could you please reinstall from that branch and check if that fixes your issue?

**Comment by healytwin1** [comment]
Will do. How do I install from a particular branch?

**Comment by KshitijT** [comment]
> Will do. How do I install from a particular branch?

You could do it either like this:
1. git clone https://github.com/caracal-pipeline/caracal.git
2.  cd  caracal
3. git checkout fix_issue_1354
4. **Activate your virtualenv at this point**
4. pip install -U .

Or more directly:
Activate your virtualenv and run `pip install -U git+https://github.com/ska-sa/caracal.git@fix_issue_1354 `

**Comment by healytwin1** [comment]
The `fix_issue_1354` worked.

**Comment by KshitijT** [comment]
Awesome ! Thanks for testing it out. :)

**Comment by KshitijT** [comment]
Ooops. I shouldn't close this issue until the branch is merged in master. @SpheMakh , can haz review?
