### ISSUE TITLE
Hardcoded scan selection in crosscal must go

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1396]
@bennahugo @SpheMakh https://github.com/caracal-pipeline/caracal/pull/1393 has hardcoded a scan selection into the `crosscal` worker. See https://github.com/caracal-pipeline/caracal/blob/9a6542e0b10aca29fbe8f5992b7dbe5df852352d/caracal/schema/crosscal_schema.yml#L159-L163 and https://github.com/caracal-pipeline/caracal/blob/9a6542e0b10aca29fbe8f5992b7dbe5df852352d/caracal/schema/crosscal_schema.yml#L273-L277

That needs to go. The default needs to be all scans.

**Comment by bennahugo** [comment]
Sorry I didn't realise example meant default... Perhaps this should be
renamed.

**Comment by paoloserra** [comment]
No worries @bennahugo , I thought that was the problem indeed.

We adopted `example` as he key to give the default value a long time ago. Back then, there were only a few keys that were allowed to be used, and `example` was the only one that made some kind of sense. `Default` or something like that was not allowed.

We haven't looked into that since then -- maybe that's changed now.
