### ISSUE TITLE
update of regions package breaking ddcal worker 

### ISSUE THREAD

**Issue by kendak333** [caracal-pipeline/caracal#1438]
Fresh install of stable caracal release has an ImportError with the ddcal worker due to an update to the regions package to version 0.6:

`Traceback (most recent call last):`
  `
File "/home/knowles/caracal-venv/lib/python3.8/site-packages/caracal/workers/worker_administrator.py", line 115, in __init__
    wkr = __import__(_worker)
`
  `
File "/home/knowles/caracal-venv/lib/python3.8/site-packages/caracal/workers/ddcal_worker.py", line 11, in <module>
    from regions import PixCoord, write_ds9, PolygonPixelRegion
`
`ImportError: cannot import name 'write_ds9' from 'regions' (/home/knowles/caracal-venv/lib/python3.8/site-packages/regions/__init__.py)`
`2022-08-01 13:03:50 CARACal ERROR: Worker "ddcal_worker" could not be found at /home/knowles/caracal-venv/lib/python3.8/site-packages/caracal/workers [ImportError]`

Force-install of an earlier regions package fixes the problem:
`pip install "regions<0.6"`

**Comment by KshitijT** [comment]
@kendak333 , thanks for posting the solution. :)

The issue you faced is the same one documented by @gigjozsa in #1429 , I think. i'll try to implement an internal solution soon.

**Comment by kendak333** [comment]
@KshitijT ah ok, I did try search for existing issues but didn't come up with any, possibly the spotty internet connection here.
