### ISSUE TITLE
Reading MS' from multiple input rawdatadirs

### ISSUE THREAD

**Issue by rstofi** [caracal-pipeline/caracal#1476]
I am trying to process data from several input MS' that sit in different long-term storage folders, and I ideally don't want to move them, but only to read them for processing. I've tried to create a symlink to a shared `rawdatadir` but it is not working (see https://github.com/caracal-pipeline/caracal/issues/1086) and the `rawdatadir` only accepts a single path string value. Is there a possible quick solution, or do I have to move the data, with no other solution available?

**Comment by KshitijT** [comment]
I think the only way is to use one `rawdatadir` at a time, let it create 'processed' measurement sets (calibrators + fields) in your msdir and then do the selfcal with all the target MSs together.

**Comment by rstofi** [comment]
Okay, thanks that seems to work well enough for my use case!
