### ISSUE TITLE
ddcal worker hanging on after initial Dico Model

### ISSUE THREAD

**Issue by AnnalisaB** [caracal-pipeline/caracal#1477]
Hi

I started ddcal with 2 directions and with automasking (use_mask: True)
It proceeds up to  the initial quick image with DDF, computes the model for the 2 directions and then it hangs on.
I don't see any lock in the MS file in the msdir, so I don't know what it is waiting for

I attach the full log and copy below the last lines:

INFO      00:42:23 - DDFacetSim         [x01] [25.4/160.8 62.1/543.9 22.4Gb] Computing visibilities in 1 facets for direction 'DDE_REG1' for model '/stimela_mount/output/DDcal_1_A2034-DD-precal.DicoModel'...
INFO      00:43:52 - DDFacetSim         [x01] [28.4/187.7 65.1/570.7 22.4Gb] Computing visibilities in 1 facets for direction 'DDE_REG2' for model '/stimela_mount/output/DDcal_1_A2034-DD-precal.DicoModel'...
INFO      00:46:12 - main               [x01] [4.2/163.4 31.9/537.5 28.4Gb] I/O job(s) complete

Thanks
Annalisa

[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/11017036/log-caracal.txt)

**Comment by KshitijT** [comment]
@AnnalisaB , I haven't encountered this error before; could you please share the cubical log in the `3GC` folder too - just in case it shows more information?

**Comment by AnnalisaB** [comment]
Thanks, I will give it a try!

**Comment by Athanaseus** [comment]
Please open it if needed!
