### ISSUE TITLE
Line imaging error: CASA raised a SEVERE exception while running task mstransform

### ISSUE THREAD

**Issue by tzuyin0524** [caracal-pipeline/caracal#1512]
I was doing line imaging and all of the other calibrations were done.
It was ok and without error to make a continuum image.
When I only enable the line worker, I get the error like the part of error log file below:

# 2023-05-17 19:29:08	INFO	MSTransformManager::colCheckInfo	Adding DATA column to output MS from input CORRECTED_DATA column
# 2023-05-17 19:29:08	INFO	MSTransformManager::open	Select data
# 2023-05-17 19:29:08	INFO	MSTransformManager::createOutputMSStructure	Create output MS structure
# 2023-05-17 19:29:10	INFO	MSTransformManager::checkFillWeightSpectrum	Optional column WEIGHT_SPECTRUM found in input MS will be written to output MS
# 2023-05-17 19:29:10	INFO	MSTransformManager::regridSpwSubTable	Regridding SPW with Id 0
# 2023-05-17 19:29:10	INFO	MSTransformManager::regridSpwAux	Input SPW:  1024 channels, first channel = 8.563134766e+08 Hz, last channel = 1.711477539e+09 Hz, first width = 8.359375000e+05 Hz, last width = 8.359375000e+05 Hz
# 2023-05-17 19:29:10	INFO	MSTransformManager::regridSpwAux	Calculate frequencies in output reference frame
# 2023-05-17 19:29:10	INFO	MeasIERS::fillMeas(MeasIERS::Files, Double) 	Requested JD 59928.2 is outside the range of the IERS (Earth axis data) table.
# 2023-05-17 19:29:10	INFO	MeasIERS::fillMeas(MeasIERS::Files, Double) +	Calculations will proceed with less precision
# 2023-05-17 19:29:10	SEVERE	MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4290)	Leap second table TAI_UTC seems out-of-date.
# 2023-05-17 19:29:10	SEVERE	MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4290)+	Until the table is updated (see the CASA documentation or your system admin),
# 2023-05-17 19:29:10	SEVERE	MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4290)+	times and coordinates derived from UTC could be wrong by 1s or more.
# 2023-05-17 19:29:10	WARN	MSTransformRegridder::calcChanFreqs	 *** Requested new channel width (835856 Hz) is smaller than smallest original channel width
# 2023-05-17 19:29:10	WARN	MSTransformRegridder::calcChanFreqs+	     which is 835857 Hz
# 2023-05-17 19:29:10	SEVERE	MSTransformRegridder::calcChanFreqs	calcChanFreqs failed, check input start and width parameters
# 2023-05-17 19:29:11	SEVERE	ParallelDataHelper::::	Task mstransform raised an exception of class RuntimeError with the following message: 2023-05-17 19:29:10	SEVERE	MSTransformRegridder::calcChanFreqs	calcChanFreqs failed, check input start and width parameters
# Running CASA task 'mstransform'
# Traceback (most recent call last):
# INFO:    Cleaning up image...
#   File "/stimela_mount/code/run.py", line 8, in <module>
#     task.run()
#   File "/usr/local/lib/python3.8/dist-packages/Crasa/Crasa.py", line 122, in run
#     raise CasaException("CASA raised a SEVERE exception while running task {0:s}".format(self.task))
# Crasa.Crasa.CasaException: CASA raised a SEVERE exception while running task mstransform
2023-05-17 21:29:12 CARACal.Stimela.mstransform-ms0 ERROR: cd /scratch3/users/tzuyin/reduction/.stimela_workdir-16843484421262705 && singularity run --userns --workdir /scratch3/users/tzuyin/reduction/.stimela_workdir-16843484421262705 --containall returns error code 1
2023-05-17 21:29:12 CARACal.Stimela.mstransform-ms0 ERROR: job failed at 2023-05-17 21:29:12.253840 after 0:00:17.158986
2023-05-17 21:29:12 CARACal ERROR: Job 'mstransform-ms0:: Doppler tracking corrections' failed: cd /scratch3/users/tzuyin/reduction/.stimela_workdir-16843484421262705 && singularity run --userns --workdir /scratch3/users/tzuyin/reduction/.stimela_workdir-16843484421262705 --containall returns error code 1 [PipelineException]
2023-05-17 21:29:12 CARACal INFO:   More information can be found in the logfile at output/logs-20230517-203349/log-caracal.txt
2023-05-17 21:29:12 CARACal INFO: exiting with error code 1

I try to reinstall Caracal again with a different method and also check the .yml and .sh file but still fails.
I have no idea why this get errors.

Thank you very much!

**Comment by tzuyin0524** [comment]
Hi @KshitijT,

Thanks, the attachment is the log file and yml file
[runjob-6259244-stderr.log](https://github.com/caracal-pipeline/caracal/file
[meerkat-defaults.yml.txt](https://github.com/caracal-pipeline/caracal/files/11552832/meerkat-defaults.yml.txt)
s/11552751/runjob-6259244-stderr.log)

Tzuyin

**Comment by KshitijT** [comment]
@tzuyin0524 , sorry, I don't seem to be able to access the log unfortunately.

**Comment by tzuyin0524** [comment]
@KshitijT , I think this may work, please check the attachment, thanks
[runjob-6259244-stderr.log.txt](https://github.com/caracal-pipeline/caracal/files/11555594/runjob-6259244-stderr.log.txt)

**Comment by tzuyin0524** [comment]
Hi @KshitijT,
Thank you very much! I successfully create the cube!
