### ISSUE TITLE
NCPU for crystalball skymodel

### ISSUE THREAD

**Issue by ktrehaeven** [caracal-pipeline/caracal#1516]
Hi. This is just a request to add an option to be able to change the number of cpus crystalball uses when predicting the primary model in the crosscal.set_model. Currently you can only set the ram memory usage, so even though I'm only using 0.5 of the ram memory, I'm hogging up all the cpus. Not sure how this affects the node performance for other users. Plus sometimes my run aborts like in the attached log and I think its because of the unintentional hogging.
![Screenshot from 2023-06-04 20-41-37](https://github.com/caracal-pipeline/caracal/assets/77777044/65b095c9-add1-41c8-a8be-a7b8c39ec46f)
[log-crosscal-set_model_cal-0-20230604-164044.txt](https://github.com/caracal-pipeline/caracal/files/11646410/log-crosscal-set_model_cal-0-20230604-164044.txt)

**Comment by paoloserra** [comment]
can you see whether this branch does what you need? https://github.com/caracal-pipeline/caracal/tree/issue1516

**Comment by ktrehaeven** [comment]
Hi @paoloserra yes it does! Thank you very much.
