### ISSUE TITLE
Pulling STIMELA images leaves a lot of debris behind

### ISSUE THREAD

**Issue by mstagni** [caracal-pipeline/caracal#1520]
Would it be possible to include a command when running stimela pull -s that clears directories in .apptainer or .singularity not to leave 60+ GB in the user's home?

**Comment by SpheMakh** [comment]
Yes, we can add a *replace* to replace old stimela images if a newer one is being downloaded. But this still won't clear the cache that lives in `~/.singularity` or `~/.apptainer`, that is not a stimela issue. I suggest you set up a routine [cache purge](https://apptainer.org/docs/user/1.0/build_env.html#cleaning-the-cache) using `apptainer cache clean` command, for example to clear cached files after 30 days, run: 
```
apptainer cache clean --days 30
```
