### ISSUE TITLE
FATAL:   While making image from oci registry: error copying image out of cache:

### ISSUE THREAD

**Issue by Dakalo12** [caracal-pipeline/caracal#1530]
Hi 

I am getting the following error: 

# INFO:    Using cached SIF image
# FATAL:   While making image from oci registry: error copying image out of cache: could not open temporary file for copy: failed to create temporary file: open /singularity_images/tmp-copy-812826199: no such file or directory
2023-07-24 20:26:24 CARACal ERROR: cd /scratch3/users/dakalo/singularity_images && singularity returns error code 255 [StimelaCabRuntimeError]
2023-07-24 20:26:24 CARACal INFO:   More information can be found in the logfile at output/logs-20230724-202622/log-caracal.txt
2023-07-24 20:26:24 CARACal INFO: exiting with error code 1

I have attched the log file.

[runjob-6631775-stderr.log](https://github.com/caracal-pipeline/caracal/files/12149184/runjob-6631775-stderr.log)

[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/12149385/log-caracal.txt)

Thank you for your help in advance.

**Comment by o-smirnov** [comment]
What is your ``SINGULARITY_TMPDIR`` environment variable set to? And if it is not set, could you try setting

```
$ export SINGULARITY_TMPDIR=/scratch3/users/dakalo/
```

At the moment it's trying to put temporary build files under ``/singularity_images/tmp-copy-812826199``, which is a bit of an absurd place to put it. @SpheMakh have you seen this problem before?

**Comment by Dakalo12** [comment]
@o-smirnov 

It was failling to pull the stimela singularity images.

But I have used /software/astro/caracal/STIMELA_IMAGES_1.7.7

Now it is running

Thank you.
