### ISSUE TITLE
Use multiple `rawdatadir` directories and combine into one MS 

### ISSUE THREAD

**Issue by SpaceMeerkat** [caracal-pipeline/caracal#1538]
From the docs it's clear that you can combine multiple measurement sets using a list of strings in:

> `getdata` > `dataid` (see [here](https://caracal.readthedocs.io/en/latest/manual/workers/getdata/index.html#dataid))

But the `general` worker appears to only support a single `rawdatadir` (see [here](https://caracal.readthedocs.io/en/latest/manual/workers/general/index.html#rawdatadir)).

Is this true or is it possible to combine measurement sets (lets assume they have the same target and calibrators) which are in different directories with different data id's?

Many thanks for any help on this!

**Comment by paoloserra** [comment]
I think they all need to be in the same rawdatadir indeed.

If they don't you could consider trying with symlinks. I don't know whether that would work -- never tried that.

**Comment by KshitijT** [comment]
Please see the discussion in #1476 .

**Comment by SpaceMeerkat** [comment]
Okay yep yep, it seems like it's a case of strictly one rawdatadir to begin with until you have processed files in your local msdir for combining later. Thanks both!
