### ISSUE TITLE
MemoryError When Performing Selfcal with Cubical

### ISSUE THREAD

**Issue by bazhaoyu** [caracal-pipeline/caracal#1560]
When performing `selfcal` on 1.7 TB MeerKAT data, I encountered a memory problem that _the estimated memory usage exceeds the allowed percentage of system memory._
![image](https://github.com/caracal-pipeline/caracal/assets/28834171/95a54c45-c592-4014-8c55-335a59bb9255)

The log file is attached here:
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/13948519/log-caracal.txt)

Actually, I also encountered this kind of memory problem when using ragavi-vis (see https://github.com/caracal-pipeline/caracal/issues/1558). The data size I used is around 1.7 TB. The server/node used for processing has 32 CPU cores and ~ 123 GB of memory.

I'm also seeking advice on how to handle big MeerKAT data analysis. Would it be more effective to split the dataset into smaller sizes, or use a fat memory node?

**Comment by paoloserra** [comment]
In addition to my advice to average the data in frequency for the purpose of continuum science, you could also reduce the number of cpu's used.

**Comment by bazhaoyu** [comment]
> In addition to my advice to average the data in frequency for the purpose of continuum science, you could also reduce the number of cpu's used.

My first try was using 1 CPU core and default `dist_max_chunks: 4`. It took almost two days. Then, I tried to use 32 CPU cores and `dist_max_chunks: 1`, which took 1 day. I am so sorry; I have no idea how to balance the CPU cores and  `dist_max_chunks`.  

I would like to average the data in frequency to reduce the data size and then try self-calibration.

**Comment by paoloserra** [comment]
Nothing to be sorry about, this part of the pipeline is not easy to get right.

Did the run with 1 CPU and `dist_max_chunks: 4` run out of memory?

**Comment by bazhaoyu** [comment]
Yes, it also ran out of memory.
<img width="1397" alt="image" src="https://github.com/caracal-pipeline/caracal/assets/28834171/0155ea90-edd2-486b-a087-e2254ae6a3cb">

**Comment by paoloserra** [comment]
OK, let's see what freq averaging does!

**Comment by JSKenyon** [comment]
Hi! Just pitching in here - the time chunking looks quite large i.e. loading 300 unique times per chunk when a single solution interval only requires 30. I would suggest setting the time chunking to 30 and then trying again with say `dist_max_chunks: 16`. I think you current setup will end up loading many, very large chunks unnecessarily.

**Comment by paoloserra** [comment]
You're right @JSKenyon .

In fact, @bazhaoyu , please set `cal_timeslots_chunk: -1`, as per default. See https://caracal.readthedocs.io/en/latest/manual/workers/selfcal/index.html#cal-timeslots-chunk .

**Comment by bazhaoyu** [comment]
Now I run the analysis by setting `chan_ave` of 5 in the transform worker, and setting `cal_timeslots_chunk: -1` and `dist_max_chunks: 16` in the selfcal worker. 
I will let you know the results ASAP. Thanks very much!

**Comment by bazhaoyu** [comment]
I got the same memory error. This time, the data size is only ~200 GB.
I have attached the screenshot and log file:

<img width="1045" alt="image" src="https://github.com/caracal-pipeline/caracal/assets/28834171/f1229a17-4515-4c0b-b9ad-b7e0ad34a5b0">

[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/13961842/log-caracal.txt)

**Comment by bazhaoyu** [comment]
> I got the same memory error. This time, the data size is only ~200 GB. I have attached the screenshot and log file:
> <img alt="image" width="1045" src="https://private-user-images.githubusercontent.com/28834171/297347842-f1229a17-4515-4c0b-b9ad-b7e0ad34a5b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODc3NTIsIm5iZiI6MTcwNTQ4NzQ1MiwicGF0aCI6Ii8yODgzNDE3MS8yOTczNDc4NDItZjEyMjlhMTctNDUxNS00YzBiLWI5YWQtYjdlMGFkMzRhNWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEwMzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmY2JlMWRjNmU1YTQ0YjRhMmE5YzcyYWYxYjVmMDYxNjgyOGI0NzZlZTg2ZjYyMzU1ZGNhNDI2Mzg1YzdlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iFEqElQ0H0i1qH37EPXAkbeiJVhpO6byZSk03osIxAA">
> 
> [log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/13961842/log-caracal.txt)

Maybe I should try with a smaller `dist_max_chunks`? Maybe set it as default?

**Comment by paoloserra** [comment]
Yes, I think it's worth a try

**Comment by bazhaoyu** [comment]
It works with default parameters of `cal_timeslots_chunk: -1` and `dist_max_chunks: 4`. Thank you for all your help!

**Comment by paoloserra** [comment]
Good, thanks for your patience!
