### ISSUE TITLE
3C273 as primary calibrator

### ISSUE THREAD

**Issue by sourabhpaul** [caracal-pipeline/caracal#1563]
Hi,

I am trying to calibrate some data which has 3C273 as both primary and secondary calibrator. I found a similar [issue](https://github.com/caracal-pipeline/caracal/issues/1436) and as per the suggestions posted there I installed caracal from branch `quickfix_issue1436`. I'm getting the following error at the beginning of the caracal run:

```
/users/sourabh/caracal_3c273/caracal_env_3c273/bin/caracal:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('caracal==1.0.6')
2024-01-23 15:14:59 CARACal INFO: Invoked as /users/sourabh/caracal_3c273/caracal_env_3c273/bin/caracal -c crosscal.yml -ct singularity -sid /software/astro/caracal/STIMELA_IMAGES_1.7.7
2024-01-23 15:14:59 CARACal ERROR: configuration file crosscal.yml fails to validate, list of errors follows:
```

out file:

```
  at top level:
    
"load()" has been removed, use

  yaml = YAML(typ='rt')
  yaml.load(...)

and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "/users/sourabh/caracal_3c273/caracal/caracal/dispatch_crew/config_parser.py", line 144

                config_content = ruamel.yaml.load(file, ruamel.yaml.RoundTripLoader, version=(1, 1))
```

With the standard installation from the master branch, the pipeline proceeds with the same configuration file and stops after some time with an error that 3C273 is not in the CASA calibrator list. Thanks for the help.

**Comment by sourabhpaul** [comment]
Also, is it possible to insert a source model manually using `setjy`? From the caracal manual, it looks like this can be done with `set_model`? Thanks.

**Comment by KshitijT** [comment]
@sourabhpaul please see #1554 , it's the same error you are getting.

**Comment by sourabhpaul** [comment]
Thanks!
