### ISSUE TITLE
Cubical failing with Stimela 1.7.10

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1586]
@SpheMakh see attached error (left column, while the right column is a successful run with Stimela 1.7.9)

<img width="1104" alt="Screenshot 2024-05-23 at 14 46 33" src="https://github.com/caracal-pipeline/caracal/assets/6591265/c955f778-38d2-4c74-b9ae-244f073379dd">

**Comment by Fil8** [comment]
this issue can be solved by downloading pristine STIMELA images. Also check .singularity folder.
