### ISSUE TITLE
stimela ERROR: Parameter parallel-gridding is unknown.

### ISSUE THREAD

**Issue by heming306** [caracal-pipeline/caracal#1599]
Hi,

I get this error with selfcal, not sure what to do :

`2024-09-17 19:11:42 CARACal.Stimela.image-field0-iter1 ERROR: Parameter parallel-gridding is unknown. Run 'stimela cabs -i wsclean' to g>`
`2024-09-17 19:11:42 CARACal.Stimela.image-field0-iter1 ERROR: job failed at 2024-09-17 19:11:42.252552 after 0:00:00.003214`
`2024-09-17 19:11:42 CARACal ERROR: Job 'image-field0-iter1:: Make wsclean image (selfcal iter 1)' failed: Parameter parallel-gridding is>`
`2024-09-17 19:11:42 CARACal INFO:   More information can be found in the logfile at output/logs-20240917-191046/log-caracal.txt`
`2024-09-17 19:11:42 CARACal INFO: exiting with error code 1`

Also attached are log files.
[log-caracal.txt](https://github.com/user-attachments/files/17032965/log-caracal.txt)
[log-selfcal-image-field0-iter1-20240917-051333.txt](https://github.com/user-attachments/files/17032966/log-selfcal-image-field0-iter1-20240917-051333.txt)

Regards

**Comment by Athanaseus** [comment]
Hi @heming306,

Thank you for raising this issue.
Based on the log, it looks like you're using Stimela version `1.7.7`.
The parameter in question was introduced in version `1.7.8`.

Please consider bumping your _Stimela_ version, or you can install the latest release with:
```
pip install stimela==1.7.10
```

Also updating _CARACal_ to the latest release should resolve the issue:
```
pip install -U caracal
```

I hope this helps!

Best regards,

**Comment by heming306** [comment]
Hi @Athanaseus ,

Updated _stimela_ to `1.7.8` and all runs well.

Thanks
