### ISSUE TITLE
Configuration file to try leakage pol calibration only

### ISSUE THREAD

**Issue by AnnalisaB** [caracal-pipeline/caracal#1615]
Hi,

as I have no success calibrating the polarization using 3C286, 
I wanted to try the experimental strategy I saw in the polcal worker and  calibrate the leakage only. 
However, I can not figure out how to pass Caracal the info that pocal=None as I see in the polcal worker.

Here my config file and the error I get

Thanks in advance

**ERROR:**

CARACal ERROR: Unable to determine pol_calib=xcal. Is your obsconf section configured properly?Your setting of pol_calib=xcal selects .
Supported calibrators are 3C138, 3C286, J1130-1449, J1331+3030, J0521+1638.
Alternatively, you can calibrate both leakage and polarization using a (known or unknown) polarized sourc
observed at several parallactic angles. Configure this source as obsconf:xcal, and leakage_calib=pol_calib=xcal. [RuntimeError]

**CONFIG file (only relevant workers):**
`**obsconf:**
  target:
    - 'J1331+3030'
  fcal:
    - 'J1939-6342'
  bpcal:
    - 'J1939-6342' 
  gcal:
    - 'J1609+2641'
  refant: 'm060'
**transform:**
  enable: true
  field: calibrators
  label_out: cal
  split_field:
    enable: true
    col: data

**crosscal:**
  enable: true
  label_in: cal
  label_cal: kgb
  uvrange: '>100'
  set_model:
    enable: true
    meerkat_band: 'L'
    meerkat_skymodel: true
    tile_size: 16
  primary:
    reuse_existing_gains: false
    order: KGBAKGB
    calmode: ['', ap, '', null, '', ap, '']
    solint: [inf, inf, inf, null, inf, inf, inf]
    combine: [scan, '', scan, null, scan, '', scan]
    b_fillgaps: 70
    plotgains: true
  secondary:
    reuse_existing_gains: false
    order: GAF
    apply: KB
    combine: ["",null,""]
    solint: [inf,null,inf]
    calmode: [ap,null,ap]
    plotgains: true
  apply_cal:
    applyto:
      - gcal
      - bpcal

**polcal:**
  enable: true
  label_in: cal
  label_cal: pcal
  otfcal:
    enable: true
    label_cal: kgb
  extendflags: True
  feed_angle_rotation: '-90'
  uvrange: '>150'
  reuse_existing_tables: false
  set_model_pol: False  
  leakage_calib: fcal

  gain_solint: '60s'
  time_solint: 'inf'
  plotgains: true
  apply_pcal: true
  applyto:
    - gcal
    - bpcal

**Comment by Athanaseus** [comment]
Hi @AnnalisaB ,

Can you please try to explicitly set `pol_calib: 'none'`, as by default it's `xcal`: 

> Configure this source as obsconf:xcal, and leakage_calib=pol_calib=xcal. [RuntimeError]

I hope this helps.

Best regards

**Comment by AnnalisaB** [comment]
I see, thanks, I've just launched the new run and I'll keep you posted

**Comment by AnnalisaB** [comment]
It works now, 
I was confused because I thought I had to specify the polcal in the obsconf worker
many thanks!
