### ISSUE TITLE
CWL pipeline repo

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/caracal#207]
This is where we doing dev for a CWL-based pipeline. CWL makes distributing the compute much easier

https://github.com/ska-sa/den

**Comment by gigjozsa** [comment]
@SpheMakh can this be closed?

**Comment by Athanaseus** [comment]
@SpheMakh is this still relevent?

**Comment by Athanaseus** [comment]
please re-open if you still working on it.
