### ISSUE TITLE
distributing the compute

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/caracal#237]
TODO:
- Add singularity support to stimela
  - We need this for the IDIA slurm cluster
- Use dask-drmaa and daskos (for mesos cluster)

**Comment by gigjozsa** [comment]
On the other hand I will now bump this up for discussion in future planning.

**Comment by gigjozsa** [comment]
Let me close this tentatively and see if it gets missed. Fornax is using a distribution scheme very efficiently.
