### ISSUE TITLE
flags and time averaging

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#27]
We use CASA SPLIT to time-average the data with the default setting KEEPFLAGS = TRUE. However, I read in the documentation of this task:

"Flagged data will be included in the average calculation, unless the parameter keepflags is set to False. In this case only partially flagged rows will be used in the average."

I'm surprised that flagged data would be included in the average. I wonder whether that's what we want.

I've tried to set KEEPFLAGS = FALSE and the result is very different indeed. Any thoughts?

**Comment by gigjozsa** [comment]
This should get high priority for v1.1

**Comment by KshitijT** [comment]
Is it actually still relevant ? With the new workflow we split/average and then flag both calibrator and targets. The only thing to worry about would be the observatory flags ? And the flags which presumably are applied through crosscal to the target ?

**Comment by paoloserra** [comment]
The workflow is flexible, and users could decide to average the data before or after flagging. I suggest we keep this open to not lose memory of this trickiness.

**Comment by KshitijT** [comment]
Closing this following today's discussion.
