### ISSUE TITLE
DQA products

### ISSUE THREAD

**Issue by Fil8** [caracal-pipeline/caracal#310]
We made a layout of what `meerkathi` should produce for **data quality assessment**. 

`meerkathi` already produces multiple plots to inspect the calibrated data. We need a worker to make a more quantitative analysis producing a table containing important statistics of these plots. These stats will allow us to immediately assess if an observation is good/bad and if the all the steps of the pipeline worked correctly. 

These are the outputs we want:

*  **Cross-calibration**
**Stats from `ploms` plots:** 
   * Real vs Imaginary part of corrected visibilities of bandpass calibrator. Quantities are measured for pre-set spectral windows, e.g. 1.4 GHz, 1.1 GHz, 1.7 GHz.
       - Centroid and rms of distribution
       - Comparison with expected 2d model
       - Asymmetry of the distribution
   * Amplitude and phase of bandpass calibrator over frequency. We expect a smooth polynomial over frequency.
       - $\sigma\big(|B_\nu|-{\rm polyfit} ( |B_\nu| ) \big) $ ; median value over all antennas  

**Stats from `html interactive` plots:**
   * Amplitude of gains over time. We expect a linear distribution centred at one.
      - $\sigma\big(|G_t|\big) $ ; median value over all antennas
   * Phase of of gains over time. We expect a smooth polynomial over frequency.
      - $\sigma\big(|\phi_{G_t}|-{\rm polyfit} ( |\phi_{G_t}| ) \big) $; median value over all antennas
   * Real vs Imaginary part of corrected Stokes V unflagged visibilities of target
      - compare with expected low r.m.s of distribution centred at 0.
* **RFI**
   * % of flagged visibilities in the protected band & in a rubbish band.
      - % of flags in short (< 200m) and long (>200 m) baselines. 
* **Self-Calibration**
   * Metrics from `aimfast`.
       * _what are them?_
   * Flux of sources in continuum images.
       * Flux ratio of point sources in field above certain threshold between MeerKAT & NVSS (1.4 GHz) / SUMMS (856 MHz). Sources must also have high S/N and must be separate more than 45'' not to present confusion problems with archival cross-matching.
   * Astrometry offset with sources from archive. 
   * $\frac{{\rm noise\ \ in\ \ residual \ \ image}}{{\rm expected \ \ noise}}>$
* **HI**
   * $<\frac{{\rm measured \ \ noise}}{{\rm expected \ \ noise}}>$ in a useful channel range (i.e. protected band, rubbish band)
   * $\frac{{\rm r.m.s.\ \ in \ \ spectra \ \ against \ \ bright \ \ continuum \ \ source}}{<{\rm noise \ \ in \ \ cube}>}$: a ratio close to 1 should indicate good continuum subtraction.

**Comment by gigjozsa** [comment]
@paoloserra @Athanaseus @o-smirnov @Fil8 
could you check how much of this has been implemented?
