### ISSUE TITLE
1GC calibration report: table of calibrator field properties

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/caracal#408]
A table with the properties of the calibrator fields would be useful. This table could include

- A source catalogue of the calibrator fields
- Spectrum
- Astrometry

**Comment by gigjozsa** [comment]
@SpheMakh @Mulan-94 @o-smirnov @Athanaseus how far are we actually with this?

**Comment by SpheMakh** [comment]
Yes, it was addressed by #961
