### ISSUE TITLE
Aimfast and selfcal loop quality assessment

### ISSUE THREAD

**Issue by KshitijT** [caracal-pipeline/caracal#430]
A feedback I got from today's discussion (from Larry Rudnick) in SPARCS is this: right now we derive the selfcal stopping criteria in a "differential" manner, i.e. DR/ Noise between successive images. At some point we might want to go sort of for an absolute scale; i.e. compare the flux densities, rms noise etc. with what we expect. As an example, the flux densities could be compared to those with external catalogs / previous images of the same field and the rms noise could be compared to what we expect given the observation time and amount of flagged data etc for that particular dataset.

Not immediately needed, more of an enhancement.

**Comment by gigjozsa** [comment]
@KshitijT is this still relevant? This is so ambitious it might never be done (unless I don't see examples that you see).

**Comment by KshitijT** [comment]
It's not **that** ambitious. :)
As for being relevant; it's a neat little sanity check on the images we get. 
Can do for a bottle of mirto.

**Comment by gigjozsa** [comment]
As a stopping criterion?

**Comment by KshitijT** [comment]
More like quality assessment.

**Comment by gigjozsa** [comment]
Ah that's different.

**Comment by KshitijT** [comment]
Closing this issue since it has been consigned to the purgatory for hubble time now.
