### ISSUE TITLE
Aimfast plotting for source flux densities - NOT a good idea for fluffy emission

### ISSUE THREAD

**Issue by KshitijT** [caracal-pipeline/caracal#561]
Continuing the series of issues where I basically eat my words on various approaches previously extolled for their apparent virtues, comes a new entry - Aimfast plotting of source flux densities. 

In issue #387 (now closed, god rest it's soul), I suggested that it's a totally awesome idea to run source finder (PyBDSF) to generate a source model  _even when using_ `vis_only` _mode_,  since we want to keep tabs on changing flux densities with calibration steps and having source models makes this comparison easy. While this all is perfectly true, this can take ages to run if the field contains lot of diffuse emission - not only that, but we all know PyBDSF sucks when it comes to modelling such emission. 

However, exactly in such cases we want to make sure the fluffy stuff is not being eaten by amp self-cal (or indeed phase self-cal, @o-smirnov ?), so we do want Aimfast to track flux density changes. It's just that PyBDSF may not be the best tool to use here.

This epiphany comes in the wake of actually reducing a field with lots of diffuse emission - the extract_sources step ran for 6 hours before I killed it, in the interests of finishing the reduction in Hubble time. Maybe we need some other tool to get the fluffy source fluxes quickly (ProFound, maybe?) ? Thoughts/suggestions/comments welcome.

**Comment by Athanaseus** [comment]
see #1448
