### ISSUE TITLE
git pre-commit flake8 checks

### ISSUE THREAD

**Issue by sjperkins** [caracal-pipeline/caracal#583]
This approach will result in running flake8 on the repo every time some tries to commit. The commit will fail if it isn't flake8 compliant.

The downsides are that this can't really be enforced.

https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

Another alternative might be using pytest to run your tests and installing the pytest-flake8 plugin. This results in flaking and running tests at the same time.

**Comment by Athanaseus** [comment]
Done. As part of CI test.
