### ISSUE TITLE
Install and run CARACal on ilifu SLURM cluster

### ISSUE THREAD

**Issue by Jordatious** [caracal-pipeline/caracal#625]
As some of you may know, I've been trying to build MeerKATHI on ilifu, in a central location that many users can access. It would be preferable that users don't build their own version in `/users`, since it's against the [ilifu policy](http://docs.ilifu.ac.za/#/data/directory_structure) to store large files here, and the whole software (repo + venv + containers) takes up ~17 GB.

In conjunction with conversations with @KshitijT and @healytwin1, I've been trying to build a version in `/idia/software/MeerKATHI`, including a python2 version, a python3 version, and a python3 version using the [cassie branch](https://github.com/ska-sa/meerkathi/tree/Cassie-final), as suggested by @KshitijT. The python2 version seemed to build fine, while the python3 versions output quite a few errors. The cassie branch had a few bugs in the `__init__.py` script that I fixed, but I still ended up getting the same error (see below).

The build script can be found here

`/idia/software/MeerKATHI/build_meerkathi.sbatch`

and the logs (stdout + stderr or each of the 3 versions I tried) can be found here:

`/idia/software/MeerKATHI/logs/`

I've been skipping the step to build the singularity containers for now (this is also why the python 2 version stderr includes `slurmstepd: error: *** JOB 226226 ON slwrk-401 CANCELLED AT 2019-10-10T13:37:30 ***`, since I cancelled the job during the container build step), and have simply using those available at `/users/pserra/STIMELA_SINGULARITY_IMAGES/`. For a comparison, I've been running `/users/pserra/meerkathi-venv/`, which seems to work on the helo fat node (but not on the SLURM worker nodes, for an unknown reason we're currently trying to work out).

I have not had any success with building and running MeerKATHI. Each time I run `meerkathi`, I get the same error below for all 3 versions. Commenting out the line to install from the requirements file seems to get the same result. I would prefer one of the developers debugged this rather than myself.

```
Traceback (most recent call last):
  File "/idia/software/MeerKATHI/meerkathi-venv-py3-cassie/bin/meerkathi", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/idia/software/MeerKATHI/meerkathi/bin/meerkathi", line 4, in <module>
    import meerkathi.main as main
  File "/idia/software/MeerKATHI/meerkathi/meerkathi/main.py", line 20, in <module>
    from meerkathi.view_controllers import event_loop
  File "/idia/software/MeerKATHI/meerkathi/meerkathi/view_controllers/__init__.py", line 3, in <module>
    from meerkathi.view_controllers.entry_form import entry_form
  File "/idia/software/MeerKATHI/meerkathi/meerkathi/view_controllers/entry_form.py", line 9, in <module>
    from meerkathi.view_controllers.option_editor import option_editor
  File "/idia/software/MeerKATHI/meerkathi/meerkathi/view_controllers/option_editor.py", line 188, in <module>
    class option_editor(npyscreen.FormBaseNew):
  File "/idia/software/MeerKATHI/meerkathi/meerkathi/view_controllers/option_editor.py", line 200, in option_editor
    def on_load(self, labeltype=npyscreen.TitleFilenameCombo, labeltext="Filename", editvalue=cp().args.config):
  File "/idia/software/MeerKATHI/meerkathi/meerkathi/dispatch_crew/config_parser.py", line 324, in __init__
    parser=parser)
  File "/idia/software/MeerKATHI/meerkathi/meerkathi/dispatch_crew/config_parser.py", line 418, in _subparser_tree
    default_value = subVars["example"]
  File "/idia/software/MeerKATHI/meerkathi-venv-py3-cassie/lib/python3.7/site-packages/ruamel/yaml/comments.py", line 753, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'example'
```

Once a stable version has been published, I suggest we put this in `/idia/software/MeerKATHI` as a master version that is only updated after sufficient testing. Development branches could then be made available as well - e.g. similar to the IDIA pipeline branches at `/idia/software/pipelines/{master,jordan-dev,dev}`.

Lastly, it may be helpful in your README to include a line for running MeerKATHI on ilifu, where you make it clear to use SLURM (e.g. an sbatch file or `srun` command).

**Comment by KshitijT** [comment]
Installed, broken, fixed, updated CARACal on ILIFU.

**Comment by KshitijT** [comment]
@paoloserra , could you please mention your procedure for CARACal installation on Slurm here?

**Comment by KshitijT** [comment]
Thanks to Jeremy (@Jordatious please add Jeremy's GitHub handle here), we now know the procedure to install CARACal on Ilifu Slurm.
I have installed it following the procedure detailed on "Installation" page of the repository (still in #1311 ) and it seems to work fine. If anyone runs into trouble following the instructions, please reopen the issue, which I am closing now.
