### ISSUE TITLE
Workers of the world, ~uni~ image your secondary

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#668]
...you have nothing to lose except your Jones chains?

Seriously though, a conversation with @bennahugo put me to mind of this. A second round of flagging works best if you give it residual visibilities. For the primary, these are straightforward to obtain, since we have a proper visibility model to begin with. For the secondary, we don't have a model as such (only the [1,0,0,0] model implicit in the gaincal). However, if we run a round of imaging on the secondary, we get a proper MODEL_DATA column and we can form up the residuals to flag on.

I think we should do this routinely. It wouldn't take that long (certainly less time than the flagging itself). It would also provide a useful diagnostic, since we often wonder if our secondaries are resolved and/or contaminated by field structure. And we could even do a second round of 1GC using the model visibilities, and presumably get better gain solutions. What's there not to like?

**Comment by gigjozsa** [comment]
@o-smirnov I suggest to add this to the 1.1 project and adding milestone 1.1 if this has not been covered yet.

**Comment by gigjozsa** [comment]
Or close.

**Comment by o-smirnov** [comment]
In principle it was covered in R1.0, but I'd like to keep this open for discussion and follow-up testing, as it's a relatively new approach. Can we have a label for ongoing tech discussions?

**Comment by o-smirnov** [comment]
lol just had a scroll through our selection of labels and ran away... can't deal....
