### ISSUE TITLE
add per-scan plots (phaseball, freq-phase, uvwl-ampl, uvwl-phase) to inspect_data worker 

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#713]
I've been finding the following kinds of plots very useful, and suggest adding them to inspect-data. They're all per-scan plots:

* Phaseballs (bpcal, gcal). Useful to see bad scans:

![image](https://user-images.githubusercontent.com/6470079/70444185-2c640d00-1aa2-11ea-9faa-b5318418d9b7.png)

* Freq vs corrected phase (bpcal, gcal). Useful to see bad scans/bad delays:

![image](https://user-images.githubusercontent.com/6470079/70443988-d8592880-1aa1-11ea-9eb0-5ef722d1cefe.png)

* UVwavelength versus corrected amplitude and phase (bpcal & gcal).

* UVwavelength vs corrected amplitude (target). Useful to see bad target scans:

![image](https://user-images.githubusercontent.com/6470079/70444021-e4dd8100-1aa1-11ea-97b5-a27ea89f1bfa.png)

That's a lot of invocations of ``plotms()`` ploughing through the entire MS though. Maybe @Mulan-94 can start thinking of a dask-ms/datashader version of these plots? If we could do a single pass through the MS and generate all five plots at once, that'd be awesome.

**Comment by SpheMakh** [comment]
Has this been added @Mulan-94 ?
