### ISSUE TITLE
reference antennas choice

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#98]
How is the reference antenna selected when observation_config:reference_antenna:auto ?

For IC5264 we used to use m006 as reference. However, the "auto" option selects m018 as reference, and results in m020 having no valid delay calibration.

**Comment by gigjozsa** [comment]
@paoloserra can this be closed?

**Comment by paoloserra** [comment]
yes, https://github.com/caracal-pipeline/caracal/pull/1235
